### PR TITLE
Removed moby from the linuxkit's push help

### PR DESCRIPTION
**Pull request by fntlnz**
Signed-off-by: Lorenzo Fontana <lo@linux.com>

### CODE REVIEW

**Comment by rneugeba** [comment]
actually, could you change this to what the `moby` tool does here: https://github.com/moby/tool/blob/master/cmd/moby/main.go#L48

**Comment by fntlnz** [comment]
@rneugeba at first instance I implemented it in that exact way but after I looked at [the other commands](https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/run.go#L24) and for consistency with them I choose to "hardcode" it.

If you prefer we can change those too

wdyt?

**Comment by rneugeba** [comment]
@fntlnz ah, I didn't see that this is also hardcoded elsewhere. Must have happened during the split. Would you mind changing the other hardcoded instances with `filepath.Base(os.Args[0])`? I think that is better/cleaner. But do hope we won't rename this again ;)

**Comment by fntlnz** [comment]
@rneugeba did it, it's quite a simple command line. I actually prefer this approach  instead of using some more complete but even heavy and complex command line library *at this stage*

**Comment by rneugeba** [comment]
@fntlnz thanks for the extra work beyond the initial fix

**Pull request merged**
