### PR TITLE
tools: Add VM integration agents to the Alpine base

### PR DESCRIPTION
**Pull request by rneugeba**
Add the Qemu, Hyper-V and VMware VM tools to the base

Also update the versions file.

Signed-off-by: Rolf Neugebauer <rolf.neugebauer@docker.com>

### CODE REVIEW

**Comment by rneugeba** [comment]
@MagnusS this add the `hvtools` package which is needed for some Docker for Windows packages. I may add them later this week, if I get around.

@ijc25 this contains the qemu agent for #1883

Once the push finishes this will be available as linuxkit/alpine:dc7d4cdb5932f3e6ff62172c05627816c0d412fa

**Comment by justincormack** [comment]
LGTM

**Comment by rneugeba** [comment]
Full hash: `linuxkit/alpine:dc7d4cdb5932f3e6ff62172c05627816c0d412fa@sha256:0239e6984a9932bfe1b44dc9be6f8e4c29dd7bdb431ba0b040b6d027b1091f08`

**Comment by ijc25** [comment]
> @ijc25 this contains the qemu agent for #1883

Thanks!

**Pull request merged**
