### PR TITLE
fix dns not working in the docker blueprint

### PR DESCRIPTION
**Pull request by dprotaso**
Signed-off-by: dave <dprotaso@gmail.com>

**- What I did**

`docker pull` was failing due to dns issues. We now bind the host's /etc/resolv.conf

**- How to verify it**
From the machine running the VM (in my case a Mac)
```
docker -H unix://docker-for-mac-state/guest.00000948 pull hello-world
```

### CODE REVIEW

**Comment by justincormack** [comment]
Ah sorry I thought I added these everywhere...

@djs55 this is not in the blueprint, should it be there too?

**Comment by djs55** [comment]
In the d4m blueprint I've currently got
```
            "/run/resolvconf/resolv.conf:/etc/resolv.conf", \
```
-- should that be `/etc/resolv.conf:/etc/resolv.conf` instead?

**Comment by justincormack** [comment]
Oh sorry I missed that, yes that is fine. It doesn't matter much as `runc` resolves symlinks before doing mounts.

**Comment by justincormack** [comment]
@djs55 it is not in https://github.com/linuxkit/linuxkit/blob/master/blueprints/docker-for-mac/docker-ce.yml though

**Pull request merged**
