### PR TITLE
Revert "wireguard: add to getty and sshd"

### PR DESCRIPTION
**Pull request by riyazdf**
Some discussion on https://github.com/linuxkit/linuxkit/pull/2266 was fragmented across other mediums and it appears that there was not agreement.

Revert in the meantime while we discuss and determine the best path forward.

### CODE REVIEW

**Comment by justincormack** [comment]
I am ok with leaving this in for now, and removing when there is a better
example of a real setup (thinking about how to do that sensibly, it needs
some changes)

**Comment by zx2c4** [comment]
That makes sense to me. We'd keep things like this now, so people can easily play, and then once there's a `pkg/wireguard` and other things, we remove it.

**Comment by rn** [comment]
I'm also ok with leaving this in for now as it is quite nice to play with it. But we should remove it at some point because it doesn't belong here and network config should be done differently anyway

**Comment by justincormack** [comment]
Closing for now as no appetite for revert and it would need updating should we decide to.

**Pull request closed without merging**
