### PR TITLE
tools/alpine: Update alpine base to include wireguard tools

### PR DESCRIPTION
**Pull request by rn**
Signed-off-by: Rolf Neugebauer <rolf.neugebauer@docker.com>

elephants

### CODE REVIEW

**Comment by justincormack** [comment]
The `versions` file doesnt have `wireguard-tools` in...

**Comment by rn** [comment]
ah, yes. I think the add is in the wrong place. closing this until fixed

**Comment by ijc** [comment]
The reordering of `versions` here is very odd (and no doubt obscured the fact that wireguard wasn't really added). Perhaps an `LC_COLLATE` issue?

**Comment by ijc** [comment]
Perhaps `s/sort/LANG=C sort/` in the appropriate place in `tools/alpine/Makefile`?

**Comment by ijc** [comment]
BTW It's not that the add is in the wrong place per se, it is that the add should instead be a new line in `versions` so it gets added to the mirror not the image filesystem.

BTW2, it seems likely the ovmf addition is in the wrong place too...

**Comment by ijc** [comment]
I see. Might be better to rework that while fixing the other stuff and have the qemu image include ovmf in its apk add.

**Pull request closed without merging**
