### PR TITLE
move pkg config from Dockerfile to build.yml

### LINKED ISSUE #2999: Move remaining LABEL definitions to build.yml
There are a bunch of packages (and possibly elsewhere) which define the container configuration via a `LABEL` in the `Dockerfile`. These should be converted to use the far more readable definition via the `configuration` entry in the `build.yml`

### PR DESCRIPTION
**Pull request by w9n**
**- What I did**

convert config json from Dockerfile label to build.yml

fixes #2999

This will break docker build compatibility

**- How I did it**

http://convertjson.com/json-to-yaml.htm

**- How to verify it**

CI

**- Description for the changelog**

move pkg config from Dockerfile to build.yml

**- A picture of a cute animal (not mandatory but encouraged)**

cleaning monkey

### CODE REVIEW

**Comment by ijc** [comment]
CI is being hit by the current golint git repo snafu.

**Comment by rn** [comment]
I'm in the process to build the images as it would be good to run these changes through CI. @w9n Thanks for doing this. Much nicer/cleaner now

**Comment by deitch** [comment]
Much much nicer!

**Comment by rn** [comment]
@w9n I've built/pushed all packages. It would be great if you could add a comit to this PR updating the hashes in the YAML files

**Comment by ijc** [comment]
I've kicked CI to have another go at this now that golint is fixed.

I'm holding off on a bump to containerd v1.1.0 until this one is in.

**Comment by rn** [comment]
I've checked a few of the updated packages and hashes and since CI is green, I'll merge

**Pull request merged**
