### PR TITLE
pkg/trim-after-delete: make docker socket path configurable

### PR DESCRIPTION
**Pull request by thaJeztah**
Docker Desktop proxies the docker socket at its default location
(/var/run/docker.sock), but allows connecting to the non-proxied
socket through /var/run/docker.sock.raw.

This patch allows the trim-after-delete utility to customize
the docker socket path, so that it can connect to the non-proxied
socket.

Related: https://github.com/linuxkit/linuxkit/pull/3539

**- Description for the changelog**

```markdown
Add `-docker-socket` flag to `trim-after-delete` utility
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@djs55 @justincormack PTAL

**Review by djs55 — DISMISSED** [review]
Makes sense to me!

**Comment by rn** [comment]
Apologies for the long delay. Could you please rebase since i merged the other `trim-after-delete` PR. I'll then push a new package and example needs updating.

**Comment by thaJeztah** [comment]
Wah! missed your comment; rebased 👍

**Review by djs55 — APPROVED** [review]
LGTM, sorry for the delay!

**Pull request merged**
