### PR TITLE
Fix: #3799 golint requires comments on non-main package for blank import

### PR DESCRIPTION
**Pull request by waldner**
Signed-off-by: Davide Brini <waldner@katamail.com>

### CODE REVIEW

**Comment by deitch** [comment]
Of course, it would be my commit that broke this. The original PR is [here](https://github.com/linuxkit/linuxkit/pull/3791). What I find surprising is that CI was clean for that; checks are [here](https://github.com/linuxkit/linuxkit/pull/3791/checks).

Either way, we should fix it.

**Review by deitch — CHANGES_REQUESTED** [review]
Can you remove the line:

```go
// fix: #3799 
```

We shouldn't have that directly in the code. Other that that, LGTM/.

**Comment by waldner** [comment]
Well, I copied it from #3743, that's why I included that line. But I'll remove it, of course.

**Comment by deitch** [comment]
Thanks. CI takes quite a while to run, but once it is clear, I will merge it in

**Pull request merged**
