### PR TITLE
Updated Compose and Docker versions.

### PR DESCRIPTION
**Pull request by jmccoy555**
Signed-off-by: James McCoy <james@mcy.email>

**- What I did**
Updated Compose and Docker versions in the Dockerfile.

**- How I did it**
Updated the version and download links.

**- How to verify it**
Built locally and rebuilt linuxkit

**- Description for the changelog**

Updated Compose image to 1.23.2 and Docker versions to 18.06.3-ce.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jmccoy555** [comment]
Can someone trigger the docker hub build?

**Comment by deitch** [comment]
> trigger the docker hub build

I don't understand. There isn't any image `linuxkit/compose` per se. This is just a reference project. Or did I miss something?

**Comment by jmccoy555** [comment]
Hummmm......

Image is [here](https://hub.docker.com/r/linuxkitprojects/compose) unelss linuxkitprojects is nothing to do with linuxkit???

But then the image is referenced in [here](https://github.com/linuxkit/linuxkit/blob/master/projects/compose/compose-dynamic.yml)

**Comment by deitch** [comment]
No, you're right. My addled Sunday brain. I will push it out.

**Comment by deitch** [comment]
`linuxkitprojects/compose:111f9f32a933c9e7acbf3ccfc13fedbdfce8224f` pushed

**Pull request merged**
