### PR TITLE
Upgrade bcc to 0.20.0 and re-enable it in the kernel build

### LINKED ISSUE #3652: bcc fails to compile with alpine 3.13
With the soon to be updated kernel build to the `linuxkit/alpine` based on 3.13, `lixnukti/kernel-bcc` fails to compile.

After a few warnings about `size_t` and `const counter_type` size mismatches we get:

```
/build/bcc/src/cc/frontends/b/lexer.h:61:38: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'const counter_type' {aka 'const int'} [-Wsign-compare]
   61 |       } else if (i > begin.line && i == end.line) {
      |                                    ~~^~~~~~~~~~~
/build/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function 'virtual ebpf::StatusTuple ebpf::cc::CodegenLLVM::visit_string_expr_node(ebpf::cc::StringExprNode*)':
/build/bcc/src/cc/frontends/b/codegen_llvm.cc:429:55: warning: 'llvm::CallInst* llvm::IRBuilderBase::CreateMemCpy(llvm::Value*, unsigned int, llvm::Value*, unsigned int, uint64_t, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)' is deprecated [-Wdeprecated-declarations
]
  429 |   B.CreateMemCpy(ptr, 1, global, 1, n->val_.size() + 1);
      |                                                       ^
In file included from /usr/lib/llvm10/include/llvm/Support/AlignOf.h:16,
                 from /usr/lib/llvm10/include/llvm/ADT/SmallVector.h:17,
                 from /usr/lib/llvm10/include/llvm/ADT/Twine.h:12,
                 from /usr/lib/llvm10/include/llvm/IR/BasicBlock.h:17,
                 from /build/bcc/src/cc/frontends/b/codegen_llvm.cc:21:
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:523:17: note: declared here
  523 |       CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src,
      |                 ^~~~~~~~~~~~
/usr/lib/llvm10/include/llvm/Support/Compiler.h:305:3: note: in definition of macro 'LLVM_ATTRIBUTE_DEPRECATED'
  305 |   decl __attribute__((deprecated))
      |   ^~~~
/build/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function 'virtual ebpf::StatusTuple ebpf::cc::CodegenLLVM::visit_table_index_expr_node(ebpf::cc::TableIndexExprNode*)':
/build/bcc/src/cc/frontends/b/codegen_llvm.cc:824:96: error: no matching function for call to 'llvm::IRBuilder<>::CreateMemSet(llvm::Value*&, llvm::ConstantInt*, llvm::ConstantInt*, int)'
  824 |     B.CreateMemSet(leaf_ptr, B.getInt8(0), B.getInt64(n->table_->leaf_id()->bit_width_ >> 3), 1);
      |                                                                                                ^
In file included from /build/bcc/src/cc/frontends/b/codegen_llvm.cc:31:
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:452:13: note: candidate: 'llvm::CallInst* llvm::IRBuilderBase::CreateMemSet(llvm::Value*, llvm::Value*, uint64_t, llvm::MaybeAlign, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)'
  452 |   CallInst *CreateMemSet(Value *Ptr, Value *Val, uint64_t Size,
      |             ^~~~~~~~~~~~
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:453:37: note:   no known conversion for argument 4 from 'int' to 'llvm::MaybeAlign'
  453 |                          MaybeAlign Align, bool isVolatile = false,
      |                          ~~~~~~~~~~~^~~~~
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:460:13: note: candidate: 'llvm::CallInst* llvm::IRBuilderBase::CreateMemSet(llvm::Value*, llvm::Value*, llvm::Value*, llvm::MaybeAlign, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)'
  460 |   CallInst *CreateMemSet(Value *Ptr, Value *Val, Value *Size, MaybeAlign Align,
      |             ^~~~~~~~~~~~
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:460:74: note:   no known conversion for argument 4 from 'int' to 'llvm::MaybeAlign'
  460 |   CallInst *CreateMemSet(Value *Ptr, Value *Val, Value *Size, MaybeAlign Align,
      |                                                               ~~~~~~~~~~~^~~~~
/build/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function 'virtual ebpf::StatusTuple ebpf::cc::CodegenLLVM::visit_struct_variable_decl_stmt_node(ebpf::cc::StructVariableDeclStmtNode*)':
/build/bcc/src/cc/frontends/b/codegen_llvm.cc:1006:79: error: no matching function for call to 'llvm::IRBuilder<>::CreateMemSet(llvm::AllocaInst*&, llvm::ConstantInt*, llvm::ConstantInt*, int)'
 1006 |       B.CreateMemSet(ptr_a, B.getInt8(0), B.getInt64(decl->bit_width_ >> 3), 1);
      |                                                                               ^
In file included from /build/bcc/src/cc/frontends/b/codegen_llvm.cc:31:
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:452:13: note: candidate: 'llvm::CallInst* llvm::IRBuilderBase::CreateMemSet(llvm::Value*, llvm::Value*, uint64_t, llvm::MaybeAlign, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)'
  452 |   CallInst *CreateMemSet(Value *Ptr, Value *Val, uint64_t Size,
      |             ^~~~~~~~~~~~
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:453:37: note:   no known conversion for argument 4 from 'int' to 'llvm::MaybeAlign'
  453 |                          MaybeAlign Align, bool isVolatile = false,
      |                          ~~~~~~~~~~~^~~~~
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:460:13: note: candidate: 'llvm::CallInst* llvm::IRBuilderBase::CreateMemSet(llvm::Value*, llvm::Value*, llvm::Value*, llvm::MaybeAlign, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)'
  460 |   CallInst *CreateMemSet(Value *Ptr, Value *Val, Value *Size, MaybeAlign Align,
      |             ^~~~~~~~~~~~
/usr/lib/llvm10/include/llvm/IR/IRBuilder.h:460:74: note:   no known conversion for argument 4 from 'int' to 'llvm::MaybeAlign'
  460 |   CallInst *CreateMemSet(Value *Ptr, Value *Val, Value *Size, MaybeAlign Align,
      |                                                               ~~~~~~~~~~~^~~~~
make[2]: *** [src/cc/frontends/b/CMakeFiles/b_frontend.dir/build.make:109: src/cc/frontends/b/CMakeFiles/b_frontend.dir/codegen_llvm.cc.o] Error 1
make[2]: Leaving directory '/build/bcc/build'
make[1]: *** [CMakeFiles/Makefile2:977: src/cc/frontends/b/CMakeFiles/b_frontend.dir/all] Error 2
make[1]: Leaving directory '/build/bcc/build'
make: *** [Makefile:163: all] Error 2
The command '/bin/sh -c mkdir -p bcc/build && cd bcc/build &&     cmake .. -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON              -DCMAKE_C_FLAGS="-I/build/usr/include"              -DCMAKE_CXX_FLAGS="-I/build/usr/include"              -DCMAKE_INSTALL_PREFIX=/usr              -DLUAJIT_INCLUDE_DI
R=/usr/include/luajit-2.1 &&     make &&     make install' returned a non-zero code: 2
make: *** [Makefile:251: build_bcc_5.11.x] Error 2
```

### PR DESCRIPTION
**Pull request by kmjohansen**
**- What I did**

I upgraded the bcc package in the kernel build to 0.20.0 and ensured that it builds on the current base image for the kernels that we presently support.

Fixes #3652

**- How I did it**

I eliminated a bunch of old patches in this build by switching to the `libelf-dev` package that's now coming in through our Alpine base image.  This allowed us to drop a bunch of steps in the build.  The failures that were observed seem to mostly be the result of new checks introduced in `llvm10` and a bit of weirdness between the `musl` runtime vs `glibc`.  The upgrade to the new `bcc` version contained fixes that address the `llvm10` issues.  The build itself required only a minor change to an `include` in order to address the `musl` vs `glibc` discrepancy.

**- How to verify it**

The simplest way to do this is to issue the following from the root of your linuxkit tree:
```
make -C kernel build_bcc_5.11.x && make -C kernel build_bcc_5.10.x && make -C kernel build_bcc_5.10.x-dbg && make -C kernel build_bcc_5.4.x
```

**- Description for the changelog**
Upgrade bcc to 0.20.0 and re-enable it in the kernel build.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by kmjohansen** [comment]
@rn would you be willing to give this PR a look when you get a chance?  I opened it in response to our discussion in 3675 and 3652.

**Comment by rn** [comment]
@kmjohansen Yes I will. Thanks for the PR. I was going to pick this up on the next kernel update but was busy lately.

**Comment by kmjohansen** [comment]
@rn Awesome; thanks!  No rush.  Just wanted to make sure that it hadn't fallen through the cracks.

**Review by rn — APPROVED** [review]
Thanks for updating this. I build tested and i did not get failures. Will properly push with the next kernel update

**Pull request merged**
