### PR TITLE
tools/alpine: Add nfs-utils

### PR DESCRIPTION
**Pull request by errordeveloper**
Needed for Kubernetes to pass more e2e tests.

### CODE REVIEW

**Comment by justincormack** [comment]
If someone has a chance to rebuild and push the package that would be great (tied up right now)

**Comment by justincormack** [comment]
Its probably ok to open a PR with just the `packages` file changes but not the versions.

**Comment by rn** [comment]
that works too, but given that whoever then pushes has to do another PR, it's probably easier to just do everything in one commit

**Comment by errordeveloper** [comment]
> that works too, but given that whoever then pushes has to do another PR, it's probably easier to just do everything in one commit

@rn makes sense, thanks!

**Comment by rn** [comment]
see #2573

**Pull request closed without merging**
