### PR TITLE
Bump containerd to v1.3.0

### PR DESCRIPTION
**Pull request by rn**
image

### CODE REVIEW

**Comment by rn** [comment]
The `containerd` test seems to time out

**Comment by rn** [comment]
Ah, the VM doesn't boot completely because there is not enough memory to unpack the initrd. If I bump the memory the test still fails because `dmsetup` can't be found. Will add that to the alpine base and the containerd test.

**Comment by rn** [comment]
Update packages, let's see how this goes

**Comment by rn** [comment]
containerd test also needed mkfs.ext4. Updated

**Comment by hyperized** [comment]
We believe this might fix the missing `containerd-shim-runc-v2` in containerd:

```docker
FROM linuxkit/alpine:6906a00130f0b0209db8cc50803b7423e0c3f245 as alpine
RUN apk add tzdata

WORKDIR $GOPATH/src/github.com/containerd/containerd
# Copy all binaries to /usr/bin/containerd
RUN cp -r bin /usr/bin/containerd

RUN mkdir -p /etc/init.d && ln -s /usr/bin/service /etc/init.d/020-containerd

FROM scratch
ENTRYPOINT []
WORKDIR /
# Copy all the files back to /usr/bin
COPY --from=alpine /usr/bin/containerd/ /usr/bin/
COPY config.toml /etc/containerd/config.toml
COPY --from=alpine /etc/init.d/ /etc/init.d/
COPY --from=alpine /usr/share/zoneinfo/UTC /etc/localtime
```

This is the most likely cause of the timeout in the build process, since nothing will work as containerd is part of the init.

**Comment by rn** [comment]
I'm getting more devmapper failures on this:

```
[  162.707396] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
[  162.784817] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
[  162.791466] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
[  162.982362] device-mapper: thin: 253:0: reached low water mark for data device: sending event.
[  163.455847] device-mapper: thin: Deletion of thin device 1 failed.
[  163.858095] device-mapper: table: 253:2: thin-pool: metadata device already in use by a pool
[  163.860752] device-mapper: ioctl: error adding target to table
[  164.003180] device-mapper: thin: 253:2: reached low water mark for data device: sending event.
[  164.770617] device-mapper: thin: 253:2: reached low water mark for data device: sending event.
[  165.850804] device-mapper: thin: 253:2: reached low water mark for data device: sending event.
[  170.353552] device-mapper: thin: 253:2: reached low water mark for data device: sending event.
[  171.101695] device-mapper: thin: 253:2: reached low water mark for data device: sending event.
[  172.193161] device-mapper: thin: 253:2: reached low water mark for data device: sending event.
[  172.718004] device-mapper: table: 253:4: thin-pool: metadata device already in use by a pool
[  172.719562] device-mapper: ioctl: error adding target to table
[  172.828076] device-mapper: thin: 253:4: reached low water mark for data device: sending event.
[  173.055020] device-mapper: table: 253:6: thin-pool: metadata device already in use by a pool
[  173.057683] device-mapper: ioctl: error adding target to table
[  174.026216] device-mapper: thin: Creation of new thinly-provisioned device with id 1 failed.
[  174.059826] device-mapper: thin: Deletion of thin device 2 failed.
v1.3.0
36cf5b690dcc00ff0f34ff7799209050c3d0c59a
+ root-test
ok      github.com/containerd/containerd/archive        0.794s
ok      github.com/containerd/containerd/metadata       25.187s
ok      github.com/containerd/containerd/mount  0.448s
ok      github.com/containerd/containerd/snapshots/btrfs        38.341s
time="2020-01-07T22:17:42Z" level=info msg="initializing pool device \"test-pool-device-467583520\""
time="2020-01-07T22:17:42Z" level=info msg="using dmsetup:\nLibrary version:   1.02.152 (2018-10-30)\nDriver version:    4.39.0"
--- FAIL: TestPoolDevice (0.29s)
    --- FAIL: TestPoolDevice/MakeFileSystem (0.00s)
        pool_device_test.go:228: assertion failed: error is not nil: exit status 1: failed to make filesystem on 'thin-1': mke2fs 1.44.5 (15-Dec-2018)
            mkfs.ext4: invalid blocks '-E' on device '/dev/mapper/thin-1'

    pool_device_test.go:134: assertion failed: error is not nil: failed to mount /var/lib/tmp/containerd-mount523371319: invalid argument
[...]
time="2020-01-07T22:18:31Z" level=debug msg=close
time="2020-01-07T22:18:31Z" level=info msg="initializing pool device \"containerd-snapshotter-suite-pool-213498420\""
time="2020-01-07T22:18:31Z" level=info msg="using dmsetup:\nLibrary version:   1.02.152 (2018-10-30)\nDriver version:    4.39.0"
time="2020-01-07T22:18:31Z" level=debug msg=close
--- FAIL: TestSnapshotterSuite (0.59s)
    --- FAIL: TestSnapshotterSuite/RemoveIntermediateSnapshot (0.96s)
        log_hook.go:40: time="2020-01-07T22:18:21.413438267Z" level=debug msg=prepare key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/base parent=
        log_hook.go:40: time="2020-01-07T22:18:21.419525967Z" level=debug msg="creating new thin device 'containerd-snapshotter-suite-pool-367454947-snap-1'"
        log_hook.go:40: time="2020-01-07T22:18:21.455819032Z" level=debug msg="mkfs.ext4 -E nodiscard,lazy_itable_init=0,lazy_journal_init=0 /dev/mapper/containerd-snapshotter-suite-pool-367454947-snap-1"
        log_hook.go:40: time="2020-01-07T22:18:21.516504011Z" level=debug msg="mkfs:\nmke2fs 1.44.5 (15-Dec-2018)\nCreating filesystem with 16384 1k blocks and 4096 inodes\nFilesystem UUID: 366a81f7-b377-462d-be50-8295c663be03\nSuperblock backups stored on blocks: \n\t8193\n\nAllocating
 group tables: 0/2\b\b\b   \b\b\bdone                            \nWriting inode tables: 0/2\b\b\b   \b\b\bdone                            \nCreating journal (1024 blocks): done\nWriting superblocks and filesystem accounting information: 0/2\b\b\b   \b\b\bdone\n\n"
        log_hook.go:40: time="2020-01-07T22:18:21.574078354Z" level=debug msg=commit key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/base name=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-base
        log_hook.go:40: time="2020-01-07T22:18:21.612649844Z" level=debug msg=prepare key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/intermediate parent=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-base
        log_hook.go:40: time="2020-01-07T22:18:21.612718867Z" level=debug msg="creating snapshot device 'containerd-snapshotter-suite-pool-367454947-snap-2' from 'containerd-snapshotter-suite-pool-367454947-snap-1'"
        log_hook.go:40: time="2020-01-07T22:18:21.678169754Z" level=debug msg=commit key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/intermediate name=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-inter
        log_hook.go:40: time="2020-01-07T22:18:21.717821337Z" level=debug msg=prepare key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/toplayer parent=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-inter
        log_hook.go:40: time="2020-01-07T22:18:21.717889525Z" level=debug msg="creating snapshot device 'containerd-snapshotter-suite-pool-367454947-snap-3' from 'containerd-snapshotter-suite-pool-367454947-snap-2'"
        log_hook.go:40: time="2020-01-07T22:18:21.817611973Z" level=debug msg=remove key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-inter
        log_hook.go:40: time="2020-01-07T22:18:21.817668144Z" level=debug msg="snapshotter error" error="1 error occurred:\n\t* cannot remove snapshot with child: failed precondition\n\n"
        log_hook.go:40: time="2020-01-07T22:18:21.817703834Z" level=debug msg=remove key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/toplayer
        log_hook.go:40: time="2020-01-07T22:18:21.880549162Z" level=debug msg=remove key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-inter
        helpers_unix.go:32: unmount /var/lib/tmp/snapshot-suite-devmapper-784761760/work/base
        log_hook.go:40: time="2020-01-07T22:18:21.911780133Z" level=debug msg=remove key=/var/lib/tmp/snapshot-suite-devmapper-784761760/work/committed-base
        log_hook.go:40: time="2020-01-07T22:18:21.941075965Z" level=error msg="failed to remove device" error="failed to delete device \"containerd-snapshotter-suite-pool-367454947-snap-1\" (dev id: 1): 1 error occurred:\n\t* dmsetup message containerd-snapshotter-suite-pool-367454947 0
 delete 1\nerror: device-mapper: message ioctl on containerd-snapshotter-suite-pool-367454947  failed: Resource busy\nCommand failed.\n\n: exit status 1\n\n"
        log_hook.go:40: time="2020-01-07T22:18:21.941128570Z" level=debug msg="snapshotter error" error="1 error occurred:\n\t* failed to delete device \"containerd-snapshotter-suite-pool-367454947-snap-1\" (dev id: 1): 1 error occurred:\n\t* dmsetup message containerd-snapshotter-suite
-pool-367454947 0 delete 1\nerror: device-mapper: message ioctl on containerd-snapshotter-suite-pool-367454947  failed: Resource busy\nCommand failed.\n\n: exit status 1\n\n\n\n"
        testsuite.go:545: failed to delete device "containerd-snapshotter-suite-pool-367454947-snap-1" (dev id: 1): 1 error occurred:
                * dmsetup message containerd-snapshotter-suite-pool-367454947 0 delete 1
            error: device-mapper: message ioctl on containerd-snapshotter-suite-pool-367454947  failed: Resource busy
            Command failed.

            : exit status 1


        helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-devmapper-784761760
        helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-devmapper-784761760/root
        helpers.go:65: -rw-------      32768 /var/lib/tmp/snapshot-suite-devmapper-784761760/root/containerd-snapshotter-suite-pool-367454947.db [ "\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\xed\xda\f\xed\x02\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x04\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00" ...]
        helpers.go:65: -rw-------  134217728 /var/lib/tmp/snapshot-suite-devmapper-784761760/root/devmapper-snapshotter-tests-265165266 [ "\xd5P\xac\xef\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbaR\x9c\x01\x00\x00\x
00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ...]
        helpers.go:65: -rw-------  134217728 /var/lib/tmp/snapshot-suite-devmapper-784761760/root/devmapper-snapshotter-tests-782965887 [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ...]
        helpers.go:65: -rw-------      65536 /var/lib/tmp/snapshot-suite-devmapper-784761760/root/metadata.db [ "\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\xed\xda\f\xed\x02\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\a\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00\x00\x00\x00\x00" ...]
        helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-devmapper-784761760/work
        helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-devmapper-784761760/work/base
    snapshotter_test.go:56: assertion failed: error is not nil: dmsetup create containerd-snapshotter-suite-pool-327564275 --table 0 262144 thin-pool /dev/loop1 /dev/loop0 128 32768 1 skip_block_zeroing
        error: device-mapper: reload ioctl on containerd-snapshotter-suite-pool-327564275  failed: Resource busy
        Command failed.

        : exit status 1: failed to create pool "containerd-snapshotter-suite-pool-327564275"
    --- FAIL: TestSnapshotterSuite/DirectoryPermissionOnCommit (0.03s)
        testing.go:782: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
    snapshotter_test.go:56: assertion failed: error is not nil: dmsetup create containerd-snapshotter-suite-pool-186559816 --table 0 262144 thin-pool /dev/loop3 /dev/loop2 128 32768 1 skip_block_zeroing
        error: device-mapper: reload ioctl on containerd-snapshotter-suite-pool-186559816  failed: Resource busy
        Command failed.

        : exit status 1: failed to create pool "containerd-snapshotter-suite-pool-186559816"
    --- FAIL: TestSnapshotterSuite/TransitivityTest (0.03s)
        testing.go:782: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
    snapshotter_test.go:56: assertion failed: error is not nil: dmsetup create containerd-snapshotter-suite-pool-527470868 --table 0 262144 thin-pool /dev/loop5 /dev/loop4 128 32768 1 skip_block_zeroing
        error: device-mapper: reload ioctl on containerd-snapshotter-suite-pool-527470868  failed: Resource busy
        Command failed.

        : exit status 1: failed to create pool "containerd-snapshotter-suite-pool-527470868"
    --- FAIL: TestSnapshotterSuite/StatActive (0.03s)                                                                                                                                                                                                                                  [0/7815]
        testing.go:782: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
FAIL    github.com/containerd/containerd/snapshots/devmapper    49.466s
--- FAIL: TestDMSetup (5.01s)
    --- FAIL: TestDMSetup/ActivateDevice (0.01s)
        dmsetup_test.go:129: assertion failed: dmsetup create test-device --table 0 2 thin /dev/mapper/test-pool 1
            error: device-mapper: create ioctl on test-device  failed: Resource busy
            Command failed.

            : exit status 1 (err *errors.withStack) != device or resource busy (unix.EBUSY syscall.Errno)
    --- FAIL: TestDMSetup/RemoveDevice (0.00s)
        dmsetup_test.go:177: assertion failed: expression is false: err == unix.EBUSY: removing thin-pool with dependencies shouldn't be allowed
    --- FAIL: TestDMSetup/RemovePool (4.83s)
        dmsetup_test.go:93: assertion failed: error is not nil: dmsetup remove --force --retry /dev/mapper/test-pool
            error: device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            device-mapper: remove ioctl on test-pool  failed: Resource busy
            Command failed.

            : exit status 1: failed to remove thin-pool
FAIL
FAIL    github.com/containerd/containerd/snapshots/devmapper/dmsetup    5.014s
ok      github.com/containerd/containerd/snapshots/devmapper/losetup    0.099s
ok      github.com/containerd/containerd/snapshots/native       11.938s
ok      github.com/containerd/containerd/snapshots/overlay      12.860s
containerd test suite FAILED
make: *** [Makefile:168: root-test] Error 1




[  370.289045] INFO: task poweroff:7149 blocked for more than 120 seconds.
[  370.291187]       Tainted: G                T 4.19.90-linuxkit #1
[  370.293071] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  370.295476] poweroff        D    0  7149   7137 0x00000000
[  370.297179] Call Trace:
[  370.298030]  ? __schedule+0x522/0x57f
[  370.299203]  ? preempt_schedule_irq+0x45/0x45
[  370.300554]  ? schedule+0x60/0x71
[  370.301302]  ? schedule_timeout+0x3b/0xf4
[  370.302034]  ? io_schedule_timeout+0x1b/0x3d
[  370.302855]  ? __wait_for_common+0x10d/0x1b2
[  370.303623]  ? wake_up_q+0x45/0x45
[  370.304246]  ? submit_bio_wait+0x5d/0x81
[  370.304985]  ? blkdev_issue_flush+0x7b/0x9f
[  370.305727]  ? ext4_sync_fs+0x153/0x17c
[  370.306428]  ? vfs_fsync+0x18/0x18
[  370.307052]  ? iterate_supers+0x83/0xcf
[  370.307738]  ? ksys_sync+0x60/0xa4
[  370.308359]  ? __ia32_sys_sync+0xa/0xd
[  370.309040]  ? do_syscall_64+0x56/0x64
[  370.309708]  ? entry_SYSCALL_64_after_hwframe+0x44/0xa9
```

**Comment by rn** [comment]
closing in favour of https://github.com/linuxkit/linuxkit/pull/3458

**Pull request closed without merging**
