### PR TITLE
Spelling error: Dautenhan -> Dautenhahn

### PR DESCRIPTION
**Pull request by ndauten**
Signed-off-by: Nathan Dautenhahn <ndd@cis.upenn.edu>

**- What I did**
Fix mispelling

**- How I did it**
Straight up

**- How to verify it**

**- Description for the changelog**

Correct spelling mistake

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by justincormack** [comment]
Thanks!

**Comment by ndauten** [comment]
@justincormack never done a PR like this on github. I'm not sure if I needed to ping you here or if it will automatically show up for you.

**Comment by ndauten** [comment]
Okay, it does notify you fast :), faster than I can comment.

**Comment by justincormack** [comment]
:)

**Pull request merged**
