### PR TITLE
tools: Remove the CoreOS grub2 patches

### PR DESCRIPTION
**Pull request by arm64b**
Remove the grub2 patch from LinuxKit since it has already been merged
into the CoreOS grub2 mainline code.

Signed-off-by: Dennis Chen <dennis.chen@arm.com>

**- What I did**
Remove the CoreOS GRUB2 patches folder from LinuxKit
**- How I did it**
Upstream and merge the patch into CoreOS GRUB2 mainline code 
**- How to verify it**
`bin/linuxkit pkg build mkimage-{iso, raw}-efi`
`Generate the corresponding images with above tools.`
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
summit

### CODE REVIEW

**Comment by deitch** [comment]
@arm64b you got them upstreamed? Hats off to you.
Would you please put a link to the merged patch CoreOS/grub PR here, for referral sake?

I will run these locally as well and then approve.

**Comment by deitch** [comment]
We will need to update [this moby tool file](https://github.com/moby/tool/blob/master/src/moby/output.go) to use the right hashes here.

After test, I will push out with `linuxkit pkg` and then post the hashes here.

**Comment by arm64b** [comment]
Hello @deitch , The CoreOS Grub2 PR can be found at: [https://github.com/coreos/grub/pull/48](https://github.com/coreos/grub/pull/48)

**Comment by deitch** [comment]
Looks good. Nice job @arm64b .

Please open a PR for [output.go](https://github.com/moby/tool/blob/master/src/moby/output.go) to use the following image hashes:

* `linuxkit/mkimage-raw-efi:167441e223c1c131dac349deb67966d400066e04`
* `linuxkit/mkimage-iso-efi:43592c9b316b036338c4db9f90aada37b48415dc`

I pushed out on x86, pushing out on arm64 now.

**Comment by arm64b** [comment]
> Please open a PR for output.go to use the following image hashes:

> linuxkit/mkimage-raw-efi:167441e223c1c131dac349deb67966d400066e04
> linuxkit/mkimage-iso-efi:43592c9b316b036338c4db9f90aada37b48415dc

Just push a new PR to update the above hash value

**Comment by deitch** [comment]
Please link to the PR here.

Once @riyazdf or someone fixes that `linuxkit pkg push` issue with the last image on arm64b, we will be able to merge that one in.

**Comment by arm64b** [comment]
The moby/tool PR can be found at :[https://github.com/moby/tool/pull/177](https://github.com/moby/tool/pull/177)

**Pull request merged**
