### PR TITLE
update -rt to 4.19.106-rt46

### PR DESCRIPTION
**Pull request by TiejunChina**
update -rt to 4.19.106-rt46 and example.

### CODE REVIEW

**Comment by TiejunChina** [comment]
Looks those checks cannot fetch some packages.  It has nothing to do with the commits.

**Comment by rn** [comment]
@TiejunChina thanks for the update. I'll compile the kernel and re-kick Ci sometime this weekend.

Do you know of there is a 5.4.x version out yet? We recently switch to it being the default

**Comment by TiejunChina** [comment]
@rn Yeah, the latest is 5.4.28-rt19. I can make this if you think it's right time now.

**Comment by rn** [comment]
@TiejunChina 5.4.28-rt19 would be great.

Some of the CI failures were timeouts on Ubuntu packages (unrelated to this PR) so I re-kicked CI but now see more (unrelated) failures. Investigating.

**Comment by TiejunChina** [comment]
@rn linuxkit:5.4.28-rt is ready in my local repo. Once you can make this work, I will send out another PR.

**Comment by rn** [comment]
@TiejunChina I've build the kernels but github actions seem to be playing up. could you make a tiny change in the commit messages for the last commit (the one which updates the kernel in the YAMLs) and force push? That should re-trigger a CI run.

As for 5.4.x, happy to look at a PR, preferably the next couple of days as I may start releasing over easter. If you prepare a PR, please don't update the YAMLs (I'll do that) since that is guaranteed to fail CI till the kernels are pushed. Thanks

**Comment by TiejunChina** [comment]
@rn Looks ci/circleci and dco-signed are still in the process. It takes so long time. Is it okay?

**Comment by rn** [comment]
thanks for pushing the update. we have not found a way to turn off circle ci and the dco check

**Pull request merged**
