### PR TITLE
Fix missing Docker hub images

### PR DESCRIPTION
**Pull request by anonymuse**
Signed-off-by: Jesse White <anonymuse@gmail.com>

There are missing Docker hub images for the Kubernetes project, so I updated them to the latest of what's in Docker Hub.

### CODE REVIEW

**Comment by deitch** [comment]
How did this ever work? I don't see images with the tag `b0fa7a0191616ed8bef9b7d4a5014dffc62c2082` anywhere on the hub?

**Comment by justincormack** [comment]
We should just push the correct version not use the old one; will take a look later/tomorrow.

**Comment by anonymuse** [comment]
If I use that image and boot a node with `linuxkit`, it doesn't seem to pick up the Kubernetes software and there's no running kubelet container:

```
(ns: getty) linuxkit-56d19243838d:~# runc list
ID             PID         STATUS      BUNDLE                            CREATED                          OWNER
000-sysctl     0           stopped     /containers/onboot/000-sysctl     2017-10-29T20:01:27.131919739Z   root
001-sysfs      0           stopped     /containers/onboot/001-sysfs      2017-10-29T20:01:27.282334014Z   root
002-dhcpcd     0           stopped     /containers/onboot/002-dhcpcd     2017-10-29T20:01:27.491948616Z   root
003-metadata   0           stopped     /containers/onboot/003-metadata   2017-10-29T20:01:27.751741006Z   root
004-format     0           stopped     /containers/onboot/004-format     2017-10-29T20:01:42.472854584Z   root
005-mounts     0           stopped     /containers/onboot/005-mounts     2017-10-29T20:01:44.582320807Z   root
(ns: getty) linuxkit-56d19243838d:~# 
```

This is running on Ubuntu 16.04 with the following initialization:

```KUBE_RUN_ARGS="-publish 2222:22" ./boot.sh```

**Comment by justincormack** [comment]
I have pushed the correct ones now, so this should not be needed.

**Pull request closed without merging**
