### PR TITLE
Update kernels to 5.0.6/4.19.33/4.14.110/4.9.167

### PR DESCRIPTION
**Pull request by rn**
Note the somewhat gross hack in the second commit. The kernel compile for 5.06 started failing with the error mentioned in the commit message. I couldn't find a conclusive culprit, but fixing up the libelf header files seemed like the best way forward.

seabright-chicken

### CODE REVIEW

**Comment by justincormack** [comment]
I think we should have installed `elfutils-dev` which corresponds to what is recommended elsewhere, not `libelf-dev` that we have installed and seems to be a different elf library...

**Comment by rn** [comment]
thanks, will try that later today

**Comment by rn** [comment]
@justincormack your suggestion worked. Updated the PR and rebuild the kernels

**Comment by rn** [comment]
The `kmod` build tests failed due to incompatible `libelf` (it installed `libelf-dev`. A new commit fixes this

**Pull request merged**
