### PR TITLE
RFC: Enable shellcheck for format package

### PR DESCRIPTION
**Pull request by majst01**
**- What I did**

**- How I did it**
This is the first step of verifying that all shell scripts are at least passing shellcheck.
**- How to verify it**
It is a integrated step in the Makefile.
**- Description for the changelog**
First release to get feedback from maintainers if this approach is feasible. If agreed, i will do this for all pkg applications.
**- A picture of a cute animal (not mandatory but encouraged)**
hamster

### CODE REVIEW

**Comment by justincormack** [comment]
I would rather we checked this globally as part of CI rather than on a per package basis. We really want to remove the per package Makefiles completely at some point.

**Comment by majst01** [comment]
So should i add these checks into to toplevel Makefile? I do not know how the datakit ci works.

**Comment by justincormack** [comment]
@majst01 if it is in the top level Makefile then we can add to tests yes. The other option that occured to me though is we could add it to the Dockerfile, like we do for the `go lint` etc tests, so if the shellcheck is in the base `linuxkit/alpine` image we can just run it after doing `COPY blah.sh /`. That way the Makefiles stay simple and it just gets done where needed.

**Comment by rneugeba** [comment]
@justincormack @majst01 I think I can add shellcheck to the alpine base. From `koalaman/shellcheck` we have:
```
/mnt # ldd /usr/local/bin/shellcheck
	/lib/ld-musl-x86_64.so.1 (0x557cc6ed6000)
	libgmp.so.10 => /usr/local/lib/libgmp.so.10 (0x7f67f2bbe000)
/mnt # ls -l /usr/local/bin/
total 15148
-rwxr-xr-x    1 root     root      15511160 May 25 02:36 shellcheck
/mnt # ls -l /usr/local/lib/
total 952
-rwxr-xr-x    1 root     root        563680 May 25 02:37 ld-musl-x86_64.so.1
-rwxr-xr-x    1 root     root        407272 May 25 02:37 libgmp.so.10
```
so we could just copy `/usr/local` from there into the base

**Comment by justincormack** [comment]
I would rather compile it from source than extract a binary from a random hub repo...

**Comment by rneugeba** [comment]
then we have to do this:
https://github.com/koalaman/shellcheck/blob/master/Dockerfile_builder

**Comment by justincormack** [comment]
Oh, I didnt realise it was written in Haskell, yeah maybe using the binary is better

**Comment by rneugeba** [comment]
OK, I have it added to the Alpine base. Should be in a PR later today

**Comment by majst01** [comment]
I think using the binary from the docker image from koalaman is ok because he is the author of shellcheck. Building it by our own is a bit difficult and only haskell guys know how :-)

After it is added to linuxkit/alpine i will change my PR to use it.

**Comment by rneugeba** [comment]
I've pushed the image to hub and you can use it as: `linuxkit/alpine:366c1f4a3244572e8acd5569a212a1c932495401`. I still need to update all the other packages to use it

**Comment by rneugeba** [comment]
actually, had to change the base image a bit more and the hash image is now:
`linuxkit/alpine:630ee558e4869672fae230c78364e367b8ea67a9`

**Comment by justincormack** [comment]
This no longer applies, so closing. We want to have this as a top level standalone option I think.

**Comment by majst01** [comment]
Of course, once i get some spare time again i will prepare another PR therefore.

**Comment by justincormack** [comment]
Thanks!

**Pull request closed without merging**
