### PR TITLE
Update containerd vendor

### PR DESCRIPTION
**Pull request by justincormack**
This fixes arm64 mac, just by updating containerd vendoring.

Signed-off-by: Justin Cormack <justin@specialbusservice.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by deitch** [comment]
Will this conflict with #3575 ?

**Comment by justincormack** [comment]
Yes. Needs a later containerd...

**Comment by deitch** [comment]
I don't see that as a major issue. But we don't know until we try.

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Approved. As soon as you have this merged in, I'll rebase the other one, test it, and you can approve that one.

**Comment by justincormack** [comment]
merged @deitch

**Comment by deitch** [comment]
Does lkt now build a binary for darwin-arm64, or is that still dependent on having go compiler for it? When done add it to our testing matrix?

**Pull request merged**
