### PR TITLE
add iscsi pkg

### PR DESCRIPTION
**Pull request by garthy**
Signed-off-by: Garth Bushell <garth@garthy.com>

**- Description for the changelog**

Add iscsi pkg

### CODE REVIEW

**Comment by eyz** [comment]
@garthy I also have an iscsi LinuxKit pkg, but I haven't submitted it as a PR. Do you have any need to also run `multipathd`, and do you have any config / metadata integration planned for this package?

**Comment by garthy** [comment]
So this is a work in progress. Our cloud boots of iSCSI with handover from IPXE/EFI. so this is needed at boot time. 

* For config the target name/IP/port is static so I can build that in to the image definition
* I'd missed the /dev and net namespace as what I know about linuxkit was from DockerCon today. I'll fix that up

Unfortunately I'm actually blocked from testing this by two other issues (Although maybe me not understandng stuff)
* ixegb[vf] drivers not build into kernel
* EFI QCOW2 image required

**Comment by justincormack** [comment]
@garthy do you want to open an issue for the things you need, and we can discuss in one place?

**Comment by rn** [comment]
Closing due to inactivity. As @justincormack suggested it might be best to first discuss iSCSI boot/root on an issue and then move on from there.

**Pull request closed without merging**
