### PR TITLE
Remove projects/kubernetes, moved to https://github.com/linuxkit/kubernetes

### LINKED ISSUE #2744: promote `projects/kubernetes` from incubation and split into separate repository
This is a second attempt at #2463. I believe there are now no fundamental blockers to moving into a separate repository, also the `cri-containerd` stuff is already integrated.

`git filter-branch` will be used to extract `projects/kubernetes` into the root of a new repository:
* `projects/kubernetes/kubelet` → `pkg/kubelet`
* `projects/kubernetes/image-cache` → `pkg/image-cache`
* `projects/kubernetes/cri-containerd` → `pkg/cri-containerd`
* `projects/kubernetes/{README.md,Makefile}` → top level.
* `projects/kubernetes/*.yml` → top level.
* `projects/kubernetes/*.sh` → `scripts/*.sh`

In addition we will want to carry over `AUTHORS`, `LICENSE`, `NOTICE`, `MAINTAINERS`, `CONTRIBUTING.md`, `poule.yml`, `.mailmap` and `.github` from the current project (in some cases they will need tailoring for the new environment, see below).

Other tasks (brain dump, will edit as things occur to me, some of these are longer term than the initial transition):
* [x] Get `poule` enabled (does this cover dco check?).
* [x] Regenerate `AUTHORS` for the new repo.
* [x] Rewrite `README.md` (was `projects/kubernetes/README.md`) into suitable top-level README.
* [x] Update `Makefile` in the same way:
  * [ ] Grab `bin/linuxkit` and `bin/moby` from their respective CI
  * [ ] ...
* [x] Check the other imported files for updates.
* [ ] Switch to packages `linuxkit` hub org.
* [ ] Enable signing/content trust for the pkg repos.
* [ ] GH config
  * [ ] labels
* [ ] CI (I plan to use circleci, same as `linuxkit/linuxkit`, will use this as an opportunity to prototype things like sensible secrets handling for possible pushing of builds to hub etc)
  * [ ] Build `pkg/*` on each PR (need to investigate circle gating functionality for `/ok-to-test` type functionality.
  * [ ] Push `pkg/*` to hub from on master (only?).
  * [ ] Build and publish (as artefacts) a matrix of images covering `KUBE_RUNTIME={docker,cri-containerd}` × `KUBE_NETWORK={weave,bridge}` (EFI and BIOS images in both cases). Perhaps only for `master` branch or perhaps build for all but publish only for `master`.
  * [ ] Automation for bumping linuxkit components (`pkg/{init,runc,...}`). Perhaps a bot or nightly cron which maintains a single open PR at a time which tracks the latest versions?
  * [ ] Running kube e2e tests (nightly? may need a second stage of CI after circle to allow the use of virtualisation)
  * [ ] Other testing, pull in rtf and write some tests?
  * [ ] Ensure `kube.yml` matches latest `pkg/*` tags in every PR.

### PR DESCRIPTION
**Pull request by ijc**
fix #2744

Signed-off-by: Ian Campbell <ijc@docker.com>

### CODE REVIEW

**Comment by ijc** [comment]
We should probably wait to merge this until we are completely happy with https://github.com/linuxkit/kubernetes and can tell contributors to cut over.

**Comment by justincormack** [comment]
Can you leave a small README redirecting to the new repo, as we gave out that url quite a bit, and also add a note in projects/README saying it has graduated and moved.

**Comment by ijc** [comment]
I was considering a general section for "related projects" in the README.md, will do both as you suggest.

**Comment by justincormack** [comment]
You missed https://github.com/linuxkit/linuxkit/blob/master/projects/README.md as well

**Pull request merged**
