### PR TITLE
Post v0.8 cleanup

### PR DESCRIPTION
**Pull request by rn**
- Bump version to v0.8+
- Update changelog (closes https://github.com/linuxkit/linuxkit/pull/3528)

cats

### CODE REVIEW

**Comment by deitch** [comment]
I want to "lgtm" this, and the simple changes on the first 2 files make sense, but what is the 3rd file, the `linuxkit-linux-amd64` file? Is that an accidental CLI build committed @rn ?

**Comment by rn** [comment]
Good catch. Removed and force pushed

**Comment by deitch** [comment]
I am very confused @rn. This shows 6 files changed, 3 of which are in `src/cmd/linuxkit/`. But the changes on this files are things that already are in there. Do you understand what it is doing?

**Comment by rn** [comment]
the files showed up because of github ui issues. they are from a PR which was merged after I create this. I rebased to master and force pushed

**Comment by deitch** [comment]
But... but... but github is perfect! I can run everything on it! Everything! And it never has any issues!! 😂

**Pull request merged**
