### PR TITLE
Kernel config update

### LINKED ISSUE #1848: Hyper-V socket crash with 4.11 kernels
PR https://github.com/linuxkit/linuxkit/pull/1844 updated the experimental kernel patches for the 4.11.1 kernel to the latest from https://github.com/dcui/linux/commits/decui/hv_sock/v4.11/20170511 which fixed an initial issue. However running longer stress tests with more concurrency cause a kernel crash on Windows 10 Pro RS1 build 14393.1066 and a hang of the Linux VM on Windows 10 Pro Insider fast ring build 16193.1001. It's unclear if the Windows build is significant as the machines are different specs.

To reproduce:
- Building a LinuxKit image with the stress test tools from https://github.com/linuxkit/virtsock by typing `make linuxkit`.
- Copy `hvtest-efi.iso` and `./build/virtsock_stress.exe` to your Windows machine
- Copy [`LinuxKIt.ps1`](https://github.com/linuxkit/linuxkit/blob/master/scripts/LinuxKit.ps1) to your Windows machine
On the windows machine:
- Make sure the Hyper-V socket UUIDs are registered using [this script](https://github.com/linuxkit/virtsock/blob/master/scripts/setup.ps1). This is a one time operation.
- Create a Hyper-V VM and start it from an elevated powershell:
  `.\LinuxKit.ps1 -Create -IsoFile .\hvtest-efi.iso -Memory 2048 -CPUs 2; .\LinuxKit.ps1 -start`
- Connect to the serial console: `putty -serial  \\.\pipe\LinuxKitVM-com1`
- In the LinuxKitVM start the server process: `virtsock_stress -v 1 -s`
- In Powershell, get the ID for the VM: `(Get-VM LinuxKitVM).Id`
- In a powershell on the host start the client:
  `virtsock_stress.exe -v 1 -c <VM ID> -i 1000000 -p 10`

The last command starts the client which will use 10 threads to connect to the server with a connection per thread. Up to 1000000 connections will be made an random amount of data is transferred over each connection and echoed back by the server. The client is also comparing checksums of the data sent and received.

On the Insider build 16193.1001 this hangs after some 10000 connections have been made and the client eventually gets a receive timeout. The server in the Linux VM is locked (can't `ctrl-c`) until we exit the client.

On the RS1 build (14393.1066) there is a kernel crash after about 13000 connections:
```
[  317.821101] ------------[ cut here ]------------
[  317.895414] WARNING: CPU: 1 PID: 543 at lib/list_debug.c:56 __list_del_entry_                                                     valid+0x51/0x84
[  317.922774] list_del corruption. next->prev should be ffff9d87b0197078, but w                                                     as ffff9d87b6ce3178
[  317.945516] Modules linked in:
[  317.951779] CPU: 1 PID: 543 Comm: virtsock_stress Not tainted 4.11.1-linuxkit                                                      #1
[  317.961773] Hardware name: Microsoft Corporation Virtual Machine/Virtual Mach                                                     ine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
[  317.961773] Call Trace:
[  317.961773]  ? dump_stack+0x5a/0x6f
[  317.961773]  ? __warn+0xd2/0xeb
[  317.961773]  ? warn_slowpath_fmt+0x5a/0x76
[  317.961773]  ? __list_del_entry_valid+0x51/0x84
[  317.961773]  ? __list_del_entry+0x9/0x1d
[  317.961773]  ? vsock_accept+0x16b/0x27e
[  317.961773]  ? add_wait_queue+0x3a/0x3a
[  317.961773]  ? SYSC_accept4+0x10b/0x1b9
[  317.961773]  ? SyS_futex+0xd1/0x158
[  317.961773]  ? entry_SYSCALL_64_fastpath+0x1a/0xa9
[  318.117012] ---[ end trace 66affefa1d1dbd3d ]---
[  318.132328] BUG: unable to handle kernel paging request at ffffb1b187be1004
[  318.148371] IP: hvs_stream_has_data+0x22/0x4f
[  318.158456] PGD 7f0ae067
[  318.158456] PUD 7f0af067
[  318.169820] PMD 77507067
[  318.169820] PTE 0
[  318.179915]
[  318.189999] Oops: 0000 [#1] SMP
[  318.200275] Modules linked in:
[  318.210337] CPU: 1 PID: 537 Comm: virtsock_stress Tainted: G        W       4                                                     .11.1-linuxkit #1
[  318.220461] Hardware name: Microsoft Corporation Virtual Machine/Virtual Mach                                                     ine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
[  318.250740] task: ffff9d87b75ba280 task.stack: ffffb1b182e6c000
[  318.270897] RIP: 0010:hvs_stream_has_data+0x22/0x4f
[  318.281027] RSP: 0018:ffffb1b182e6fd30 EFLAGS: 00010246
[  318.291121] RAX: 0000000000000001 RBX: ffff9d87b0196d40 RCX: ffff9d87b75ba280
[  318.311320] RDX: ffffb1b187be1000 RSI: 0000000000000246 RDI: ffff9d87b0196d40
[  318.353684] RBP: 0000000000000001 R08: ffff9d87b0230400 R09: ffff9d87bd550280
[  318.373919] R10: 0000000000000000 R11: ffff9d87b75ba280 R12: 7fffffffffffffff
[  318.404151] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000004
[  318.424381] FS:  00007f3b58ac5eb0(0000) GS:ffff9d87b7a40000(0000) knlGS:00000                                                     00000000000
[  318.444527] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  318.460023] CR2: ffffb1b187be1004 CR3: 0000000070061000 CR4: 00000000003406a0
[  318.474838] Call Trace:
[  318.485127]  ? vsock_stream_recvmsg+0x16f/0x34a
[  318.495222]  ? core_sys_select+0x179/0x220
[  318.505296]  ? core_sys_select+0x1ce/0x220
[  318.515370]  ? add_wait_queue+0x3a/0x3a
[  318.535562]  ? sock_read_iter+0x80/0xab
[  318.545663]  ? __vfs_read+0x8c/0xc4
[  318.555728]  ? vfs_read+0x94/0xb0
[  318.565799]  ? SyS_read+0x5c/0x9d
[  318.565799]  ? entry_SYSCALL_64_fastpath+0x1a/0xa9
[  318.585973] Code: c3 0f 1f 44 00 00 31 c0 c3 0f 1f 44 00 00 48 8b 97 20 04 00                                                      00 b8 01 00 00 00 83 7a 38 00 75 37 4c 8b 42 28 49 8b 90 20 01 00 00 <8b> 72 04                                                      8b 0a 41 8b 90 30 01 00 00 41 89 c9 01 ca 41 29 f1 29
[  318.636432] RIP: hvs_stream_has_data+0x22/0x4f RSP: ffffb1b182e6fd30
[  318.656575] CR2: ffffb1b187be1004
[  318.656575] ---[ end trace 66affefa1d1dbd3e ]---
[  318.717071] Kernel panic - not syncing: Fatal exception
[  318.727136] Kernel Offset: 0x19000000 from 0xffffffff81000000 (relocation ran                                                     ge: 0xffffffff80000000-0xffffffffbfffffff)
[  318.727136] ---[ end Kernel panic - not syncing: Fatal exception
```

I've seen both the kernel crash as well as the hang on two successive runs (with restarting the VM in between, of course). So it seems easy to reproduce

### LINKED ISSUE #2146: Enable additional kernel configs
Netx round of kernel config add the following to the kernel config
- `CONFIG_EFI_VARS=y`: Exposes EFI variables to the host. Might be useful for Hyper-V
- Network device drivers:
  - `CONFIG_I40E=m` and `CONFIG_I40EVF=m`: Intel 40G NICs See #2139
  - `CONFIG_MLX4_EN=m`, `CONFIG_MLX4_CORE=m`, `CONFIG_MLX5_CORE=m`: Mellanox 40G NICs
  - `CONFIG_BNX2=m`, `CONFIG_BNX2X=m`, `CONFIG_BNX2X_SRIOV=y`, `CONFIG_CNIC=m`, `CONFIG_BNXT=m`, `CONFIG_BNXT_SRIOV=y`: Various 1/10/40G Broadcom drivers
- `CONFIG_ACPI_NFIT=y`, `CONFIG_LIBNVDIMM=y`, `CONFIG_FS_DAX=y`, `CONFIG_DEV_DAX_PMEM=y`, `CONFIG_BLK_DEV_PMEM=y`: NVDIMM support, use on some hypervisors for guest/host comms
- `CONFIG_VIRTUALIZATION=y`, `CONFIG_KVM=m`, `CONFIG_KVM_INTEL=m`, `CONFIG_VHOST_NET=m`, `CONFIG_VHOST_SCSI=m`, `CONFIG_VHOST_VSOCK=m`, `CONFIG_VHOST=m`: Enable KVM as module for running on bare metal

### PR DESCRIPTION
**Pull request by rn**
- Updated the 4.11 patches to the latest from https://github.com/dcui/linux/commits/decui/hv_sock/v4.11/20170511-debug-0628-with-signed-off-by-of-dexuan-fixed
- Updated 4.9.x and 4.11.x kernel configs to include additional network device drivers and KVM as modules as well as enabling some additional EFI options (e.g. expose EFI variables in sysfs)
- Added kernel config and patches to enable LCOW (based on https://github.com/Microsoft/opengcs/tree/master/kernelconfig/4.11). The kernel config options are a bit of a guessing games as to which ones are actually required.

resolves #2146
 
The updates to the 4.11 kernel also seem to fix the issue we have seen with Hyper-V socket as I've run more than 100k connections with a stress tests on Windows 10 Pro builds 16237.1001 and 14393.1358 without kernel crash, so this may resolves #1848

### CODE REVIEW

**Comment by justincormack** [comment]
Can't see anything unreasonable...

**Comment by rn** [comment]
removed the WIP and kicked off a kernel build (after rebasing). The 4.11 kernel config test still passed locally

**Comment by tych0** [comment]
Yep, LGTM too.

**Comment by dcui** [comment]
Thank you Rolf for the help all the way! 
Please feel free to contact me if you find any new issue. I'm ready to debug it. 
Currently I'm working on how to upstream the patches. I'll keep you updated once I have any progress.

**Pull request merged**
