### PR TITLE
check-kernel-config: check for STRICT_MODULE_RWX too

### PR DESCRIPTION
**Pull request by tych0**
This is what CONFIG_DEBUG_SET_MODULE_RONX was renamed to; since we want
that one, presumably we want this one too.

Signed-off-by: Tycho Andersen <tycho@docker.com>

### CODE REVIEW

**Comment by tych0** [comment]
Sure, I can't push to the hub though so I didn't do any of that. If you want to set +w, then I can.

**Comment by rn** [comment]
do you have signing power? I've added you to the test-kernel-config repo on hub

**Comment by tych0** [comment]
No, I don't think I have signing power either (i.e. my keys haven't been whitelisted, if that's what you mean)

**Comment by riyazdf** [comment]
code LGTM.  Pushed and signed `linuxkit/test-kernel-config:9f0b6b012ad86f22d6ad488cdd870a37fa70bc75` for yml usage.

**Comment by tych0** [comment]
Thanks, I just pushed another patch to look at that hash.

**Comment by rn** [comment]
hit rebuild

**Comment by justincormack** [comment]
It went green...

**Pull request merged**
