### PR TITLE
Update Moby tool

### PR DESCRIPTION
**Pull request by justincormack**
- containerd 1.0 vendoring
- yaml omitempty
- null pointer dereference

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

actic_noaa_walrus_formatted

### CODE REVIEW

**Comment by ijc** [comment]
Might be worth propagating the relevant changes from `src/cmd/linuxkit/vendor/github.com/moby/tool/vendor.conf` into `src/cmd/linuxkit/vendor.conf`.

**Comment by justincormack** [comment]
Ah yes

**Comment by justincormack** [comment]
Added commit to bring the two into line

**Comment by justincormack** [comment]
ok, all match except x/sys which is newer here and needs to be, will update moby/tool to match later.

**Pull request merged**
