### PR TITLE
Update to containerd v1.0.0

### PR DESCRIPTION
**Pull request by ijc**
Info in https://github.com/containerd/containerd/releases/tag/v1.0.0

Mechanical update.

### CODE REVIEW

**Comment by ijc** [comment]
```
[+ 41m 45s] [FAIL    ] linuxkit.packages.containerd 211.88s
...
[+ 58m 29s] [FAIL    ] linuxkit.packages.getty-containerd 106.29s
```

I'll investigate.

**Comment by ijc** [comment]
Seems like PEBCAK during the update:
```diff
@@ -4,9 +4,9 @@ kernel:
   cmdline: "console=ttyS0 page_poison=1"
 init:
   - linuxkit/vpnkit-expose-port:15c56c57ac9a7adeec20b34f36f2bc165c347679 # install vpnkit-expose-port and vpnkit-iptables-wrapper on host
-  - linuxkit/init:7357177a8be310e40fef7424305a72c198e857c4
+  - linuxkit/init:19ab525233763e1740cd3b9d60cd17141d316776
   - linuxkit/runc:1b0741d07949c0acc444cd6a04ee7f833443579d
-  - linuxkit/containerd:737e4b004e28510d2dd504942b80fa5ffa409315
+  - linuxkit/init:19ab525233763e1740cd3b9d60cd17141d316776
   - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
 onboot:
   # support metadata for optional config in /var/config
```

That linuxkit/containerd update is not likely to be correct!

**Comment by ijc** [comment]
Done properly this time. Surprising the test results weren't more catastrophic. I guess many of the tests are `runc` only!

**Comment by justincormack** [comment]
Yeah quite a few tests are runc only, we should probably have more that
stress containerd

**Pull request merged**
