### PR TITLE
[WIP] Contain

### PR DESCRIPTION
**Pull request by w9n**
**- What I did**
Contain is a program to easily execute commands in predefined containers on runtime on containerd. I would like to use the moby service config for container definition at some point.

It can be used as a more sound implementation of a containerized mounter ( linuxkit/kubernetes#16 ) or to basically start any predefined command/container pair.

**- How I did it**
Contain checks each provided container definition in order if its X command parameters are equal to the first X Args of contain and then starts the container with the full args.

**- How to verify it**
~There is a test provided that starts a containerd process, which sometimes weirdly doesnt properly shutdown.~ It seems hard to gracefully shutdown containerd so i just remove the socket file after a SIGKILL

~The test currently fails with:~  The test environment cant be overlay on overlay.
```
failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/10/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/10/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/9/fs]}: invalid argument: unknown
```
~Which I dont know why...~ Feedback is much appreciated. If you want to merge this i would move the dependencies into a build container.
**- Description for the changelog**

Introduce contain

**- A picture of a cute animal (not mandatory but encouraged)**
contain

### CODE REVIEW

**Comment by deitch** [comment]
> Contain is a program to easily execute predefined commands in predefined containers

I am confused (but perhaps missed an earlier conversation around this?). Doesn't every `service` and `onboot` already have a `command` which executes it? And if I wanted a different command, could I not just reuse the image and change the `command: ["something"]`?

A sample use case might help, e.g. "I want to be able to do X, here is how I do it, here is how the config changes, etc."

**Comment by w9n** [comment]
I forgot to mention that its for starting container on runtime. so basically the kubernetes use case is `ctn mount ...`, `ctn mount -t nfs ...`, `ctn mount -t glusterfs ...` executes the mount command in different containers, which either already exist or get pulled and created by the contain provided config. I would also like to use it as some kind of docker-compose replacement for desktop apps.

**Comment by deitch** [comment]
These commands are meant to be run to do a command _other_ than the listed `command` for the container, e.g. an init process (like `ctn mount`) or parallel (like a sidecar)? Who runs `ctn mount`?

**Comment by w9n** [comment]
The kubelet invokes ` ctn mount` from the `--experimental-mounter-path` parameter. You can have a look at linuxkit/linuxkit#2683 and linuxkit/kubernetes#16

**Comment by deitch** [comment]
> The kubelet invokes ctn mount from the --experimental-mounter-path parameter. You can have a look at linuxkit/linuxkit#2683 and linuxkit/kubernetes#16

Ah, wasn't as involved with that one (wanted to be, but head down on building and manipulating filesystems from within `moby/tool`), so I probably am missing the use case. Will watch this but refrain until the people involved there @ijc and @justincormack comment.

**Comment by w9n** [comment]
I developed this into the direction of a containerd cli and dont think it fits in as a linuxkit pkg.

**Pull request closed without merging**
