### PR TITLE
v0.2 release

### PR DESCRIPTION
**Pull request by rn**
- Update all packages/tools/tests to latest linuxkit/alpine
- everything in `./pkg` was pushed with `linuxkit pkg push -release=v0.2`
- Update YAMLs
- `moby/tool` was updated to use the new version packages for image builds and vendored back here
- Finally, version bump in top level make file

All packages have been  build and pushed

Once merged, I'll tag the commit and extract the artefacts and create a release page.

slime-fish

### CODE REVIEW

**Comment by rn** [comment]
Severl tests failed because, for some reason some pacakges were not pushed (which is weird since I did a `make push` in `./pkg`. I've repushed the packages but `linuxkit.build.formats.vmdk` is still failing on *linux* but works fine on macOS (with hyperkit)

**Comment by ijc** [comment]
I don't suppose the original push is still in your terminal scrool? I thought I had been experiencing this for a while after I first added `linuxkit pkg push` but I never managed to reproduce while I was looking for it, I even used to routinely do these updates under `script(1)` but never saw it while doing so...

**Comment by rn** [comment]
@ijc I had this on `linuxkit/vpnkit` and it fails. I re-did the make which then didn't re-push the package (should have force pushed this one):
```
Successfully signed docker.io/linuxkit/ip:v0.2-amd64
Pushing linuxkit/ip:v0.2-amd64 to manifest linuxkit/ip:v0.2
time="2018-01-25T16:15:31Z" level=warning msg="Couldn't find or access image reference \"linuxkit/ip:v0.2-arm64\". Skipping image."
Digest: sha256:144bd95e5b9f3b18d3efa53854c0033b22d776abf57c9854831c2c4919c0323e 433
spawn notary -s https://notary.docker.io -d /Users/rneugeba/.docker/trust addhash -p docker.io/linuxkit/ip v0.2 433 --sha256 144bd95e5b9f3b18d3efa53854c0033b22d776abf57c9854831c2c4919c0323e -r targets/releases
Addition of target "v0.2" by sha256 hash to repository "docker.io/linuxkit/ip" staged for next publish.
Auto-publishing changes to docker.io/linuxkit/ip

* fatal: client is offline
expect: spawn id exp6 not open
    while executing
"expect {
    timeout {
        puts "Expected password prompt"
        exec kill -9 $pid
        exit 1
    }
    "password: " {
```
The `linuxkit/ip` package is a mystery as there was no build failure. But, unfortunately, it's not in my scroll anymore

**Comment by rn** [comment]
Looks like the vmdk failure was a bug in the `mkimage-vmdk` and `mkimage-dynamic-vhd`. I added a fix but need to do the detour via `moby/tool` and vendoring. I'll add the commits to the top of the queue so that the commit hashes for the already built packages are not out of whack.

**Comment by rn** [comment]
Force pushed an update with updated `mkimage-vmdk` and `mkimage-dynamic-vhd` packages and revendored moby tool.

This should fix the ci failures

**Pull request merged**
