### PR TITLE
make init sequential

### PR DESCRIPTION
**Pull request by justincormack**
carry #2210 

frog

### CODE REVIEW

**Comment by rn** [comment]
What's the rational behind removing the usermode helper? We need it for 4.11 kernels  which is configured to use it to shell out to other commands.

**Comment by justincormack** [comment]
Oh, sorry, I was confusing it with something else

**Comment by justincormack** [comment]
removed that commit

**Comment by justincormack** [comment]
Hmm, trying a rebuild; the log didnt make it clear what in the `containerd-getty` test failed, could not actually see an error...

**Comment by justincormack** [comment]
Ah Redis output message has changed slightly in 4.0...

**Pull request merged**
