### PR TITLE
Allowing re-using existing machines on packet.net

### PR DESCRIPTION
**Pull request by rn**
Normally `linuxkit run` provisions a new server (and deletes it when done). We already had the `-keep` option to keep the machine around. This PR adds the `-device` option which allows us to reboot an existing machine and boot it with a new iPXE config.

This requires some patches to the packet.net bindings which currently are in my fork, but I'll try to upstream them.

muffin

### CODE REVIEW

**Comment by justincormack** [comment]
Shall we wait until this gets merged upstream?

**Comment by rn** [comment]
I don't know how long that'll take. If you are ok with it, let's merge this now and I'll revendor once the upstream PR is merged

**Comment by justincormack** [comment]
ok

**Comment by justincormack** [comment]
this got merged upstream

**Pull request merged**
