### PR TITLE
Fix bug: when request to build multiple arches, if one already found, it skips the others

### PR DESCRIPTION
**Pull request by giggsoff**
We cannot build for another arch after building for one arch because of setting `skipBuild` to true if one arch found. In other words `linuxkit pkg build --platforms linux/riscv64,linux/amd64 ...` after `linuxkit pkg build --platforms linux/amd64 ...` will not build for linux/riscv64  which is not expected.

In general when we check for available images and able to found part of platforms we do not want to rebuild all of them. So this PR includes `platformsToBuild` slice which we fill with platforms we want to build for.

### CODE REVIEW

**Comment by deitch** [comment]
Can you describe the problem you are trying to fix in a little more detail?

First of all, these are not bootable images (`lkt build`) but package images (`lkt pkg build`)?

Second, what is the issue? When we push an image, e.g. linux/amd64, it creates the image, manifest and multi-arch index (with one arch in it). The manifest builder looks for all known platforms, tries to find the manifests for them, but ignores any missing ones because that is the behaviour we want: try for all, but accept whatever we find (missing is not an error).

If we later push another one, e.g. `linux/arm64`, we add that manifest, and regenerate the index, which now contains pointers to 2 manifests (and cannot find 10-15 more, which are reported but are not errors).

So what is the issue?

**Comment by giggsoff** [comment]
The main issue is here: https://github.com/linuxkit/linuxkit/blob/86cc42bf79fde5bba63519313da337144841b647/src/cmd/linuxkit/pkglib/build.go#L239

If we found image for one platform, we skip build.

But I think it would be nice to refactor the code and not build it for all platforms if any of them were found and pulled from the registry. So I implemented that logic here.

**Comment by deitch** [comment]
> If we found image for one platform, we skip build.

What is the current behaviour, and to what we want to change it? The issue description talks about issues pushing, but the comment above discusses builds.

It sounds like you are saying, if we asked to build for 3 platforms, and managed to find it for 1 of them (local cache or registry), then we skip for all 3. Is that what you are addressing? That would, indeed, be a bug, but is not what is listed in the description and title, and is the opposite of what you wrote:

> not build for all platforms if any of them were found and pulled from the registry.

Do you mind clarifying please?

**Comment by giggsoff** [comment]
Sorry for inconvenience. I tried to describe the issue with push which actually include the build internally. But you are right, it was not clear, so I edit descriptions.

**Comment by deitch** [comment]
No problem. On the basis of your description, I changed the title.

**Review by deitch — APPROVED** [review]

**Pull request merged**
