### PR TITLE
Update kernels to 5.1.15/4.19.56/4.14.131/4.9.184

### LINKED ISSUE #3092: Enable Wireless extensions in base kernel configs
As per @rn and the [issue logged on docker/for-mac](https://github.com/docker/for-mac/issues/3050) I'm opening this upstream.

Would it be possible to enable the following in linuxkit kernels:
CONFIG_WIRELESS=y
CONFIG_WLAN=y

To enable the building of wireless modules for proprietary linuxkit images, such as those used in Docker-CE for Mac|Windows/Docker Desktop.

Specifically, @rn would like to know the implications of doing so, and whether it can be done safely.

### PR DESCRIPTION
**Pull request by rn**
This skips 5.1.13/4.19.54/4.14.130/4.9.183 as there is only one patch to the next version.

Also enable CONFIG_WIRELESS/CONFIG_WLAN for x86/arm64 kernels. resolves #3092

image

### CODE REVIEW

**Comment by rn** [comment]
Hmm, the containerd test failed:
```
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334395809Z: --- FAIL: TestOverlay (0.00s)
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334440728Z:     --- FAIL: TestOverlay/Basic (0.32s)
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334473970Z:         testsuite.go:253: failure reason: device or resource busy
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334518234Z:         helpers_unix.go:32: unmount /var/lib/tmp/snapshot-suite-Overlay-768495960/work/nextlayer
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334560615Z:         helpers_unix.go:32: unmount /var/lib/tmp/snapshot-suite-Overlay-768495960/work/preparing
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334596965Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334633278Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334674996Z:         helpers.go:65: -rw-------      65536 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/metadata.db [ "\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\xed\xda\f\xed\x02\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00\x00\x00\x00\x00" ...]
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334724058Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334780237Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334825864Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1/fs
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334920320Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1/fs/a
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.334960261Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1/fs/a/b
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335011472Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1/fs/a/b/c
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335074508Z:         helpers.go:65: -rwxrwxrwx          4 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1/fs/foo [ "foo\n" ...]
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335110136Z:         helpers.go:67: drwx--x--x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/1/work
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335149671Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335195583Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/fs
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335241876Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/fs/a
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335285320Z:         helpers.go:67: Dc---------          0 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/fs/a/b
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335331289Z:         helpers.go:65: -rwxrwxrwx          4 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/fs/bar [ "bar\n" ...]
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335368013Z:         helpers.go:65: -rwxrwxrwx          4 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/fs/foo [ "bar\n" ...]
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335405888Z:         helpers.go:67: drwx--x--x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/work
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335443074Z:         helpers.go:67: d---------       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/2/work/work
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335478851Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/3
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335522997Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/root/snapshots/3/fs
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335562354Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/work
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335600020Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/work/nextlayer
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335635798Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/work/nextnextlayer
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335676787Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-768495960/work/preparing
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335722980Z: FAIL
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335772740Z: FAIL	github.com/containerd/containerd/snapshots/overlay	11.689s
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335818310Z: containerd test suite FAILED
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335856002Z: make: *** [Makefile:155: root-test] Error 1
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335894355Z: [  155.598427] sd 0:0:0:0: [sda] Synchronizing SCSI cache
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335939165Z: [  155.603837] sd 0:0:0:0: [sda] Stopping disk
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.335982182Z: [  155.609025] ACPI: Preparing to enter system sleep state S5
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.336025419Z: [  155.614473] reboot: Power down
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.336060567Z: + clean_up
[+ 45m 50s] [STDERR  ] 2019-07-03T08:19:26.336104981Z: + rm -rf containerd-cmdline containerd-initrd.img containerd-kernel containerd-state
[+ 45m 50s] [FAIL    ] linuxkit.packages.containerd 239.09s
```

This was still using the older version `containerd`. I rebased to master and forcepushed

**Comment by rn** [comment]
Same failure with latest containerd:
```
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474310810Z: ok  	github.com/containerd/containerd/archive	0.208s
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474323771Z: ok  	github.com/containerd/containerd/metadata	20.300s
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474343687Z: ok  	github.com/containerd/containerd/mount	0.345s
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474356575Z: ok  	github.com/containerd/containerd/snapshots/btrfs	30.088s
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474369190Z: ok  	github.com/containerd/containerd/snapshots/native	10.363s
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474382189Z: --- FAIL: TestOverlay (0.00s)
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474395478Z:     --- FAIL: TestOverlay/Basic (0.30s)
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474408833Z:         testsuite.go:253: failure reason: device or resource busy
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474426837Z:         helpers_unix.go:32: unmount /var/lib/tmp/snapshot-suite-Overlay-391257545/work/nextlayer
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474439714Z:         helpers_unix.go:32: unmount /var/lib/tmp/snapshot-suite-Overlay-391257545/work/preparing
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474452495Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474465674Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474483527Z:         helpers.go:65: -rw-------      65536 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/metadata.db [ "\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\xed\xda\f\xed\x02\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\r\x00\x00\x00\x00\x00\x00\x00" ...]
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474502336Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474516170Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474529104Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1/fs
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474541854Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1/fs/a
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474554751Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1/fs/a/b
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474567599Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1/fs/a/b/c
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474587866Z:         helpers.go:65: -rwxrwxrwx          4 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1/fs/foo [ "foo\n" ...]
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474602035Z:         helpers.go:67: drwx--x--x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/1/work
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474615234Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474627814Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/fs
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474640840Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/fs/a
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474653746Z:         helpers.go:67: Dc---------          0 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/fs/a/b
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474672239Z:         helpers.go:65: -rwxrwxrwx          4 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/fs/bar [ "bar\n" ...]
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474686135Z:         helpers.go:65: -rwxrwxrwx          4 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/fs/foo [ "bar\n" ...]
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474699521Z:         helpers.go:67: drwx--x--x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/work
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474712185Z:         helpers.go:67: d---------       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/2/work/work
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474725102Z:         helpers.go:67: drwx------       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/3
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474738107Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/root/snapshots/3/fs
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474753847Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/work
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474766521Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/work/nextlayer
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474784007Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/work/nextnextlayer
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474796958Z:         helpers.go:67: drwxr-xr-x       4096 /var/lib/tmp/snapshot-suite-Overlay-391257545/work/preparing
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474810035Z: FAIL
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474826769Z: FAIL	github.com/containerd/containerd/snapshots/overlay	11.999s
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474839630Z: containerd test suite FAILED
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474852540Z: make: *** [Makefile:155: root-test] Error 1
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474872713Z: [  161.854650] sd 0:0:0:0: [sda] Synchronizing SCSI cache
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474885521Z: [  161.860100] sd 0:0:0:0: [sda] Stopping disk
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474903160Z: [  161.865319] ACPI: Preparing to enter system sleep state S5
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474915726Z: [  161.870829] reboot: Power down
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474928255Z: + clean_up
[+ 44m 32s] [STDERR  ] 2019-07-03T20:44:20.474941570Z: + rm -rf containerd-cmdline containerd-initrd.img containerd-kernel containerd-state
[+ 44m 32s] [FAIL    ] linuxkit.packages.containerd 241.77s
```

Haven't checked but I suspect some overlay changes between 4.19.52 and 4.19.56.

@justincormack any idea?

**Comment by rn** [comment]
4.19.55 passes and 4.19.56 fails with the `containerd` overlayfs test. There were a bunch of changes:
```
0319ef1d40ff ("ovl: fix bogus -Wmaybe-unitialized warning")  (2019-06-25 11:35:52 +0800) <Arnd Bergmann (N)>
639e8c2f0910 ("ovl: don't fail with disconnected lower NFS")  (2019-06-25 11:35:52 +0800) <Miklos Szeredi (N)>
f1c5aa5eda08 ("ovl: detect overlapping layers")  (2019-06-25 11:35:52 +0800) <Amir Goldstein (N)>
a00f405e133f ("ovl: make i_ino consistent with st_ino in more cases")  (2019-06-25 11:35:52 +0800) <Amir Goldstein (N)>
d6623379d895 ("ovl: fix wrong flags check in FS_IOC_FS[SG]ETXATTR ioctls")  (2019-06-25 11:35:52 +0800) <Amir Goldstein (N)>
3cb5d7fa8f7d ("ovl: support the FS_IOC_FS[SG]ETXATTR ioctls")  (2019-06-25 11:35:52 +0800) <Amir Goldstein (N)>
```

@crosbymichael should I file an issue on `containerd` or is thi something you are aware of already?

**Comment by rn** [comment]
@justincormack new kernels are out but no changes to overlayfs. I don't have good viz if this is an issue with the kernel or containerd or the containerd test. One option would be in the short term to disable the containerd test...thoughts?

**Comment by crosbymichael** [comment]
Ya, let create an issue for this in containerd.

**Comment by rn** [comment]
containerd issue: https://github.com/containerd/containerd/issues/3405

**Comment by rn** [comment]
force pushed a rebase now that the containerd bump containing the fix to the tests has been merged (https://github.com/linuxkit/linuxkit/pull/3403)

**Pull request merged**
