### PR TITLE
Removed unused vendoring

### PR DESCRIPTION
**Pull request by justincormack**
Not required since #2025

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by rn** [comment]
I noticed we also vendor infrakit, but couldn't find why?

**Comment by justincormack** [comment]
Hmm, I noticed this when making another vendoring update and `vndr` removed this, but it didnt complain about infrakit...

**Comment by justincormack** [comment]
Oh, it was just the README etc, removed as well

**Comment by rn** [comment]
infrakit is still in `vendor.conf`. should be removed

**Comment by justincormack** [comment]
removed

**Pull request merged**
