### PR TITLE
Add s390x support to binfmt_misc

### PR DESCRIPTION
**Pull request by johanneswuerbach**
**- What I did**

Register s390x with binfmt_misc and add the static qemu s390x binary. Docker already provides
official images for s309x (but no official support).

https://github.com/docker-library/official-images#architectures-other-than-amd64

**- How I did it**

While the process wasn't really documented before, I added some details around adding an architecture.

**- How to verify it**

```
docker build -t binfmt ./pkg/binfmt
docker run --rm -it --privileged binfmt
docker run --rm -it s390x/debian:stretch uname -a
Linux 989516accfdd 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 s390x GNU/Linux
```

**- Description for the changelog**

Add support for cross-building s390x images 

**- A picture of a cute animal (not mandatory but encouraged)**

image

What would be the process to have this eventually supported in docker for mac besides bumping the image here https://github.com/linuxkit/linuxkit/blob/master/examples/docker-for-mac.yml#L20?

### CODE REVIEW

**Comment by deitch** [comment]
I do like having this, thank you @johanneswuerbach 

There were some issues with `qemu-s390x-static` not working correctly. I came across them most recently when I was working to get calico cross-platform, but I cannot recall what they were at the moment. It has been a bit of time, but I found my own (unfortunately cryptic) comment [here](https://github.com/projectcalico/typha/blob/0bd59769525663f6e22866d9ba987d1c7ad1ecb5/Makefile#L75), but cannot recall what the issues were. Something about binaries giving a strange SIGSEGV due to qemu emulation issues? The exclusion exists in every calico project, I remember having to exclude it, but cannot recall the details now.

I do recall that we worked with @alicefr on it, as well as @mkumatag . Does either of you recall what the qemu s390x issues were?

**Comment by justincormack** [comment]
The original reason for not adding this was that IBM had some legal issues with s390 emulation, not sure if this is really an issue or not any more.

**Comment by deitch** [comment]
> IBM had some legal issues with s390 emulation,

Then we may have a technical issue and a legal issue. Hopefully Alice or Manjunath can shed light on the technical ones. Do you know who can answer the legal ones?

**Comment by thaJeztah** [comment]
> Do you know who can answer the legal ones?

Perhaps @estesp ?

**Comment by mkumatag** [comment]
@cwsolee do you know anyone who can help us here?

**Comment by cwsolee** [comment]
I'm been away, Alice might have more recent news on whether they can work on it.

**Comment by alicefr** [comment]
hi everybody! Unfortunately,  the legal issues are still there. User emulation as fas as I know should work fine, it is the system emulation that have issues.

**Comment by justincormack** [comment]
This is only for user emulation.

**Comment by rn** [comment]
@alicefr any comment?

**Comment by rn** [comment]
@alicefr thanks for confirming.

@johanneswuerbach Could you add another commit to update `pkg/binfmt` in all YAML files with the output of `linuxkit pkg show-tag pkg/binfmt`? `./scripts/update-component-sha.sh` will help with that.

**Comment by johanneswuerbach** [comment]
@rn done, is that correct?

**Comment by rn** [comment]
yes, thank you. The CI will fail, but will rebuild/push/sign the binfmt package this evening and rekick the CI

**Pull request merged**
