### PR TITLE
Add Network Limitations section

### PR DESCRIPTION
**Pull request by rogaha**
Signed-off-by: Roberto Gandolfo Hashioka <roberto.hashioka@docker.com>

Closes https://github.com/linuxkit/linuxkit/issues/1719

### CODE REVIEW

**Comment by justincormack** [comment]
Can you follow Gordon's instructions please...

**Comment by rogaha** [comment]
@justincormack I've done it. The `commit` is signed.

**Comment by rneugeba** [comment]
I don't think we need a separate section. It should just be paragraph at the end of the Networking section. And it's actually not a limitation of VPNKit. We use it because the macOS VMNet framework requires root priviledge

**Comment by rogaha** [comment]
@rneugeba I think it's a `networking` limitation, do you have a suggestion that better explain this limitation? Having this in a separate `section` will facilitate its visibility avoiding `users` failed attempts. 

@justincormack I've fixed the weird `commit` message.

**Comment by rogaha** [comment]
Issue created: https://github.com/linuxkit/linuxkit/issues/1719

**Comment by rneugeba** [comment]
closing in favour of #1724. Thanks for reporting the need for additional clarification in the docs

**Comment by rogaha** [comment]
👍  Thanks @rneugeba!

**Pull request closed without merging**
