### PR TITLE
Remove bashism in script

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**- What I did**
Removed a bashism from [update-component-sha.sh](./scripts/update-component-sha.sh) per https://github.com/linuxkit/linuxkit/issues/2284#issuecomment-317685142 

**- How I did it**
Removed the duplicate word `function`

**- How to verify it**
Run it in different modes.

**- Description for the changelog**

Remove bashism from script.

**- A picture of a cute animal (not mandatory but encouraged)**
ostrich

### CODE REVIEW

**Comment by deitch** [comment]
> I applied this locally and checkbashisms (from the devscripts package on Debian and I presume Ubuntu) was happy with the result.

Me too, although I just did `brew install checkbashisms` :-)

I also kicked off an ubuntu shell using `docker run -it --rm -v $PWD:/src ubuntu:16.04 sh` and then `cd /src` and ran the script. Results were identical.

Sure, no need to wait for CI. I will flag some others to take a look.

**Comment by deitch** [comment]
Heh, I think I flagged almost everyone. Just one more to jump in please.

**Comment by rn** [comment]
One review from a maintainer should be enough

**Comment by rn** [comment]
please don't merge before CI finishes (even if the change is not tested). Sets a bad precedence and the CI is not stopped by it anyway

**Comment by deitch** [comment]
> please don't merge before CI finishes (even if the change is not tested

I don't usually, but @ijc said:

> Probably not much point waiting for CI on this change. Perhaps go ahead and merge if a third maintainer (after you and I) approves?

**Comment by deitch** [comment]
I trust that you guys who have been in this much longer know when to follow the procedures and when not to bother. :-)

**Comment by ijc** [comment]
I should have been clearer that I mean for another maintainer to approve the early merge, rather than just the normal approval of the set of changes.

**Comment by deitch** [comment]
> I mean for another maintainer to approve the early merge

Oh. Oops. :-)

I thought it was irregular, but figured if you said it was ok, then ok.

Lessons for the future then.

**Pull request merged**
