### PR TITLE
Add development report for week to 28 May 2017

### PR DESCRIPTION
**Pull request by justincormack**
Slightly late, due to holiday, sorry!

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

beachdog

### CODE REVIEW

**Comment by rneugeba** [comment]
We also enabled vulnerability scanning for all images

**Comment by justincormack** [comment]
Ah yes

**Comment by justincormack** [comment]
Hmm, doesn't seem to be all the repos

**Comment by justincormack** [comment]
In fact its not very many images at present, will look into it and mention it next time...

**Pull request merged**
