### PR TITLE
Fixes #2511 by adding latest HPE storage drivers

### LINKED ISSUE #2511: add HP devices
add
```
CONFIG_SCSI_HPSA=m
```

Also review other storage drivers.

### PR DESCRIPTION
**Pull request by bcornec**
Adds support for the HPE ProLiant storage drivers:
- SmartPQI for Gen10 ProLiant
- HPSA for Gen9 ProLiant

Signed-off-by: Bruno Cornec <bruno.corec@hpe.com>

**- What I did**
modify the kernel config files

**- How I did it**
Look for driver names

**- How to verify it**
Compare to a supported Red Hat kernel e.g.

**- Description for the changelog**
Adds support for Gen9 & Gen10 HPE ProLiant storage drivers

### CODE REVIEW

**Comment by rn** [comment]
could you also apply these to the `aarch64` kernel configuration. Even if the driver is never used there, we try to minimise the difference between the default kernel confgurations

**Comment by bcornec** [comment]
Ok done, but indeed it's irrelevant for now on HPE's side.

**Comment by rn** [comment]
Thanks but this will not pass the kernel compile because enabling the config options seems to enable other options and we check (as part of the kernel compile) that the kernel config does not change.

I've run  the config changes through the process described [here](https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md#modifying-the-kernel-config) and I get a diff for both the 4.9 and the 4.12 kernels:
```
[bcornec-master *]iMac:kit/linuxkit/kernel: git diff
diff --git a/kernel/kernel_config-4.12.x-x86_64 b/kernel/kernel_config-4.12.x-x86_64
index 93f4fd95..29761fec 100644
--- a/kernel/kernel_config-4.12.x-x86_64
+++ b/kernel/kernel_config-4.12.x-x86_64
@@ -1577,7 +1577,7 @@ CONFIG_HAVE_IDE=y
 # SCSI device support
 #
 CONFIG_SCSI_MOD=y
-# CONFIG_RAID_ATTRS is not set
+CONFIG_RAID_ATTRS=m
 CONFIG_SCSI=y
 CONFIG_SCSI_DMA=y
 # CONFIG_SCSI_NETLINK is not set
@@ -1604,7 +1604,7 @@ CONFIG_CHR_DEV_SG=y
 CONFIG_SCSI_SPI_ATTRS=y
 # CONFIG_SCSI_FC_ATTRS is not set
 CONFIG_SCSI_ISCSI_ATTRS=m
-# CONFIG_SCSI_SAS_ATTRS is not set
+CONFIG_SCSI_SAS_ATTRS=m
 # CONFIG_SCSI_SAS_LIBSAS is not set
 # CONFIG_SCSI_SRP_ATTRS is not set
 CONFIG_SCSI_LOWLEVEL=y
@@ -4086,6 +4086,7 @@ CONFIG_HAS_IOPORT_MAP=y
 CONFIG_HAS_DMA=y
 # CONFIG_DMA_NOOP_OPS is not set
 # CONFIG_DMA_VIRT_OPS is not set
+CONFIG_CHECK_SIGNATURE=y
 CONFIG_CPU_RMAP=y
 CONFIG_DQL=y
 CONFIG_GLOB=y
diff --git a/kernel/kernel_config-4.9.x-x86_64 b/kernel/kernel_config-4.9.x-x86_64
index 8be1c045..991da5ae 100644
--- a/kernel/kernel_config-4.9.x-x86_64
+++ b/kernel/kernel_config-4.9.x-x86_64
@@ -1510,7 +1510,7 @@ CONFIG_HAVE_IDE=y
 # SCSI device support
 #
 CONFIG_SCSI_MOD=y
-# CONFIG_RAID_ATTRS is not set
+CONFIG_RAID_ATTRS=m
 CONFIG_SCSI=y
 CONFIG_SCSI_DMA=y
 # CONFIG_SCSI_NETLINK is not set
@@ -1537,7 +1537,7 @@ CONFIG_CHR_DEV_SG=y
 CONFIG_SCSI_SPI_ATTRS=y
 # CONFIG_SCSI_FC_ATTRS is not set
 CONFIG_SCSI_ISCSI_ATTRS=m
-# CONFIG_SCSI_SAS_ATTRS is not set
+CONFIG_SCSI_SAS_ATTRS=m
 # CONFIG_SCSI_SAS_LIBSAS is not set
 # CONFIG_SCSI_SRP_ATTRS is not set
 CONFIG_SCSI_LOWLEVEL=y
@@ -3914,6 +3914,7 @@ CONFIG_ASSOCIATIVE_ARRAY=y
 CONFIG_HAS_IOMEM=y
 CONFIG_HAS_IOPORT_MAP=y
 CONFIG_HAS_DMA=y
+CONFIG_CHECK_SIGNATURE=y
 CONFIG_CPU_RMAP=y
 CONFIG_DQL=y
 CONFIG_GLOB=y
```

**Comment by rn** [comment]
closing in favour of #2523 which has the full kernel config update

**Pull request closed without merging**
