### PR TITLE
set the CONFIG_IP_SCTP=y to enable SCTP support in the kernel

### PR DESCRIPTION
**Pull request by razaborg**
**- What I did**

I just recompiled the linuxkit moby kernel to get a SCTP support directly from the kernel.

I personally needed it in a docker for mac usecase to get SCTP support in my containers

**- How I did it**

I edited the kernel/kernel_config file to set the **CONFIG_IP_SCTP** option to **y** and remake the kernel.

For the usecase of docker for mac (I don't know if it's the only usecase of this kernel), I replaced the */Applications/Docker.app/Contents/Resources/moby/vmlinuz64* file (on the host) by the newly compiled bzImage kernel, and restarted docker daemon.

**- How to verify it**

```
host>docker run -it debian
container>cat /proc/net/protocols 
protocol  size sockets  memory press maxhdr  slab module     cl co di ac io in de sh ss gs se re sp bi br ha uh gp em
SCTPv6    1416      1       0   no       0   yes  kernel      y  y  y  y  y  y  y  y  y  y  y  y  n  y  y  y  y  y  y
SCTP      1256      0       0   no       0   yes  kernel      y  y  y  y  y  y  y  y  y  y  y  y  n  y  y  y  y  y  y
```

**- Description for the changelog**

In the *kernel/kernel_config* file :
```
before: # CONFIG_IP_SCTP is not set
after: CONFIG_IP_SCTP=y
```

### CODE REVIEW

**Comment by razaborg** [comment]
I just amended and signed my commit

**Comment by avsm** [comment]
@razaborg this LGTM, but if you need it in a Docker for Mac release could you also open up an issue on https://github.com/docker/for-mac/issues and reference this one? This way we can update that issue whenever it actually ships in a release downstream of Docker for Mac.

**Comment by razaborg** [comment]
My usecase is the following : 
I use Docker for Mac and need to implement a telco test lab (using Diameter protocol, which uses SCTP as transport layer), so my containers needs to exchange using the SCTP transport protocol.

SCTP works perfectly in Docker over a linux host (Debian/archlinux/... base kernel), but I needed it to work in Docker for Mac, so I found out why it didn't work, and wanted to share it in this PR.
And btw, I note that in the current config, other SCTP-related options are enabled while CONFIG_IP_SCTP is disabled: 
```
CONFIG_NF_CT_PROTO_SCTP=y
CONFIG_NF_NAT_PROTO_SCTP=y
CONFIG_NETFILTER_XT_MATCH_SCTP=y
CONFIG_IP_VS_PROTO_SCTP=y
```


I manually edited the configuration file and used `make` to recompile it. That works fine for me.

**Comment by riyazdf** [comment]
@razaborg ok, thanks for detailing your use-case!  This works for me as well as @rneugeba and @justincormack.  Could you please rebase?

Also cc @rneugeba with the new kernel build goodness, we don't have the `4.9.22-1` type bumps anymore right?

**Comment by razaborg** [comment]
Well...
I switched my commit to a new branch, fetch the upstream linuxkit repo, and then rebased my own branch to the master one, and finally push the modifications to my fork git repo...
I hope I did things well, I'm not very familiar with git and big projects :/ 

And I've seen that you reorganized the kernel_config files... and my change only applied to the 4.9 version... Dunno if you want it added to other version... (?)

**Comment by razaborg** [comment]
> your branch needs a rebase. It includes a whole bunch of unrelated history.

I really don't know how to do it... I've tried a lot of things but without any success. 
So if you could give me the git commands to correct that... :(

**Comment by justincormack** [comment]
I think it might be easier to open a new PR given it is a small change. Or you can make a new branch, hard reset this one to upstream master and cherry pick the patch on top again

**Comment by justincormack** [comment]
Closing as does not apply. Probably easiest to reopen a new PR.

**Comment by justincormack** [comment]
@anandshah05 there is no built in support, you need an external kernel module.

**Comment by rn** [comment]
I'm not sure we have update the docker for mac VM yet to pick up the changes either

**Pull request closed without merging**
