### PR TITLE
pkg/ip: updating linuxkit/ip sha to image built in #2605

### PR DESCRIPTION
**Pull request by eyz**
**- What I did**
- updated sha for `linuxkit/ip` to `linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506`

**- How I did it**
- `scripts/update-component-sha.sh linuxkit/ip:0d1d6d9810812bc23652556c3cbe7d2e87655278 linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506`

**- How to verify it**
- I verified the linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506 image was pushed before this change

**- Description for the changelog**

pkg/ip: updated sha tag in examples for #2605 

**- A picture of a cute animal (not mandatory but encouraged)**
img_20171005_124047

### CODE REVIEW

**Comment by deitch** [comment]
Looks good to me. I don't know about dependencies and requirements on wireguard. this good to go, @zx2c4  ?

**Comment by eyz** [comment]
@zx2c4 good to go if CI passes, or anything else you'd like to look at?

**Comment by zx2c4** [comment]
Keeping this up to date is always a good thing and there shouldn't be WireGuard issues at all.

**Comment by deitch** [comment]
Done

**Pull request merged**
