### PR TITLE
Fix sshd

### PR DESCRIPTION
**Pull request by sprat**
**- What I did**

Fixed some problems with sshd package:
- allow access to all devices
- fix a tini warning

**- How I did it**

No devices appeared when running blkikd, had a hard time to figure out the problem
By checking the logs, I also noticed a warning with tini because it does not run with pid 0, so I fixed the problem as described in the tini warning by adding the "-s" flag

**- How to verify it**

CI

**- Description for the changelog**

SSHd: allow access to all devices + fixed a warning with tini

**- A picture of a cute animal (not mandatory but encouraged)**

https://www.santelog.com/sites/santelog.com/www.santelog.com/files/images/accroche/adobestock_276208008_lama.jpeg

### CODE REVIEW

**Comment by rn** [comment]
Thanks for tracking this down. I'm not sure we want to give access to all device by default. In my opinion we want the packages locked down as much as possible by default and then use the image YAML to relax it on a per case basis. This is, for example, what we do with getty.

@djs55 @justincormack @deitch any strong opinion either way?

**Comment by deitch** [comment]
I'm mixed on this one. In general, I would prefer locked down. On the other hand, the purpose of the sshd package is administrative access. If it cannot access devices, it isn't much good. If everyone will have to enable it, does that mean it might as well have it as a default?

**Comment by rn** [comment]
@deitch fair point. 

@sprat looks like the second commit for updating the hashes has no signed-off-by line. Could you force push an update?

**Comment by sprat** [comment]
I agree with @deitch: after noticing that the sshd service has full priviledges & host pid already, I think that we should also grant access to devices too, for administrative tasks. It was the case before the introduction of per-services "devices" configuration.

@rn : I've pushed-force to add the signef-off line, I should have enabled that by default.

**Review by rn — APPROVED** [review]

**Comment by sprat** [comment]
Thanks!

**Pull request merged**
