### PR TITLE
go tool vet no longer supported

### PR DESCRIPTION
**Pull request by justincormack**
Just use go vet. The compat was removed in Go 1.13, but
go vet works in all supported versions now.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

puppt

### CODE REVIEW

**Comment by justincormack** [comment]
Ah, actually behaviour is different, will fix/upgrade Go.

**Comment by justincormack** [comment]
Fixed up should now work with all recent Go versions and will go vet correctly cross platform.

**Comment by justincormack** [comment]
Ah, its not working due to the skanky vendor script, which means go vet doesn't work. Tempted to just remove this...

**Comment by rn** [comment]
This was done as part of https://github.com/linuxkit/linuxkit/pull/3502 and https://github.com/linuxkit/linuxkit/pull/3500.

Closing this one

**Pull request closed without merging**
