### PR TITLE
FIX Docs Link: ./kernel to ../kernel/README.md

### PR DESCRIPTION
**Pull request by ndauten**
Signed-off-by: Nathan Dautenhahn <ndd@cis.upenn.edu>

**- What I did**

Converted link of .kernel in docs/kernels.md to point to ../kernel/README.md

**- How I did it**

Modified it. 

**- How to verify it**

Read it and verify link works

**- Description for the changelog**

FIX Docs Link: ./kernel to ../kernel/README.md

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by ndauten** [comment]
This might be better served linking the Makefile instead because the README doesn't have any general instructions on kernel image building.

**Comment by justincormack** [comment]
I think the current link makes more sense, it is just there to point out where the actual build code is, the README is that document itself.

**Comment by riyazdf** [comment]
@justincormack: good point, the GH page will display the README for the directory as well.  I'm fine with closing this to leave the link as-is

**Comment by ndauten** [comment]
The link as is points to "./kernel" and should minimally be changed to "../kernel". I wasn't sure if that would work fine in github, which is why I pointed it directly at ../kernel/README.md. 

If the link "../kernel" works in github then that would be my proposal.

**Comment by riyazdf** [comment]
@ndauten: good point, I missed that.  I agree that we should change the link to point to `../kernel`

**Comment by justincormack** [comment]
Ah ok, yes directory links work fine in github.

**Pull request merged**
