### PR TITLE
Add support for named pipes to init

### PR DESCRIPTION
**Pull request by kppk**
Signed-off-by: Tomas Knappek <tomas.knappek@gmail.com>

**- What I did**
Added support for named pipes in based images.

**- How I did it**
`pkg/init/cmd/init/init.go` to allow ` os.ModeNamedPipe` on rootfs

**- How to verify it**
Use RHEL based image for a service, and run it.

**- Description for the changelog**
Allow based images that use named pipes, for example RHEL descendants that use named pipe in /dev for systemd.

### CODE REVIEW

**Comment by justincormack** [comment]
Looks fine; this needs the image rebuilt before merge.

**Comment by rn** [comment]
@kppk apologies, this seems to have fallen down the cracks. Could you please rebase this PR to the latest?

Could you then also update all instances of `linuxkit/init` in the YAML files with the output of `linuxkit pkg show-tag .` executed in the `./pkg/init` directory. This will cause CI to pick up these changes. CI will fail, but I'll update push an updated `init` package and kick CI.

Thanks

**Comment by kppk** [comment]
@rn done

**Comment by rn** [comment]
@kppk thanks, but could you please separate out the updates to the YAMLs into a separate commit? Sorry, I completely forgot to mention that in my previous comment. It makes it easier

**Comment by kppk** [comment]
@rn can you check now pls?

**Comment by rn** [comment]
@kppk thanks. this looks good. I've tried to build the new init but there seem to be some issues with the notary server (I'm getting timeouts from three machines in at least tow different locations). I will retry in a while and once it succeeds will re-kick CI

**Comment by rn** [comment]
build the images and kicked CI

**Pull request merged**
