### PR TITLE
pkg/init: Mount /sys/fs/bpf

### PR DESCRIPTION
**Pull request by errordeveloper**
**- Description for the changelog**

pkg/init: mount /sys/fs/bpf (fix https://github.com/docker/for-mac/issues/4454)

### CODE REVIEW

**Comment by errordeveloper** [comment]
Not sure why CI is failing, the [error](https://github.com/linuxkit/linuxkit/pull/3516/checks?check_run_id=646176749#step:9:18) seems certainly unrelated:
```
[STDERR  ] 2020-05-05T13:29:53.917435298Z: /home/runner/work/linuxkit/src/github.com/linuxkit/linuxkit/test/cases/group.sh: 15: /home/runner/work/linuxkit/src/github.com/linuxkit/linuxkit/test/cases/group.sh: rt_label_set: not found
```

**Comment by errordeveloper** [comment]
I wonder if I should update any of the examples, and if so, the question is - which ones?

**Comment by deitch** [comment]
> I wonder if I should update any of the examples, and if so, the question is - which ones?

Did you run the `scripts/update-component-sha.sh`?

**Comment by deitch** [comment]
Nope, looks like you did not. Let's do that.

**Comment by deitch** [comment]
Looking better now. Image is almost pushed out.

**Comment by deitch** [comment]
Image is out.

**Comment by errordeveloper** [comment]
@deitch is `rt_label_set` function missing because of the image?

**Comment by errordeveloper** [comment]
@deitch CI is getting greener 🎉

**Comment by deitch** [comment]
Yup. That last one takes a long time to run, can be 60+ minutes (lots of building OSes and running them and tearing them down). When it clears green, we can merge this in.

**Pull request merged**
