### PR TITLE
Unpack filesystem for BIOS ISO

### PR DESCRIPTION
**Pull request by justincormack**
Now that LinuxKit works on a truly immutable filesystem, for an
ISO it makes sense to use the ISO filesystem rather than using
an initrd. Only major difference is you may need to specify the
device for the root filesystem in the kernel command line, but
we set a sane default of `/dev/sr0` if unspecified.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

cat-mummy

### CODE REVIEW

**Comment by justincormack** [comment]
I will bump the `moby` version when https://github.com/moby/tool/pull/135 is merged before merging this.

**Comment by justincormack** [comment]
I haven't changed the EFI ISO yet as there are some issues with testing it...

**Comment by deitch** [comment]
Is there a concern with the structure being different in an ISO that elsewhere? I don't mean technically as much as maintenance and runtime debugging? I don't see it as a major issue, but I also am unsure what the benefit is of having the files laid out in the ISO vs a single file `initrd.img`?

**Comment by rn** [comment]
@deitch we don't need to uncompress the initrd during boot so should be faster. Overall the system might be slower, though give that now all rootfs access go to the cdrom instead of the ram disk. @justincormack have you seen any issues with this?

**Comment by justincormack** [comment]
The benefits are
(a) actually immutable, while with `initrd` an attacker can remount writeable.
(b) faster boot time as there is no unpack stage for unpacking the initramfs
(c) (the main reason I have been working on this) much lower memory usage for huge images, in particular Kubernetes will not boot in under 4G of RAM, large amounts of which are permanently going to be used to store the boot images, especially since as we now have properly immutable container images you cannot free up space. We are roughly throwing away 1.5GB RAM permanently booting Kubernetes at present, which is kind of expensive and unworkable. (Yes we can trim it down a bit, but it is a gigantic piece of software right now).
(d) there are other filesystems that it makes sense to unpack, for example `squashfs` for embedded devices is the most sensible option, and would have the same benefits, will not throw away precious RAM, and can be used in place.

**Comment by deitch** [comment]
> much lower memory usage for huge images

That makes a lot of sense. I can see that.

**Comment by justincormack** [comment]
So far I have only run it with `qemu` so it is a little hard to judge speed, but it seems ok. Going to test hyperkit next (we dont actually have an ISO option in `linuxkit run hyperkit` right now)

**Pull request merged**
