### PR TITLE
cmd/qemu: Disable rng on macOS

### PR DESCRIPTION
**Pull request by rn**
With rng-random, booting hangs before switching
to the initrd.

fixes https://github.com/linuxkit/linuxkit/issues/3320

image

### CODE REVIEW

**Comment by justincormack** [comment]
Can we add a comment that this is a bug not a permanent issue please.

**Comment by rn** [comment]
added a comment

**Comment by rn** [comment]
ping

**Comment by rn** [comment]
@justincormack ping

**Pull request merged**
