### PR TITLE
remove -x from getty script

### PR DESCRIPTION
**Pull request by justincormack**
Was annoying me by being ultra verbose...

cc @deitch

### CODE REVIEW

**Comment by deitch** [comment]
> Was annoying me

I can see that! 

LGTM.

**Comment by justincormack** [comment]
hmm, the test seems to be relying on the output...

**Comment by ijc** [comment]
I can't see where, the stuff in the expect script is all normal stuff.

I think the issue is this:
```
getty: cmdline has console=ttyS0 but does not exist in /etc/securetty; will not be able to log in as root on this tty ttyS0.
```
which is preventing the script from logging in. Why this is just showing up here I cannot imagine.

**Comment by justincormack** [comment]
Yes, we actually need to add a full `securetty` not sure why this did not fail before

**Comment by justincormack** [comment]
Ok added a reasonable `securetty` file. Very unclear why the tests passed before still...

**Comment by justincormack** [comment]
@deitch I removed fetching `/etc/securetty` from host, as the host one is lacking a lot, and happy to add any more things to here (or you can bind mount).

**Comment by justincormack** [comment]
All green, merging.

**Comment by deitch** [comment]
@justincormack looks fine (and already merged), but with the `securetty` now I the container, what is the recommended method for a user overriding? If they just bind-mount, then it messes up all of the defaults in the `LABEL`. 

That `data:` idea is looking better...

**Comment by justincormack** [comment]
yeah, we should probably do the data think soon, but you can just open a PR to add new interface types here, there arent actually that many, and most are for different architectures which will need other support anyway.

**Comment by deitch** [comment]
I know why I am crazy enough to be online at this late hour - I just came back from watching an amazing Canada-USA ice hockey game - but why are you on this late? :-)

So you are thinking that soon enough the one in the getty package just will be comprehensive enough that people mostly won't need to mount it?

**Comment by justincormack** [comment]
Well it's already better than the host one. The host should not be
responsible for setting up the getty container correctly, it is likely to
not have a securetty file at all soon...

**Comment by deitch** [comment]
> to not have a securetty file at all soon

Soon? Why not now? See any reason to keep it?

**Comment by deitch** [comment]
Actually, do you know where the host-level `/etc/securetty` comes from? We don't have it anywhere in our repo except in `pkg/getty`, yet 

```
(ns: getty) linuxkit-025000000008:~# ls -l /proc/1/root/etc/securetty
-rw-r--r--    1 root     root            65 Jun 11 06:38 /proc/1/root/etc/securetty
```

**Comment by justincormack** [comment]
It's in the base alpine I think, which we are going to be able to remove
once we rewrite a few more shell scripts.

**Comment by deitch** [comment]
> It's in the base alpine I think

[Here](https://github.com/linuxkit/linuxkit/blob/master/pkg/init/Dockerfile#L9) with `alpine-baselayout`? 

```
RUN apk add --no-cache --initdb -p /out alpine-baselayout busybox musl
```

**Comment by justincormack** [comment]
```
/ # apk info -W /etc/securetty 
/etc/securetty is owned by busybox-1.26.2-r5
```

**Comment by deitch** [comment]
Yeah. I just did the first install, but `alpine-baselayout` depend upon `busybox`, which installs is.

**Pull request merged**
