### PR TITLE
Disable CONFIG_BPFILTER for 5.4.x-x86_64 kernel configuration

### PR DESCRIPTION
**Pull request by qdeslandes**
`bpfilter` is not meant to be used at all at this point. Only the module's boilerplate is available upstream. It seems to be causing issues to some users [#43](https://github.com/moby/moby/issues/43755). While it has been disabled in other kernel configurations (https://github.com/linuxkit/linuxkit/pull/3701), this one remained.

I am curious to know how come this was enabled? As far as I can tell, `CONFIG_BPFILTER` is disabled by default in the kernel, however the config files available in this repository seem to be pushed with `CONFIG_BPFILTER` enabled.

**- What I did**

Remove `bpfilter` from `5.4.x-x86_64` kernel configuration. 

**- How I did it**

Updated the configuration file and ran `make oldconfig` with https://github.com/linuxkit/linux.

**- How to verify it**

Build a kernel.

**- Description for the changelog**

Disable `CONFIG_BPFILTER` config option for 5.4 x86_64 kernel.

**- A picture of a cute animal (not mandatory but encouraged)**

280116894_5324585564270958_5619801542749031374_n
(Credit to Taronga Zoo Sydney)

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @qdeslandes! I saw your comment on the linked issue, and indeed wondered "didn't we disable this already in https://github.com/linuxkit/linuxkit/pull/3701 ?). Perhaps the assumption was  that the issue didn't affect older kernel versions 🤔 


@fredericdalleau @djs55 @dgageot PTAL (I don't have permissions on this repo to trigger CI 😅)

**Comment by thaJeztah** [comment]
> I am curious to know how come this was enabled? As far as I can tell, CONFIG_BPFILTER is disabled by default in the kernel, however the config files available in this repository seem to be pushed with CONFIG_BPFILTER enabled.

I see the file was added in https://github.com/linuxkit/linuxkit/commit/f9fee518a7524b467e9d089713ba92a233bc57b5 (https://github.com/linuxkit/linuxkit/pull/3450). Not sure how the config is determined. Perhaps others can fill me in on that part.

**Comment by qdeslandes** [comment]
> Thanks @qdeslandes! I saw your comment on the linked issue, and indeed wondered "didn't we disable this already in #3701 ?). Perhaps the assumption was that the issue didn't affect older kernel versions 🤔
> 
> @fredericdalleau @djs55 @dgageot PTAL (I don't have permissions on this repo to trigger CI 😅)

Unfortunately it would have an effect on every version as long as it's enabled. But it's very possible that no one noticed (yet) ;)

**Comment by thaJeztah** [comment]
Orthogonal to this PR, but maybe we should add a check for this in https://github.com/moby/moby/blob/13f426235482de9fe1e8f9d6a86a44cd79e976b8/contrib/check-config.sh (and print a warning); ISTR we had reports from users on other distros (or custom kernels) where it was enabled as well.

**Review by fredericdalleau — APPROVED** [review]
LGTM

**Comment by qdeslandes** [comment]
Hi folks, is this in a good state to be merged, or do you want a modification?

**Comment by deitch** [comment]
I think this is fine, but we would need @rn to comment. I am not sure what the pipeline for kernel is, if we need to build and publish anything. 🤷‍♂️

**Review by rn — APPROVED** [review]

**Pull request merged**
