### PR TITLE
update -rt

### PR DESCRIPTION
**Pull request by TiejunChina**
Upgrade -rt part.

### CODE REVIEW

**Comment by TiejunChina** [comment]
@rn Done with removing s390 stuff.

**Comment by TiejunChina** [comment]
@rn Thanks. CI issue? Do I need to change something on my side?

**Comment by rn** [comment]
The CI issues are unrelated to your PR. All PRs seem to be failing on one of the steps (running a LinuxKit instance on GCP).

**Comment by rn** [comment]
Could you rebase to include https://github.com/linuxkit/linuxkit/pull/3203 which hopefully will fix the GCP CI issue.
Thanks

**Comment by TiejunChina** [comment]
@rn Rebased.

**Comment by rn** [comment]
Thanks. CI is green thanks to the rebase, I'll pick up the -rt update with the next round of kernel updates.

**Pull request merged**
