### PR TITLE
bump alpine to 3.14, remove go version hack

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**- What I did**

Updated alpine from 3.13 to 3.14.

Since 3.14 includes go 1.16.5, we no longer need that hack to grab it from edge, so got rid of it

**- How I did it**

Updated `tools/alpine/Dockerfile` and some `packages` files

**- How to verify it**

CI

**- Description for the changelog**

alpine 3.14 as base

I didn't yet push out the images. I will do so and then update the PR.

### CODE REVIEW

**Comment by deitch** [comment]
Also removed `gummiboot` from `packages.x86_64` for two reasons:

1. It is no longer available in Alpine packages from 3.14 onwards
2. I did a search, and we don't use it anywhere in the entire repository

**Comment by deitch** [comment]
This _does_ clean up the golang repo dependency, which is great. But it does use musl and musl-dev 1.2.2-r3 (i.e. greater than 1.2.2-r0), which brings back the faccess2 issue, see [here](https://wiki.alpinelinux.org/wiki/Draft_Release_Notes_for_Alpine_3.14.0#faccessat2)

@justincormack and @thaJeztah , I thought the two of you knew this issue? Is it fixed in the version of runc we are using?

**Comment by thaJeztah** [comment]
I _think_ the faccess2 issue should be resolved in runc v1.0.0-rc95 and up (at least, when running on a kernel version that supports it, if I'm not mistaken). I see https://github.com/linuxkit/linuxkit/pull/3684 was still pending (what version is currently used?)

**Comment by deitch** [comment]
[Looks like](https://github.com/linuxkit/linuxkit/blob/master/pkg/runc/Dockerfile#L15) v1.0.0-rc10. So we need #3684 as you pointed out. What was the issue there?

**Comment by deitch** [comment]
Pushed out images and manifests. But I did not update downstream dependencies.

**Comment by rn** [comment]
@deitch where are you with this? The base seems updated but I don't seen any uses of it. Are you planning to do that at some point?

**Comment by deitch** [comment]
We are blocked by #3684. With 3.14, we have the updated musl packages, which create the containerd/runc issues. When that one (#3684) is in, we can move this one in.

**Comment by rn** [comment]
Thanks. Looks like @djs55 made some progress on it

**Comment by djs55** [comment]
@deitch Hopefully this is unblocked by the runc/containerd upgrade. Let me know if you're too busy -- I can try to rebase it and regenerate the images if that's helpful.

**Comment by deitch** [comment]
Yeah, I will try to tackle next week.

**Comment by deitch** [comment]
OK, updated. I rebuilt based on alpine 3.14. @djs55 does this take advantage of your changes in #3684? What do I need to do to ensure it gets them?

**Comment by djs55** [comment]
This LGTM. Do we just need to update the alpine yamls in the packages (and then rebuild the packages and then update the package hashes)? I think everything should just work, as far as I can see.

**Comment by rn** [comment]
Yes, this still requires the full dance of updating tools then packages and then tests to the new version.

**Comment by deitch** [comment]
"the full dance" - well put.

**Comment by deitch** [comment]
Oh that is such a painful "full dance".

Finally updating the packages in `pkg/`. I assume that will run all night, have to be restarted a few times. Hopefully sometime tomorrow it will be ready.

**Comment by djs55** [comment]
A previous CI run failed pulling `runc` but when I checked with `linuxkit pkg push` it was already built and pushed. So I hit the re-run tests button. Hopefully this time ...

**Review by djs55 — APPROVED** [review]

**Pull request merged**
