### PR TITLE
Merge moby tool back into LinuxKit

### PR DESCRIPTION
**Pull request by justincormack**
The split made it harder to work with LinuxKit and no one else is using the tool.

This merges with different roots.

The merge is of this branch https://github.com/justincormack/tool/tree/prepare-to-merge

leimur loop

### CODE REVIEW

**Comment by justincormack** [comment]
Gordon is complaining as the merge commits are not signed-off-by so inclined to ignore this.

**Comment by AkihiroSuda** [comment]
Is the executable name still "moby"?

**Comment by justincormack** [comment]
No, there is a `moby` library, but `moby` was already the same code as `linuxkit build`.

**Comment by justincormack** [comment]
Ok, as discussed moved all the `moby/tool` code under `src/cmd/linuxkit`.

**Comment by justincormack** [comment]
ping @rn

**Comment by AkihiroSuda** [comment]
moby/tool repo should be archived now?

**Comment by justincormack** [comment]
I just need to transfer open issues to here.

**Pull request merged**
