### PR TITLE
Mount /var/log to getty and ssh again

### LINKED ISSUE #2269: /var/log no longer in getty and ssh containers
In c48acd5d9d802812456f9d445961b27d9486f202 I removed the entire `/var` bind mount, which was a mistake, since we (I think) do want `/var/log` in that context. We should bind that specific path.

Filing and self assigning as a reminder to myself since it is getting towards the end of the day and I'm not sure I'll get to this before next week.

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**- What I did**
Mounted `/var/log` back into getty and sshd containers

Closes #2269 for @ijc 

**- How I did it**
Added to the labels

**- How to verify it**
1. Run it
2. See `/var/log`

**- Description for the changelog**

Return mount for `/var/log` to getty and sshd containers

**- A picture of a cute animal (not mandatory but encouraged)**
monsters

### CODE REVIEW

**Comment by deitch** [comment]
Will change tags for `examples/` etc. now

**Comment by deitch** [comment]
Hashes updated.

That script for updating them is nice, but it would be great if there were an option to say, "update all linuxkit/sshd hashes to x", as opposed to "from x to y"

**Comment by justincormack** [comment]
The images are not signed, hence CI fail.

**Comment by deitch** [comment]
Just waiting for one "LGTM" and I'll push them out.

**Comment by deitch** [comment]
OK both pushed out. If someone can kick off CI again? 

While we are at it, can someone give me a login for linuxkit.datakit.ci ?

**Comment by ijc** [comment]
LGTM.

Logins to linuxkit.datakit.ci are via github integration. There's a "Login with Gitihub" link underneath the login form. The flow is a bit odd, once you've logged in you might need to hit back a few times and then refresh.

I've clicked rebuild on this one now.

**Comment by deitch** [comment]
> LGTM. I've clicked rebuild on this one now.

OK, when it passes I will merge it in. Thanks for restarting.

**Comment by deitch** [comment]
Phew. Finally pushed out.

@ijc: should we update the base `FROM` in all of the `pkg` images? It isn't strictly necessary, but if it is used as a template for others...

**Comment by deitch** [comment]
(accidentally put comment in wrong PR, please ignore; deleting)

**Comment by deitch** [comment]
Still waiting for CI to complete...

**Comment by deitch** [comment]
Eh, apparently, I do not have rights to click "Rebuild" in CI. Would someone please do it?

**Comment by deitch** [comment]
Ah, finally passed. Merging.

**Pull request merged**
