### PR TITLE
use correct manifest name when pushing

### PR DESCRIPTION
**Pull request by deitch**
**- What I did**

Fixed how manifests are created with `linuxkit pkg push`

**- How I did it**

Passed the name of the manifest, rather than the name of the arch-specific image, to `ManifestPush()`

**- How to verify it**

Run it. I just did, it works.

Also, CI is a nice thing.

**- Description for the changelog**

Fix pushing of packages

### CODE REVIEW

**Comment by deitch** [comment]
Fixes #3628

**Comment by rn** [comment]
@deitch could you push a DCO commit?

**Comment by deitch** [comment]
Oops. Fixed.

**Review by rn — APPROVED** [review]

**Comment by deitch** [comment]
Thanks. As soon as CI is green, will merge in.

**Pull request merged**
