### PR TITLE
kernel: Update to 4.11.3/4.9.30/4.4.70

### PR DESCRIPTION
**Pull request by rneugeba**
There was no 4.10 kernel update this week

Signed-off-by: Rolf Neugebauer <rolf.neugebauer@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
There is no 4.10, it is EOL. We can remove it...

**Comment by rneugeba** [comment]
Ah, missed that. Updated the PR

**Comment by justincormack** [comment]
also need to remove https://github.com/linuxkit/linuxkit/tree/master/test/cases/020_kernel/002_config_4.10.x

**Comment by rneugeba** [comment]
done

**Comment by rneugeba** [comment]
I'll merge once the compile finished

**Pull request merged**
