### PR TITLE
containerd v1.2.0

### PR DESCRIPTION
**Pull request by ijc**
This is mostly the usual mechanical bump (no code changes needed in LinuxKit) except I switched to using credentials helpers since the last bump I did so I had to update some of the scripting/tooling to cope with that on Linux (see the first commit).

### CODE REVIEW

**Comment by ijc** [comment]
I've not run it at all, CI should cover the basics but this being a new minor version I guess there is a chance that e.g. `ctr` interfaces have changed in ways which people might trip over.

**Comment by ijc** [comment]
CI:
```
[FAIL    ] linuxkit.packages.getty-containerd 90.49s
```
Not exactly a huge shock. I'll take a look.

**Comment by ijc** [comment]
I've kicked CI to have another go while I dig into it, on the off chance it was just a flake.

**Comment by ijc** [comment]
Failed for me locally too, so not a flake. Trying to obtain any useful logs.

**Comment by ijc** [comment]
Looks like I need to rebase so I'll sort out the minor nit as I go.

**Comment by ijc** [comment]
Rebased and force pushed, will merge with the existing approvals once CI is green.

I dropped the containerd maintainers a line re the new need to bind `/var/lib/containerd` just in case it wasn't expected. We shouldn't block this PR if it wasn't though and should instead revert the relevant commit whenever we pickup a fixed v1.2.x.

**Comment by rn** [comment]
SGTM

**Comment by justincormack** [comment]
Yes, curious as to why that change is needed...

**Pull request merged**
