### PR TITLE
kubernetes: add socat to cri-containerd and dependency fixes

### PR DESCRIPTION
**Pull request by w9n**
See #2639

### CODE REVIEW

**Comment by w9n** [comment]
#2632

**Comment by w9n** [comment]
```
[+ 68m 20s] error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%22org.opencontainers.image.revision%22%3A%22cc4d2e96fba86ee1816ab2f6376855090a9578bc%22%2C%22org.opencontainers.image.source%22%3A%22https%3A%2F%2Fgithub.com%2Flinuxkit%2Flinuxkit%22%7D&memory=0&memswap=0&networkmode=none&rm=1&shmsize=0&t=linuxkit%2Fcontainerd%3A69968ebd9f66edccceec0344865bf648ad105ea9-amd64&target=&ulimits=null: No trust data for 69019e422ef1185138e24e49d24330aab7002b74
```
alpine base image need to be signed and pushed first

**Comment by eyz** [comment]
@w9n maybe revert the image hash, let the CI go, and then get someone to build and push it first?

**Comment by w9n** [comment]
The image can be build from my branch aswell - no need for 2 PRs

**Comment by eyz** [comment]
@w9n do you mean from w9n:helm-bug? Ideally CI would pass before the package get built and signed, from what I've seen. I think you may want to revert the hash and `git push -f` to get CI to pass, then one of the maintainers can build the package and go from there.

**Comment by w9n** [comment]
ill do if required but the first PR and ci would be pointless and inconsistent because the tests and images would use old hashes and containers. This might should be rethought. @ijc will take care of this PR next week.

**Comment by rn** [comment]
This PR changes too many unrelated things in one commit. From I can see, there are several unrelated changes, which ideally should be broken up into separate commits.
- bump `containerd` to a new non-tagged version and at this point I think we prefer to only use tagged versions.
- Update Kube project to new containerd, Note, if we bump `containerd`, we should bump all uses of `containerd` because otherwise we run multiple versions of `containerd` which seems messy and makes it hard to debug.
- Add `socat` to `cri-containerd` package
- Update `cri-containerd` hashes.

Also, changes to the `linuxkit/alpine` package are best done by a maintainer, because by the time one of us pushes your changes, the versions may have changed again. It also needs to be pushed to `arm64` which would likely change the `aarch64` versions file as well.

**Comment by ijc** [comment]
I added `socat` as part of #2665. I think the containerd bump here can wait until beta.3 comes out (should be quite soon it seems).

**Pull request closed without merging**
