### PR TITLE
Small improvements to projects/kubernetes

### PR DESCRIPTION
**Pull request by ijc**
**- What I did**

Some small updates to `projects/kubernetes`:
* kubernetes: update to latest init
* kubernetes: Combine boot-{master,node}.sh into a single script
* kubernetes: give each instance a specific state directory
* kubernetes: Create disk in state dir

and some improvements to the qemu runner:
* Add state dir support to Qemu runner.
* Add metadata support to Qemu runner.

The scripting can now be used to boot master & nodes on both Linux and MacOS.

**- How I did it**

**- How to verify it**

After building `./boot.sh` and `./boot.sh 0 -join wibble` should boot on both MacOS and Linux, although due to #2031 I've not been able to fully test that. Note that on Linux the node is not yet expected to be able to contact the master, since I haven't sorted out the networking side yet.

**- Description for the changelog**

Minor updates to projects/kubernetes, improved support in LinuxKit qemu runner.

**- A picture of a cute animal (not mandatory but encouraged)**

/cc @errordeveloper

### CODE REVIEW

**Comment by justincormack** [comment]
@ijc the `mkimage` failure looks like the state directory cleanup needs fixing.

**Comment by justincormack** [comment]
Other than that LGTM when tests green

**Comment by ijc** [comment]
@justincormack that sounds plausible, but OOI how did you determine that? [The logs](https://linuxkit.datakit.ci/log/saved/linuxkit-build-of-13a94c7a3c2a5777e9bc48764f2f67e9109f999d-default-ci-pr/5665ca4ece435a83ea678cc0487916d73c865c02) don't seem to contain anything other than the `[FAIL    ] linuxkit.packages.mkimage 194.11s`. Am I failing to find some more enlightening source of information?

**Comment by justincormack** [comment]
Full logs are in the link at the top of the logs page once the run finishes, in this case at https://github.com/linuxkit/linuxkit-logs/commit/5665ca4ece435a83ea678cc0487916d73c865c02

**Comment by ijc** [comment]
Ah, I read "Loaded from commit 5665ca4ece435a83ea678cc0487916d73c865c02" as meaning the test run had started with that state, rather than that being where the log was loaded from!

**Comment by ijc** [comment]
Hmph. `linuxkit.packages.mkimage` works for me locally and I can't really see how:
```
+[STDERR  ] 2017-06-13T11:02:07.489584158Z: + find . -iname mkimage* -not -iname *.yml -exec rm -rf {} ;
+[STDERR  ] 2017-06-13T11:02:07.495564602Z: find: `./mkimage-state': No such file or directory
```
Could ever happen, unless there is some other process racing with it.

Unlike in the logs the quoting is correct in the actual test `find . -iname "mkimage*" -not -iname "*.yml" -exec rm -rf {} \;`.

Something quite exciting must be going on I think.

**Comment by justincormack** [comment]
shouldnt it be `find. -iname 'mkimage*'` with single quotes?

**Comment by ijc** [comment]
I think either sort of quoting ought to be ok for this case, globs aren't expanded in either.

I may have forgotten to type `make` after switching back to this branch and before running the tests, so maybe I will be able to repro after all...

**Comment by ijc** [comment]
Yes, I can repro after all, will figure it out...

**Comment by rn** [comment]
I also noticed this when I moved some of the tests to work with HyperKit and "fixed" it by doing a `|| true` after the find in the clean up function #1982

**Comment by ijc** [comment]
`find` is trying to recurse into `mkimage-state` after it has traversed (and remove it)...

I think the right answer is to add `-depth` to the `find`, which I'll do here.

I think it might also be worth making the qemu runner only make the state dir if it has something to put there, in this case it's just creating an empty dir, it's also leaking `qcow2.disk-state`...

**Comment by justincormack** [comment]
Ah that makes sense

**Comment by ijc** [comment]
I'm just testing a patch to not create the dir if it isn't needed, I expect I'll push it before the CI finishes, but if not whoever is thinking of merging might want to wait for one more commit to show up.

**Pull request merged**
