### PR TITLE
Fix return code of rungetty.sh

### PR DESCRIPTION
**Pull request by giggsoff**
In case of INITGETTY defined we will return exit code 1 which is not expected

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by stephen-goveia** [comment]
@giggsoff do you this PR might fix this Issue? https://github.com/linuxkit/linuxkit/issues/3811

**Comment by deitch** [comment]
> In case of INITGETTY defined we will return exit code 1

I guess because we do `[ -z "$INITGETTY" ] && wait`, which, if `-z` fails, leaves the last code to be `1`.

Maybe this should be the following?

```
[ -n "$INITGETTY" ] || wait
```

I tried that, and it always returns `0`.

After fixing, you do need to run `update-package-tags`, but keep it simple for this, and just run:

```
./scripts/update-component-sha.sh --image $(linuxkit pkg show-tag pkg/getty)
```

**Review by deitch — CHANGES_REQUESTED** [review]
Please simplify to `[ -n "$INITGETTY" ] || wait`

and run `update-component-sha.sh`

**Comment by giggsoff** [comment]
> @giggsoff do you this PR might fix this Issue? #3811

No, it is not related. My assumption that the problem there is in outdated linuxkit without https://github.com/linuxkit/linuxkit/commit/24db42dd686a69afbc5b01cabb01fdf088d2cf44.

**Comment by deitch** [comment]
No, it should pull from the local cache. You used to have to build it and push it out manually (which required a maintainer). At some point we changed it so that it builds to local cache and can test from there, and when you merge, it pushes it to registry. Strange that it failed. Did you figure it out?

**Review by deitch — APPROVED** [review]

**Comment by giggsoff** [comment]
> No, it should pull from the local cache. You used to have to build it and push it out manually (which required a maintainer). At some point we changed it so that it builds to local cache and can test from there, and when you merge, it pushes it to registry. Strange that it failed. Did you figure it out?

I put required changes (to use cache with packages in CI) in the third commit of the PR. Now the error I mentioned earlier become unexpected.

**Review by deitch — APPROVED** [review]

**Pull request merged**
