### PR TITLE
Add development tools to linuxkit/alpine mirror

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**- What I did**
Added the following packages to `linuxkit/alpine` local mirror:

* autoconf
* gettext
* gettext-dev
* libtool
* openssl-dev

As discussed in Slack with @rn 

**- How I did it**
1. Added packages to `packages`
2. Ran `make` to build and saved versions
3. Commited
4. Pushed
5. Opened this PR

**- How to verify it**
Run the image. See that `apk add` works with those packages.

**- Description for the changelog**

Add 5 development packages to alpine mirror

**- A picture of a cute animal (not mandatory but encouraged)**
salt vampire

### CODE REVIEW

**Comment by deitch** [comment]
OK, pushing out image hash and will merge after CI passes.

**Comment by rn** [comment]
just push out the image hash before submitting the PR. `make` should do that (as I mentioned on slack)

**Comment by deitch** [comment]
> just push out the image hash before submitting the PR. 

Still figuring this process out. Somewhere in last week or two someone said the flow usually is:

1. Make change in local, commit, push to GitHub, create PR
2. Wait for approval/LGTM
3. Push image hash
4. After CI passes, merge

`make` wanted to do everything here, but I stopped it to try and follow the process. Is it different?

**Comment by deitch** [comment]
In any case, the push is being painfully slow. It will get through soon enough....

**Comment by deitch** [comment]
Phew. Finally pushed out.

@rn: should we update the base `FROM` in all of the `pkg/` images? It isn't strictly necessary, but if it is used as a template for others...

**Comment by rn** [comment]
no, it's too tedious to update all packages. We only resync them once in a while or if there is a vulnerability in one of the packages.

**Comment by deitch** [comment]
> We only resync them once in a while or if there is a vulnerability in one of the packages.

OK, although those scripts help (and I just updated them to make it a bit easier).

**Pull request merged**
