### PR TITLE
FIX disk parameter usage

### PR DESCRIPTION
**Pull request by Fabsolute**
**- What I did**
The `-disk` parameter is not working with `linuxkit run virtualization`. Fixed

**- How I did it**
Changed conditions about disk check and created image if file not provided

**- How to verify it**
CI

**- Description for the changelog**
`-disk` usage fixed for `linuxkit run virtualization`

**- A picture of a cute animal (not mandatory but encouraged)**
Here is my cat Sanji
sanji

### CODE REVIEW

**Comment by deitch** [comment]
Cat is cute. 😄

**Review by deitch — COMMENTED** [review]
Thanks for fixing this. I see how you did it, makes sense.

Only question I have is, why change `d` (which is the item coming from the `range`), as opposed to using `diskPath` the var? Changing an item in a loop, when your purpose is not to change the item, is a bit anti-pattern, isn't it?

**Comment by Fabsolute** [comment]
Actually I made a little bit consistent with the other implementations like qemu, vmware etc.

**Comment by deitch** [comment]
Oh, yeah? Then I won't complain. 😁

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
CI can take a while.

**Comment by nustiueudinastea** [comment]
Hey @deitch any chance we can merge this? PR looks pretty good

**Comment by deitch** [comment]
Yeah. We have one failing test, we should rerun it, but I cannot find the button to do so.

**Comment by Fabsolute** [comment]
> Yeah. We have one failing test, we should rerun it, but I cannot find the button to do so.

I can create a dummy commit to retrigger the tests 🤔

**Comment by deitch** [comment]
Would you please? I am wrangling with the GitHub CLI to get it to do the same thing, and it is not making it easy.

**Comment by deitch** [comment]
Running.

**Comment by Fabsolute** [comment]
Oh, snap! It failed again. I rebased and pushed again.

**Pull request merged**
