### PR TITLE
Upgrade -rt kernel version to 4.14.29-rt25.

### PR DESCRIPTION
**Pull request by TiejunChina**
Upgrade -rt kernel version to 4.14.29-rt25.

### CODE REVIEW

**Comment by ijc** [comment]
As an aside we should perhaps look to increasing the bus factor of the kernel builds...

**Comment by TiejunChina** [comment]
@ijc Understood. Note I just rebase that since yesterday new -rt vevrsion was released.

**Comment by rn** [comment]
@TiejunChina sorry, I messed up this PR. There was a conflict (due to https://github.com/linuxkit/linuxkit/pull/2969) which I tried to resolve via the web UI and it didn't add a DCO on my merge :(

Could you rebase your PR to master, resolve the conflict (some hashes changed) and then force push?

**Comment by TiejunChina** [comment]
@rn NP and done.

**Comment by TiejunChina** [comment]
@GordonTheTurtle But I didn't open new one or am I wrong somewhere?

**Comment by rn** [comment]
@TiejunChina apologies (again).  While you rebased I did a kernel update and now there is another conflict. Could you rebase again (the conflict should be trivial to resolve). I'll then merge and pick up the changes with the next round of kernel updates

**Comment by TiejunChina** [comment]
@rn Done.

**Pull request merged**
