### PR TITLE
Update kernel to 5.2.9/4.19.71/4.14.142/4.9.192 and WireGuard to 0.0.20190913

### PR DESCRIPTION
**Pull request by rn**
- Update the kernels to 4.19.71/4.14.142/4.9.192 (skipping a few kernels missed while containerd tests failed and travelling)
- Remove 5.1.x kernel
- Add 5.2.x kernel
- 5.2.x is disabled for s390x due to https://github.com/linuxkit/linuxkit/issues/3412
- Update WireGuard to 0.0.20190913
- Make VSOCKETs a module on all kernels
- Build kernel and kernel tests with latest alpine base

bear

### CODE REVIEW

**Comment by rn** [comment]
CI failed because i use 4.9.191 in the YAML, should have been 4.9.192. Force pushed an update

**Comment by justincormack** [comment]
Failed again...

**Comment by rn** [comment]
Invalid trust data for 4.9.x kernel. This failed during the build but looks like the rebuild didn't push it

**Comment by rn** [comment]
repushed images.  kicking CI

**Comment by rn** [comment]
ping @justincormack CI is green now. Will re-enable 5.2.x on for s390x on the next kernel update if the workaround works

**Pull request merged**
