### PR TITLE
Add rsync in sshd package

### PR DESCRIPTION
**Pull request by errordeveloper**
The `rsync` command has to be available on both ends.

### CODE REVIEW

**Comment by errordeveloper** [comment]
I am not sure why CI gives me this error:
```
Failed to create OCI spec for linuxkit/sshd:a0ac44ab1cbfd14e368ed139c6a4e128f2a33513: Trusted pull for linuxkit/sshd:a0ac44ab1cbfd14e368ed139c6a4e128f2a33513 failed: No valid trust data for a0ac44ab1cbfd14e368ed139c6a4e128f2a33513
```

From previous experience, I recalled that I need to bump all uses of a package in the same PR/commit that introduces the changes to the package itself - does CI now assume that changes are made separately?

**Comment by deitch** [comment]
> I'm not sure we want the sshd base layer to be the union of anything anyone might ever want in that context. e.g. we currently IIRC don't include the packages necessary to make scp "just work" (or perhaps I'm thinking of sftp, either way).

Tough call. I tend to agree with this sentiment, but then why do we have the wireguard package installed (see [here](https://github.com/linuxkit/linuxkit/blob/master/pkg/sshd/Dockerfile#L13))? 

I think this might be easier if there were a simple way for a consumer of `lkt` to just use the standard `linuxkit/sshd` package, but yet have the desired tools made available without having to extend the base. Mounted in? Standardly available dir? Unlike most `pkg/` parts, `sshd` (it keeps auto-correcting to `sushi`) is a CLI, so people will want things in there that they find useful, and so we are likely to get more and more of these, and more and more discussion of what is "standard" and "base" and "commonly used". We definitely _have_ an answer with "extend it in a `Dockerfile` with what you want," but I am wondering if we could have an easier one?

**Comment by errordeveloper** [comment]
> Tough call. I tend to agree with this sentiment, but then why do we have the wireguard package installed (see here)?

Yes, inderd. I had second thoughts, but after finding wireguard, I figured rsync might be reasonable to add.

**Comment by deitch** [comment]
I just looked at the history; wireguard has been in since July 2017, when it was added to everything else. I don't recall the PR that added it, or the discussions around it, offhand. I do recall other discussions around adding more "standard" packages to getty and sshd, and usually they were held back to keep it minimal.

I would like to see none of it in there, and one of:

* a way to mount in desired `apk` packages (or binaries) from another location, so they can be kept clean
* a way to add them in "on the fly", i.e. during `lkt build`

Either of these essentially comes down to some higher-order form of composition. We already have composition of layers and packages via `Dockerfile` to build OCI images, and we have composition of those images using a `linuxkit.yml` to build OS images via `lkt build`. There is some middle layer here, where lkt can know to do some additional composition.

I am just not sure what that is, and if it is worth it...

**Comment by errordeveloper** [comment]
Making it easier to fork a package without copying much of the config would be great. For example, sshd package has many binds, and wouldn't want to make a copy of those, I would rather add one or two on top. Perhaps we could add 'from' field in pkg config?

**Comment by deitch** [comment]
We have spoken in the past about some of the issues with appending to binds rather than overriding. Lots to do here for configurability...

**Comment by rn** [comment]
I'm with @ijc on leaning towards not adding `rsync` to the `sshd` package. It seems a bit niche.

**Pull request closed without merging**
