### PR TITLE
wireguard: update to 0.0.20191212

### PR DESCRIPTION
**Pull request by djs55**
**- What I did**

Bumped wireguard to the latest release.

**- How I did it**

Edited the URL and `sha256`

**- How to verify it**

Unsure -- I don't use wireguard myself. This was requested by a user of Docker Desktop and looked simple. I'm hoping that a CI run will be enough to check.

**- Description for the changelog**

- Bump wireguard to 0.0.20191212

### CODE REVIEW

**Comment by deitch** [comment]
I use WireGuard, but not on lkt. We should ask @zx2c4 who has contributed in the past and can comment.

I will admit that I am curious of the use case. WG from a desktop is used regularly. How are they using it from within the Docker Desktop VM?

**Comment by zx2c4** [comment]
This PR is fine. I don't have much to offer in terms of "how to use Docker" for testing or whatever, but between September and December, the build system hasn't changed, so a simple bump like this should be fine.

**Comment by djs55** [comment]
@deitch I'm also curious about the use-case -- I'll try to find out!

**Comment by rn** [comment]
CI does not pick up the changes until I update the kernel (which I plan to do later this week).

**Pull request merged**
