### PR TITLE
Avoid running git command 254 times

### PR DESCRIPTION
**Pull request by dgageot**
Make sure those git commands run only once and not 254 times in total.

*Before:*
```
$ make -C kernel -n SHELL="/bin/bash -x" build_5.15.x
+ git rev-parse --show-toplevel
+ uname -m
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse HEAD
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
docker pull linuxkit/kernel:5.15.27-c88d1943a797df4fde159a907d5b2ddfd684e5ae-arm64 || docker build --build-arg KERNEL_VERSION=5.15.27 --build-arg KERNEL_SERIES=5.15.x --build-arg EXTRA= --build-arg DEBUG= --build-arg BUILD_IMAGE=linuxkit/alpine:2be490394653b7967c250e86fd42cef88de428ba --label org.opencontainers.image.source=https://github.com/linuxkit/linuxkit --label org.opencontainers.image.revision=c79558cc5a642ff6b8c39866fe15814e568759c1 --label org.mobyproject.linuxkit.kernel.buildimage=linuxkit/alpine:2be490394653b7967c250e86fd42cef88de428ba --no-cache -t linuxkit/kernel:5.15.27-c88d1943a797df4fde159a907d5b2ddfd684e5ae-arm64 .
```

*After:*
```
make -C kernel -n SHELL="/bin/bash -x" build_5.15.x
+ git ls-tree --full-tree HEAD -- /Users/dgageot/src/linuxkit/kernel
+ awk '{print $3}'
+ git update-index -q --refresh
+ git diff-index --quiet HEAD -- /Users/dgageot/src/linuxkit/kernel
+ git rev-parse --show-toplevel
+ uname -m
+ git rev-parse HEAD
+ git rev-parse HEAD
+ git rev-parse HEAD
+ git rev-parse HEAD
+ git rev-parse HEAD
+ git rev-parse HEAD
docker pull linuxkit/kernel:5.15.27-d6fc9337526f0f2f8a64ee150fe4fb9c511f886a-arm64 || docker build --build-arg KERNEL_VERSION=5.15.27 --build-arg KERNEL_SERIES=5.15.x --build-arg EXTRA= --build-arg DEBUG= --build-arg BUILD_IMAGE=linuxkit/alpine:2be490394653b7967c250e86fd42cef88de428ba --label org.opencontainers.image.source=https://github.com/linuxkit/linuxkit --label org.opencontainers.image.revision=f39c638c43bd66d7f0efd70783942ede1c557bf8 --label org.mobyproject.linuxkit.kernel.buildimage=linuxkit/alpine:2be490394653b7967c250e86fd42cef88de428ba --no-cache -t linuxkit/kernel:5.15.27-d6fc9337526f0f2f8a64ee150fe4fb9c511f886a-arm64 .
```

### CODE REVIEW

**Review by djs55 — APPROVED** [review]

**Comment by deitch** [comment]
I don't get it. How was it called 254 times, and how does this help?

**Comment by dgageot** [comment]
> I don't get it. How was it called 254 times, and how does this help?

I've added information to explain the before/after situation.
Basically, I added memoization to prevent such variable to be evaluated every time on of the multiple targets uses it.

**Comment by deitch** [comment]
That is the output, thanks. But I still don't understand why this changes. I cannot see why it is called 254 times in the first place.

**Comment by dgageot** [comment]
> make -C kernel -n SHELL="/bin/bash -x" build_5.15.x

This happens because the Makefile uses a template (`kernel`) to generate the build targets.

**Comment by dgageot** [comment]
> > make -C kernel -n SHELL="/bin/bash -x" build_5.15.x
> 
> This happens because the Makefile uses a template (`kernel`) to generate the build targets.

What also doesn't help is that `$(TAG)` is used all over the place. Without memoization, its value being `$(HASH)$(DIRTY)`,  it generates two executions of `git` each time it's evaluated.

**Comment by deitch** [comment]
Ah, right! [this here](https://github.com/linuxkit/linuxkit/pull/3915/files#diff-3a325663233178293ee38b8161f3be511a466af7e0156b9d03d5aed0497564bfR95):

```makefile
define kernel
```

Now I remember. Also that I struggled with it.

**Review by deitch — APPROVED** [review]

**Pull request merged**
