### PR TITLE
Add VRF kernel module

### PR DESCRIPTION
**Pull request by barajus**
**- What I did**
Added kernel mode for VRF

**- Description for the changelog**

Hi! 
LinuxKit is used for Docker for Mac, but since VRF is not enabled, every container who needs VRF and L3 segmentation are broken by design.
https://www.kernel.org/doc/html/latest/networking/vrf.html
https://man7.org/linux/man-pages/man8/ip-vrf.8.html

That would be very helpful to enable it, since a lot of networking simulation tools and containers rely on this feature :(

```
root@6fe1680126e4:/# ip link add vrf-blue type vrf table 10
RTNETLINK answers: Operation not permitted
root@6fe1680126e4:/# insmod vrf
insmod: ERROR: could not load module vrf: No such file or directory
```

**- A picture of a cute animal (not mandatory but encouraged)**

Signed-off-by: Julien Dhaille [julien@dhaille.com](mailto:julien@dhaille.com)

### CODE REVIEW

**Comment by barajus** [comment]
Signed-off-by: Julien Dhaille [julien@dhaille.com](mailto:julien@dhaille.com)

**Review by barajus — COMMENTED** [review]
Signed-off-by: Julien Dhaille [julien@dhaille.com](mailto:julien@dhaille.com)

**Comment by barajus** [comment]
Hi,
I just force-pushed with an amended comment.
Thank for considering these changes, that would be very helpful :)
Julien

**Comment by barajus** [comment]
Hi!
Any chances to get an update on this one?
Thanks :)

**Comment by barajus** [comment]
Hi @djs55 
Do you think it will be possible to consider this PR?
sorry the noise :)

**Comment by mestery** [comment]
This would be pretty epic to enable as I imagine people are still hitting this. Any chance this could be rebased and merged?

**Comment by mestery** [comment]
@barajus this is still not passing the DCO check either, I think you need to update the actual commit with a correct "Signed-off-by". This can be done by doing this: `git commit --amend -s`, which will amend it.

**Comment by mestery** [comment]
We really need to get the DCO fixed on this and have this merged. Can someone from the linuxkit team help out here? There are valid use cases for enabling the VRF module, and it would be ideal to get this added.

**Comment by mestery** [comment]
> Hi @mestery, I just amed the commit, but it looks like DCO is still stuck :(

One of your commits still is incorrect and contains this, can you make them all as below:

```
Signed-off-by: barajus <julien.dhaille@gmail.com>
```

Also, you have a merge commit in here, not sure if that is causing problems as well.

**Comment by deitch** [comment]
Looks like the DCO has not been fixed. @barajus do you want to squash the commit down to one and ensure it is signed? Conversely, @mestery , if you are active on this and want to open this in a new PR (with a single signed commit), we can get that in as soon as CI is clean.

**Comment by floatingstatic** [comment]
+1 I'm also interested in this feature

**Comment by mestery** [comment]
This is merged upstream in https://github.com/linuxkit/linuxkit/pull/3966.

@deitch we should probably close this one now.

**Comment by deitch** [comment]
We did! And many thanks to @mestery for providing it. It is in the 6.6.x kernel.

**Pull request closed without merging**
