### PR TITLE
linuxkit: add -vpnkit-socket flag

### PR DESCRIPTION
**Pull request by MagnusS**
Add a new flag to set the VPNKit ethernet socket path. Defaults to auto,
which will try to use the existing socket from Docker for Mac.

This flag can be used to connect to the VPNKit instance started by
another linuxkit VM launched with `-start-vpnkit`. VMs connected to the
same VPNKit instance will be on the same virtual internal network.

(related to discussion in #1891)

Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>

### CODE REVIEW

**Comment by MagnusS** [comment]
Hm - not sure why CI failed. Seems to be unrelated:
```
ssh: connect to host 35.189.232.213 port 22: Connection refused
```

**Comment by justincormack** [comment]
This code is a bit confusing, how is the value `auto` actually used? I would expect the default value to be the actual path of the socket...

**Comment by MagnusS** [comment]
@justincormack "auto" is used by the hyperkit API: https://github.com/moby/hyperkit/blob/master/go/hyperkit.go#L134

But I can use the path as the default instead of auto. The HyperKit API just looks for the socket in the standard location anyway.

**Comment by MagnusS** [comment]
Pushed an update which defaults to the DfM standard path

**Pull request merged**
