### PR TITLE
Add s390 console to examples

### PR DESCRIPTION
**Pull request by alicefr**
On z platform, the kernel console is ttysclp0

Signed-off-by: Alice Frosi <alice@linux.vnet.ibm.com>

**- What I did**
I added the s390 console to `examples`

### CODE REVIEW

**Comment by alicefr** [comment]
In the `docker.yml` the image `docker:17.07.0-ce-dind` has not s390 support. Instead, the version `docker:17.09.0-ce-dind` includes s390 support

**Comment by justincormack** [comment]
@alicefr its fine to update the docker example to a later version, it is not intentional it has not been updated.

**Comment by alicefr** [comment]
Ok! Done.

**Comment by rn** [comment]
you just removed the change. A PR can contain multiple commits. Can you create a new commit with the DinD change and push to this PR? Thanks

**Pull request merged**
