### PR TITLE
Adding an AWS example

### PR DESCRIPTION
**Pull request by DieterReuter**
**- What I did**
Adding an AWS example (as clone of the GCP example), refs to: #1918

**- How I did it**
Fixed the GCP example, had to add `binds:` keyword to `sshd` service
Updated the `linuxkit/metadata` to latest version which supports AWS (introduced with #1954)
Simplified `sshd` service, no need to specify the bind mount of /etc/resolv.conf as this is already the default

**- How to verify it**
Just built the raw image and imported it into AWS as snapshot, created an AMI from the snapshot, ran a new EC2 instance and provided my own ssh keys to the instance. Verified that I can login via ssh from the outside network. 

**- Description for the changelog**
Added an AWS example

Signed-off-by: Dieter Reuter <dieter.reuter@me.com>

### CODE REVIEW

**Comment by justincormack** [comment]
We should not have to add the bind mount, if it needs to be there it should be in the image metadata, but I am not sure whats changed as it should not have been needed.

**Comment by DieterReuter** [comment]
The bind mount is already provided as a label/default within the image `linuxkit/sshd`.

**Comment by justincormack** [comment]
@DieterReuter not `/var/config/ssh/authorized_keys:/root/.ssh/authorized_keys` which you added

**Comment by DieterReuter** [comment]
The bind mount `/var/config/ssh/authorized_keys:/root/.ssh/authorized_keys` comes directly from the GCP example. 

But if you'd prefer to use the standard `~/.ssh/authorized_keys` location instead, we should change the storage of the ssh keys in metadata pkg. WDYT?

**Comment by justincormack** [comment]
Not sure need to take a look.

**Comment by DieterReuter** [comment]
I just found some more details. sshd service is looking for additional keys at /etc/ssh with the following search `KEYS=$(find /etc/ssh -name 'ssh_host_*_key')`, but metadata pkg stores the key as `/var/config/ssh/authorized_keys` for both GCP and AWS providers.

**Comment by justincormack** [comment]
Also, as the two examples are identical, not sure we need both...

**Comment by kencochrane** [comment]
They might be identical right now, but maybe not in the future. Also, it might make it easier for newbies to get started, if they see an aws.yml, it is more obvious that it is for aws, vs knowing that the gcp.yml is also good for aws.

**Comment by justincormack** [comment]
ok. We should move them to `blueprints/` soon though.

**Comment by DieterReuter** [comment]
Maybe I could include some other things as well like node_exporter, but my intention is to have a separate AWD example to get easy started for newbies. We should write some small tutorials, I think I'll start with a short blogpost on the weekend.

**Comment by justincormack** [comment]
The plan was to have https://github.com/linuxkit/linuxkit/tree/master/blueprints have really detailed "this is how you might really want to run it" examples, although we may decide this is not how we want to do it.

**Pull request merged**
