### PR TITLE
tools & test use package.mk and build --iidfile

### PR DESCRIPTION
**Pull request by ijc**
**- What I did**

Reworked the builds of `test/pkg/*`  and `tools` to use `package.mk` (where it makes sense / is possible) or if not then to use `build --iidfile`. Also reworked most things to use a multistage build and to use the alpine mirror.

In practice this means everything is switch to `package.mk` except for `tools/guestfs` which is a mirror-like image providing the basis for many of `tools/mkimage-*`.

`tools/mkimage-iso-*` are switched to the `tools/alpine` base, `iso` used use `alpine:3.5` and `efi` used `alpine:edge`. Looking at the timelines I think the current `alpine:3.6` base should be ok for both.

**- How I did it**

Emacs.

**- How to verify it**

Build all the things. In particular all of the images types.

NB: This will not build until content trust is enabled on `linuxkit/guestfs` and I have signed + pushed `linuxkit/guestfs:aecc40bf84ce4f4238e06934c46d7cc570a39eed@sha256:62e810869e83dabe04af7ac8fcd81d9f177d986a3424dcb9c4eb5439993c962f`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
[](https://en.wikipedia.org/wiki/The_VIIth_Coming)

### CODE REVIEW

**Comment by ijc** [comment]
Sigh, needs a rebase already!

I think it might make sense to PR moby/tool with the new hashes here and include that bump at the end of the PR, or in a new PR, thoughts?

**Comment by justincormack** [comment]
I have taken to opening PRs without the hash changes, waiting for review and then updating...

**Comment by ijc** [comment]
Thanks to @riyazdf for enabling content trust I have now pushed `linuxkit/guestfs:aecc40bf84ce4f4238e06934c46d7cc570a39eed@sha256:62e810869e83dabe04af7ac8fcd81d9f177d986a3424dcb9c4eb5439993c962f` and re-kicked CI.

**Comment by ijc** [comment]
Looks like there is a real failure with [linuxkit.packages.containerd](https://github.com/linuxkit/linuxkit-logs/blob/aba4491f02f1fa572a261066a010fa7e2041cae9/value/c2698841-54a6-448b-a8c7-6277a1881ac1/linuxkit.packages.containerd.log):
```
[STDERR ] 2017-07-26T14:34:12.8127479Z: exec: "containerd": executable file not found in $PATH: FAIL github.com/containerd/containerd 0.376s
```

Might be a consequence of the alpine base layer for this test being updated by this PR, when it really ought to be bumped whenever CONTAINERD_COMMIT is. Will investigate.

**Comment by ijc** [comment]
It appears that the container `root-test` target now requires the `containerd` binary to be in the path (so we need wither a `make build` or a bind). But even with that I get:
```
🇩 bin/ctr
🇩 bin/containerd
🇩 bin/containerd-shim
🇩 binaries
🇩 root-test
time="2017-07-26T16:22:51Z" level=info msg="running tests against containerd" revision=036232856fb8f088a844b22f3330bcddb5d44c0a version=v1.0.0-alpha1-71-g03623285 
failed to do request: Head https://registry-1.docker.io/v2/library/alpine/manifests/latest: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:39322->[::1]:53: read: connection refused: time="2017-07-26T16:22:51Z" level=info msg="starting containerd" module=containerd revision=036232856fb8f088a844b22f3330bcddb5d44c0a version=v1.0.0-alpha1-71-g03623285 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." module=containerd type=io.containerd.metadata.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.differ.v1.base-diff"..." module=containerd type=io.containerd.differ.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1 
time="2017-07-26T16:22:51Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/containerd-test/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." module=containerd type=io.containerd.snapshotter.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." module=containerd type=io.containerd.monitor.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1 
time="2017-07-26T16:22:51Z" level=info msg=serving... address="/run/containerd/debug.sock" module="containerd/debug" 
time="2017-07-26T16:22:51Z" level=info msg=serving... address="/run/containerd-test/containerd.sock" module="containerd/grpc" 
time="2017-07-26T16:22:51Z" level=info msg="containerd successfully booted in 0.001660s" module=containerd 
time="2017-07-26T16:22:51Z" level=debug msg="received signal" module=containerd signal=terminated 
time="2017-07-26T16:22:51Z" level=fatal msg="serve failure" address="/run/containerd-test/containerd.sock" error="accept unix /run/containerd-test/containerd.sock: use of closed network connection" module="containerd/grpc" 
FAIL	github.com/containerd/containerd	0.127s

```

So it seems to be requiring network access and hitting the registry, which I'm not sure if we want.

I'm considering marking this test as skip until we can sort this out (one way or another).

/cc @AkihiroSuda

**Comment by ijc** [comment]
I added the skip for now because I want CI to try the various build bits.

**Comment by AkihiroSuda** [comment]
> I'm considering marking this test as skip until we can sort this out (one way or another).
> /cc @AkihiroSuda

SGTM for skipping.

Is there any (security?) issue if enable network?

**Comment by ijc** [comment]
> Is there any (security?) issue if enable network?

I wasn't sure if it was allowed, but looking now I see several tests which do networking and hit hub (including one I wrote :blush:)

**Comment by justincormack** [comment]
Tests using network is fine, although trying to keep network usage to a minimum makes sense...

**Comment by ijc** [comment]
CI green, can we merge this as is and I'll fix and reenable the containerd test as part of the bump to alpha2 I'm planning to do today? Otherwise rebase hell lies in my future...

**Pull request merged**
