### PR TITLE
Include ethtool in linuxkit ip image.

### PR DESCRIPTION
**Pull request by ctalledo**
**- What I did**

Include the ethtool in the Linuxkit "ip" image.

**- How I did it**

Add the "ethtool" package to the ip image Dockerfile.

**- How to verify it**

Generate the ip image, run ethtool from within it.

**- Description for the changelog**

Include the ethtool in the Linuxkit "ip" image; this allows configuring ethernet interfaces using this image.

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by errordeveloper — DISMISSED** [review]

**Comment by ctalledo** [comment]
Hi @errordeveloper, thanks for the tip.

> you need to run scripts/update-component-sha.sh and check the results in also

Got it; I've done that now (i.e., obtained the new tag with: `linuxkit pkg show-tag pkg/ip`, then updated the tag with: `./scripts/update-component-sha.sh --image <new-tag>`).

Let me know if it looks good. Thanks again!

**Comment by ctalledo** [comment]
Hi @errordeveloper, gentle nudge to see if I can get approval for this PR. Thanks!

**Comment by errordeveloper** [comment]
@ctalledo I am happy to sign this off, but don't think my approvals mean much here at the moment.

**Comment by ctalledo** [comment]
> @ctalledo I am happy to sign this off, but don't think my approvals mean much here at the moment.

Oh my apologies, thought you were one of the maintainers. 

@djs55: can you approve this PR please? Thanks.

**Pull request closed without merging**
