### PR TITLE
Update linuxkit kernel to 4.12.9

### PR DESCRIPTION
**Pull request by iamShantanu101**
**- Update linuxkit kernel to 4.12.9**

Updated all linuxkit kernel versions to 4.12.9 from older ones. Also updated the `linuxkit/init` hash in `examples/tpm.yml`

### CODE REVIEW

**Comment by rn** [comment]
@iamShantanu101 Thanks for the PR, but we want the default kernel to be the latest LTS kernel not the latest stable kernel. 4.12 will be EOLed very soon. Also our 4.12 kernel contains some experimental, not yet fully tested patches.

Do you have specific need for the 4.12 kernel?

**Comment by iamShantanu101** [comment]
@rn No specific need. Just gave a thought that why the latest stable kernel was not there. Are you guys going to switch directly on 4.14 LTS when it is released in near future and continue with this kernel till then? Just curious.

**Comment by justincormack** [comment]
We will switch to 4.14 once it seems to be working; we will probably spin off a stable branch that stays on 4.9 as well though before then.

**Comment by rn** [comment]
Closing this PR for the reasons given [here](https://github.com/linuxkit/linuxkit/pull/2481#issuecomment-326982738) and as @justincormack says we'll switch to 4.14 once it is stable, probably wait for a few dot releases before we switch

**Pull request closed without merging**
