### PR TITLE
Update kernel to 4.9.54 and 4.4.91 and tweak build/kernel config

### LINKED ISSUE #2581: add `make firmware_install` to kernel build
Mostly a note to self, that we should include the fimrwarez in the same tarball as the modules.

### LINKED ISSUE #2582: enable KASLR in kernels
requires enabling `RANDOMIZE_BASE`. This should be enabled for x86_64 and arm64 on kernels which support it.

### PR DESCRIPTION
**Pull request by rn**
- Add firmware blobs to initrd (resolves #2581). The FW blobs are added to the modules tarball under `/lib/firmware`. On a x86_64 build this adds about 600KB to the size of the `initrd`.
- Enable KASLR in the arm64 4.9.x/4.13.x kernels. This enables it on all kernels (resolves #2582)
- Update kernels to 4.9.54/4.4.91 (no update to 4.13.x yet)

x86_64 images pushed/signed. arm64 is still building

octo

### CODE REVIEW

**Comment by deitch** [comment]
Cool octopus.. but I hope the following is a typo?

> On a x86_64 build this adds about 600MB to the size of the initrd

600 MB ?

**Comment by rn** [comment]
I hadn't run the 4.13 kernel through config so there was an error when compiling. Force pushed a fix

**Comment by rn** [comment]
yeah, it's 600*KB* not *MB*

**Comment by rn** [comment]
arm64 kernels also now built...just waiting for CI to finish

**Pull request merged**
