### PR TITLE
Use pure Go unix.Reboot function in rc.init

### PR DESCRIPTION
**Pull request by tklauser**
Use unix.Reboot from golang.org/x/sys/unix for poweroff and reboot
instead of relying on external commands.

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by justincormack** [comment]
Thanks, LGTM once CI is happy and we rebuild the container.

**Comment by tklauser** [comment]
Oops, sorry. Now changed, PTAL.

**Comment by rn** [comment]
Thanks for this improvement. I've build, pushed, signed the update packages. Could you update this PR with an *additional* commit to update the YAML files.

Something like this in the root directory should do the trick:
```
scripts/update-component-sha.sh linuxkit/init:9250948d0de494df8a811edb3242b4584057cfe4 linuxkit/init:5a577d070817b4f17821657823082651baafd4ed
```

That way CI will actually test with the update packages.

**Comment by tklauser** [comment]
YAML files now updated and pushed in an additional commit. Sorry for missing this previously and thanks for your help @rn !

**Pull request merged**
