### PR TITLE
Enable sysctl kernel.dmesg_restrict

### PR DESCRIPTION
**Pull request by justincormack**
This requires that users have `CAP_SYSLOG` in order to access `dmesg`.
This means that containers by default have no access to `dmesg` (which
can leak information about the host or other containers) unless they
have this capability added.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

message in a bottle

### CODE REVIEW

**Comment by justincormack** [comment]
Will update hashes shortly.

**Comment by justincormack** [comment]
cc @riyazdf

**Comment by justincormack** [comment]
Added hashes, did arm64 build...

**Comment by justincormack** [comment]
cc @tych0

**Comment by tych0** [comment]
+1, thanks!

**Pull request merged**
