### PR TITLE
fix: #3742 golint requires comments on non-main package for blank import

### PR DESCRIPTION
**Pull request by aoxn**
Signed-off-by: 谢瑶瑶 <yaoyao.xyy@alibaba-inc.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> /assign @AkihiroSuda

/unassign

**Review by djs55 — APPROVED** [review]
LGTM

**Review by rn — APPROVED** [review]

**Comment by rn** [comment]
Thanks. I had spotted this last week as well but hadn't gotten around fixing it.

**Pull request merged**
