### PR TITLE
use updated kernel and correct path in examples/swap.yml

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**- What I did**

Fix `examples/swap.yml` to:

1. Use correct path for `swap.sh`
2. Updated to a more recent kernel version

**- How I did it**

**- How to verify it**

Run.

**- Description for the changelog**

Update kernel in swap.yml example and use correct path to script for onboot container

**- A picture of a cute animal (not mandatory but encouraged)**
koala

### CODE REVIEW

**Comment by justincormack** [comment]
You need to rebase to fix CI I think

**Comment by deitch** [comment]
I thought I did, but I must have just missed it. No worries, I will do it again. In any case, I found another (dumb) issue with `swap.sh` (only came to fore when working on the encrypted, but could be triggered in other cases).

**Comment by deitch** [comment]
Very strange. It is complaining about:

```
time="2017-04-28T14:23:41Z" level=fatal msg="Failed to extract kernel image and tarball: Failed to docker create image linuxkit/kernel:4.9.x: Error: No such image: linuxkit/kernel:4.9.x" 
```

`kernel:4.9.x` was in the _old_ one, not the _new_ one. And there *is* a tag `4.9.x` in the docker hub for `linuxkit/kernel`?

**Comment by justincormack** [comment]
Yes, seems that https://github.com/linuxkit/linuxkit/pull/1734 did fix it though. Its unclear how it got in that state...

**Comment by deitch** [comment]
No idea! :-)

I fixed the other issue, and submitted it as a single commit and signed (to keep Mr. Turtle happy)

**Comment by justincormack** [comment]
Doesnt look like you rebased against the latest master

**Comment by deitch** [comment]
Dang, multiple windows at once. Oops.

**Comment by deitch** [comment]
I think I got it this time.

**Comment by justincormack** [comment]
Well it may work, but I found the bug...

**Comment by deitch** [comment]
The `-gt` one?

**Comment by deitch** [comment]
It occurs to me that this fix means that the hash is changed, so I need to change the example, right?

**Comment by deitch** [comment]
OK, will add to this PR

**Comment by deitch** [comment]
Added.

**Comment by justincormack** [comment]
You don't need to add 4.10.x to get the config changes, they will be in 4.9.x so long as you re-pull (eg `moby build --pull ...`) - unless you need specific 4.10 features?

**Comment by deitch** [comment]
No, I don't, but why not use the latest? Any reason not to use 4.10?

**Comment by justincormack** [comment]
Well its just kind of odd if one example uses 4.10 and the rest don't people will assume it needs 4.10 features. Currently we have not done extensive testing of 4.10 although we plan to soon; it is also going to be EOL shortly as 4.11 is out this weekend...

**Comment by deitch** [comment]
No worries. I will back to 4.9 over the weekend. Hold off on the merge until another push here.

**Comment by justincormack** [comment]
needs a rebase too, sorry

**Comment by deitch** [comment]
Ugh. Oh well.

**Comment by deitch** [comment]
OK, kernel restored to `4.9.x`, need to rebase, though

**Comment by deitch** [comment]
OK, rebased. Used the hash from the fixed build.

**Comment by deitch** [comment]
Ready for approval?

**Comment by justincormack** [comment]
Ah but you havent got push access have you, whats your docker hub id? I can give you push to linuxkit/swap for now

**Comment by deitch** [comment]
Same as my GitHub, https://hub.docker.com/u/deitch/

Hold on a sec on merging this please. Just want to be paranoid and run one more check

**Comment by justincormack** [comment]
Ok, you should be able to push to linuxkit/swap now so you can add that image

**Comment by deitch** [comment]
I copied the Makefile from `pkg/mount`, it has a push which includes the hash. I assume that is good enough?

**Comment by justincormack** [comment]
yes that should work

**Comment by deitch** [comment]
OK, one more paranoid check, then I will push

**Comment by deitch** [comment]
Any plans to break these packages to their own `linuxkit/*` repos?

**Comment by justincormack** [comment]
Maybe, not decided yet, will see what makes sense.

**Comment by deitch** [comment]
I knew there was another issue in `swap.sh`, was hoping to defer to another PR. Even though it is not in current path, it still trips it up. Well, I might as well fix it and squash into this one.

**Comment by deitch** [comment]
Yeah, herestring `<<< $var` is a bash thing, need to convert to heredoc `<<EOF`. A minute or two

**Comment by deitch** [comment]
Fixed, new hash updated as well. Should I wait for next approval to push the image?

**Comment by deitch** [comment]
Image is in https://hub.docker.com/r/linuxkit/swap/

**Pull request merged**
