### PR TITLE
[WIP] Add TPM module builder options to kernel

### PR DESCRIPTION
**Pull request by deitch**
**- What I did**
Added all of the in-tree tpm options to the kernel config

**- How I did it**
1. Run the kernel build container
2. Stop it to get to the build image hash
3. Run the build hash with the `kernel/` dir mounted in
4. Run `make menuconfig`
5. Load in the existing `.config`
6. Add tpm options all is `M` (as in modules)
7. Save config to `.config`
8. Copy config to bind mounted dir
9. Exit container
10. Compare the config with the original config, fix any errors (mainly `HYPERV_SOCK` missing)
11. Copy over to appropriate `kernel.config-*` and build

**- How to verify it**
1. Build a kernel. 
2. Run on a virtual machine (e.g. hyperkit) without tpm, see it works, no impact, modules not loaded
3. Run on a machine with tpm (virtual or physical):
    * see modules are loaded
    * check that `/dev/tpm0` is created
    * check that `/sys/class/tpm/...` is properly populated with device info
    * check that `../pcrs` has actual information
    * check that `tcsd` can start and can get `tpm_version`

**- Description for the changelog**

Add support via kernel modules for in-tree tpm drivers

**- A picture of a cute animal (not mandatory but encouraged)**
mongoose

As discussed with @justincormack and @rn.

**Note:** This is still WIP. The current PR only includes changes for 4.9.x series kernel. Working on 4.11.x

### CODE REVIEW

**Comment by rn** [comment]
thanks, this looks ok to me. Happy to merge and recompile/push kernels once this is also done for 4.11.  I think we can ignore 4.4 for now as no-one seems to be actively using it and we just keep it around because it's still alive

**Comment by deitch** [comment]
No 4.4? Excellent!

Hoping to get 4.11 done tomorrow.

**Comment by rn** [comment]
well, I haven't added to additional hardware support for network cards and the like to 4.4 either...

**Comment by justincormack** [comment]
Only 7 months of 4.4 support left, can't imagine anyone is going to build something new on it.

**Comment by riyazdf** [comment]
@deitch 🎉  this is awesome, looks good so far

**Comment by deitch** [comment]
* Updated for 4.11.x
* Not doing 4.4.x per @rn (thank you)

Ran same tests with 4.11.x kernel. On hyperkit, system without tpm (or with it disabled in bios), runs as expected, no kernel modules loaded. On system with tpm, runs as expected, `/dev/tpm0` created, `/sys/class/tpm/tpm0/` entries as expected, and can read `pcrs/` with correct values. Also was able to get trousers to work.

**Comment by deitch** [comment]
What is the process for this now? With `pkg/`, it usually is:

1. Someone approves, says "LGTM"
2. I do a `make tag` to get the image out with its hash
3. We merge in

With the kernel, there is no `make tag`, but rather `make push`. More importantly, in addition to the hashed image, e.g. `4.9.36-abcd5566aff`, it updates the semver `4.9.36`. What is the deployment process for new kernel images with existing versions?

**Comment by deitch** [comment]
Quite welcome. I was surprised at how little work the change itself was... and how much work it took to get it set up to run `menuconfig` (well, _before_ you walked me through it and hence documented), and even more to test it. But all good!

Would you please comment here (or @ tag me on Slack) when it is pushed so. I can start to build upon it?

**Comment by rn** [comment]
all kernels compiled, pushed and signed

**Comment by deitch** [comment]
I realized I never removed the `[WIP]` from the title. A bit late, but might as well clean it up.

**Pull request merged**
