### PR TITLE
Adds new LTS kernel 5.10.x

### PR DESCRIPTION
**Pull request by thebsdbox**
**- What I did**
Added the LTS 5.10.x branch of the Linux Kernel

**- How I did it**
Updated the Makefile and kernel configuration

**- How to verify it**
Move to the kernel folder and `make build_5.10.x`

**- Description for the changelog**
Added the LTS 5.10.x branch of the Linux Kernel

image

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thebsdbox** [comment]
```
Step 33/34 : COPY --from=kernel-build /out/* /
 ---> bc852afe9a6a
Step 34/34 : LABEL org.opencontainers.image.source=https://github.com/linuxkit/linuxkit
 ---> Running in c82da68f276f
Removing intermediate container c82da68f276f
 ---> 25b1617711b0
Successfully built 25b1617711b0
Successfully tagged linuxkit/kernel:5.10.11-f39f83d0d475b274938c86eaa796022bfc7063d2-dirty-amd64
```

^ Output from build.

**Review by djs55 — APPROVED** [review]
LGTM!

I tested by replacing the kernel in my Docker Desktop and it worked fine:
```
PS C:\Users\dave> docker run alpine uname -a
Linux 08595583f011 5.10.11-linuxkit #1 SMP Sun Feb 14 14:22:47 UTC 2021 x86_64 Linux
```

**Comment by djs55** [comment]
I guess we'll still need a `config-5.10.x-{s390x,aarch64}`. Perhaps those can be added separately?

**Comment by thebsdbox** [comment]
I can add such configurations (based upon previous kernel version on those architectures) but unfortunately i'm unable to test them so they may be broken.

**Comment by djs55** [comment]
@rn (sorry for the ping!) is there anything I can do to help out with the kernel efforts? I'm keen to move Desktop forward into the future :) and would rather collaborate here than build my own custom one. Let me know what you think!

**Comment by rn** [comment]
I've lost signing powers (no idea how that happened) so currently can't build/push/sign packages...I have tried to regain the powers a few times the past couple of weeks to no avail so far...

**Comment by thebsdbox** [comment]
In the interim, another commiter has added arm support to the the PR :-D

**Review by djs55 — APPROVED** [review]
Seems to work for me!
```
% docker run alpine uname -a
Linux 39d3c5173d40 5.10.11-linuxkit #1 SMP PREEMPT Thu Mar 4 16:51:44 UTC 2021 aarch64 Linux
```

**Pull request closed without merging**
