### PR TITLE
Upgrade to go 1.19

### PR DESCRIPTION
**Pull request by dgageot**
Signed-off-by: David Gageot <david.gageot@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like it's failing to install `golint`

```bash
go get -u golang.org/x/lint/golint
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

However, it's deprecated, so I'm not sure if it should even be used (see https://github.com/golang/lint). Perhaps better if we would use golangci-lint with some good linters enabled.

**Comment by deitch** [comment]
Yeah we should. I've switched to golangci-lint pretty much everywhere.

**Comment by deitch** [comment]
I have an open PR #3849 to add modern golangci-lint. But I am going to wait until your cleanup changes are in @dgageot in the various PRs before I merge it, since it raises a lot of the same issues.

**Comment by deitch** [comment]
Once #3849 is clean and in, you should be able to rebase this and get good results.

**Pull request closed without merging**
