### PR TITLE
docs: Add a section on custom kernel builds

### LINKED ISSUE #1835: Build  my own kernel
**Description**
When I rebuild the kernel under /kernel with the modified kernel_config-4.11.x and moby rebuild linuxkit.yml. After it  I run 'linuxkit run linuxkit". But the kernel is not modified. So Is it a wrong situation?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

### PR DESCRIPTION
**Pull request by rneugeba**
fixes #1835

Signed-off-by: Rolf Neugebauer <rolf.neugebauer@docker.com>

### CODE REVIEW

**Comment by yankunsam** [comment]
The new issues:

sam-machinedeMacBook-Pro:kernel sam$ make build_4.9.x  HASH=ima
docker pull linuxkit/kernel:4.9.27-ima || docker build --build-arg KERNEL_VERSION=4.9.27 --build-arg KERNEL_SERIES=4.9.x --build-arg DEBUG= --no-cache -t linuxkit/kernel:4.9.27-ima .
Error response from daemon: manifest for linuxkit/kernel:4.9.27-ima not found
Sending build context to Docker daemon 982.5 kB
Step 1/24 : FROM linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b AS kernel-build
Error parsing reference: "linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b AS kernel-build" is not a valid repository/tag: invalid reference format
make: *** [build_4.9.x] Error 1
sam-machinedeMacBook-Pro:kernel sam$


So where is the changing?

Thanks!

**Comment by rneugeba** [comment]
can you do a `docker pull linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b`?

**Comment by yankunsam** [comment]
Yes. I can. But the error is before it.

"Error response from daemon: manifest for linuxkit/kernel:4.9.27-ima not found"

**Comment by rneugeba** [comment]
that's because there is no image called `linuxkit/kernel:4.9.27-ima`. Is this your own kernel? If so you should overwrite the hub org using `make ... ORG=<foo>` to store the image elsewhere

**Comment by yankunsam** [comment]
Yes.  I run like this "make build_4.9.x HASH=ima" Where is the reason?

**Comment by rneugeba** [comment]
`Error response from daemon: manifest for linuxkit/kernel:4.9.27-ima not found` is expected, because the Makefile tries to pull the image and it is not there. It should then proceeds to build the image. the error which aborts the make is :`is not a valid repository/tag: invalid reference format`.

did you modify the files in any form? the above works for me(tm)

**Comment by yankunsam** [comment]
I have tried in the new directory , but there is the same error.

**Comment by yankunsam** [comment]
As the "ORG", did it says that  linuxkit does not allow **local** kernel image  now?

**Comment by rneugeba** [comment]
it does allow local images

**Comment by rneugeba** [comment]
but your error/problem is an error when executing the docker file which has nothing to do with organisations etc. 

can you do a docker run with the compile image by executing /bin/sh or something?

**Comment by yankunsam** [comment]
Yes. Here is the output messages:

sam-machinedeMacBook-Pro:kernel sam$ docker run -it ubuntu bash
root@70e09422a0a9:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@70e09422a0a9:/#

**Comment by yankunsam** [comment]
in the kernel/Makefile:

docker pull $(ORG)/$(IMAGE):$(1)$(3)-$(HASH)

So "ORG" must been a valid , not for local image?

**Comment by yankunsam** [comment]
sam-machinedeMacBook-Pro:kernel sam$ make build_4.9.x ORG=linuxkit
docker pull linuxkit/kernel:4.9.29-ima || docker build --build-arg KERNEL_VERSION=4.9.29 --build-arg KERNEL_SERIES=4.9.x --build-arg DEBUG= --no-cache -t linuxkit/kernel:4.9.29-ima .
Error response from daemon: manifest for linuxkit/kernel:4.9.29-ima not found
Sending build context to Docker daemon 986.6 kB
Step 1/24 : FROM linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b AS kernel-build
Error parsing reference: "linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b AS kernel-build" is not a valid repository/tag: invalid reference format
make: *** [build_4.9.x] Error 1
sam-machinedeMacBook-Pro:kernel sam$ make build_4.9.x
docker pull linuxkit/kernel:4.9.29-ima || docker build --build-arg KERNEL_VERSION=4.9.29 --build-arg KERNEL_SERIES=4.9.x --build-arg DEBUG= --no-cache -t linuxkit/kernel:4.9.29-ima .
^Cmake: *** [build_4.9.x] Interrupt: 2

sam-machinedeMacBook-Pro:kernel sam$


why there is "AS kernel build" when use "ORG" ?

**Comment by rneugeba** [comment]
no, I was suggesting to try:
```
docker run --rm -ti "linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b /bin/sh
```
the `AS` line is for multi-stage builds

ORG is set in the makefile with `ORG?=linuxkit` but local images can be called whatever, you just can't push them

**Comment by yankunsam** [comment]
Thanks. Here is the output message:

sam-machinedeMacBook-Pro:kernel sam$ docker run --rm -ti "linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b /bin/sh
>

I do not know why ?

**Comment by yankunsam** [comment]
Sorry for that.

sam-machinedeMacBook-Pro:kernel sam$ docker run --rm -ti "linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b"  /bin/sh
Unable to find image 'linuxkit/kernel-compile@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b' locally
sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b: Pulling from linuxkit/kernel-compile
627beaf3eaaf: Already exists
26dc4067def6: Pull complete
Digest: sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b
Status: Downloaded newer image for linuxkit/kernel-compile@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b
/ # ls
bin    dev    etc    home   lib    media  mnt    proc   root   run    sbin   srv    sys    tmp    usr    var
/ #

**Comment by rneugeba** [comment]
I thought you already did a pull but it looks like it needed pulling...does the kernel build make now work?

The error does not seem to be related to the makefile and how kernels are build. if the above does not work could you try a doing a reset of  docker for mac?

**Comment by yankunsam** [comment]
I have resetted the docker, but the same error. Can you show me the right process in your machine?

Thanks!

**Comment by rneugeba** [comment]
the make just works for me, and probably for others too. It also works on a linux machine

just remembered you need docker 17.05 for all of the packages. if you are not on that version you should upgrade

**Comment by yankunsam** [comment]
Are you sure you have changed the ORG=xxx, not linuxkit?

**Comment by rneugeba** [comment]
- The Makefile is pretty simple and straight forward and I've used it to both override the ORG and the HASH
- The error you get is not related to the ORG or HASH, but it's on the first line of the Dockerfile
- Have you checked your docker version as I suggested in my last comment?

**Comment by yankunsam** [comment]
Here is my advice
ori:
FROM linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b AS kernel-build

now:
FROM linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b@sha256:6b32d205bfc6407568324337b707d195d027328dbfec554428ea93e7b0a8299b

Maybe I will push a patch for custom kernel building.

I have used the latest version. You mean "uppercase" for 17.05?

**Comment by rneugeba** [comment]
No, the `AS kernel-build` is correct. which docker version do you have?

**Comment by yankunsam** [comment]
sam-machinedeMacBook-Pro:kernel sam$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
sam-machinedeMacBook-Pro:kernel sam$


I think there should be a compatibility for docker.

**Comment by rneugeba** [comment]
as I said, you need 17.05. You are on 17.03. The kernel build (and pretty much everything else in LinuxKit) is using features only present 17.05

**Comment by yankunsam** [comment]
I try 17.05 for mac. It works. But it is "edge".  Thanks so much. 👍

**Pull request merged**
