### PR TITLE
add vultr example

### PR DESCRIPTION
**Pull request by riyazdf**
cc @furious-luke: could you please validate this `vultr.yml`?  I'm not too familiar with vultr and will try to do so myself as well.

### CODE REVIEW

**Comment by furious-luke** [comment]
@riyazdf Unfortunately, it seems that ISOs built from moby are now not able to launch on Vultr. I had an ISO built from about a week ago that was working, but after rebuilding from the latest linuxkit/moby the ISO produced is not recognised by Vultr. So, I'm afraid I can't test this PR at the moment. I'll try debugging some more and see if I can figure out why this has happened, but I'm afraid there is very little information to go on from Vultr's end, so it's a lot of guesswork. :/

**Comment by furious-luke** [comment]
So, the ISO that I built from `examples/vultr.yml` didn't seem to work (not recognised by Vultr). However, when I merged your PR into `master` locally and rebuilt the ISO I've been using with Vultr previously it worked just fine. I can't say why it is that the examples YAML file didn't work, but the metadata changes are working as expected.

**Comment by riyazdf** [comment]
Interesting - would you mind sharing the yaml file that works for you on Vultr?  I can update this PR to converge with that image.

**Comment by furious-luke** [comment]
Sure thing, I've included it below. The `bootstrap` image is just something to prepare the Vultr attached disk, it don't think it would affect whether or not Vultr recognises the ISO.

I've also lodged a ticket with Vultr to try and get some more details, I'll keep you posted.

```yaml
kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:17693d233dd009b2a3a8d23673cb85969e1dce80
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:a33cdcf50b8107ffe14c92802c460fe7ada39acd
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
  - name: sysfs
    image: "linuxkit/sysfs:1244c5a86dfa2318c4e304af68d37e12367e1b7f"
  - name: binfmt
    image: "linuxkit/binfmt:8ac5535f57f0c6f5fe88317b9d22a7677093c765"
  - name: format
    image: "linuxkit/format:180cb2dc1de5e60373385080f8148abf10a3afac"
  - name: mount
    image: "linuxkit/mount:ff5338822f20375b8913f5a80f9ed4f6ea9a592b"
    command: ["/mount.sh", "/var/disk"]
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2b8aaaf20c24ad7d11a5ea2ea5b4a80dc966f1"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: "linuxkit/metadata:9a614b312a8d507acacc6905267c5c43589c2f01"
  - name: bootstrap
    image: "test/bootstrap"
    capabilities:
     - all
    command: ["/bootstrap.sh", "/var/disk"]
    binds:
     - /var/config:/var/config
     - /var/disk:/var/disk
     - /root:/root
     - /etc/docker:/etc/docker
     - /var/run:/var/run
     - /lib/modules:/lib/modules
services:
  - name: getty
    image: "linuxkit/getty:d0765e0a14733f9454010ac109a7c846a4e67fc5"
    env:
     - INSECURE=true
  - name: rngd
    image: "linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31"
  - name: ntpd
    image: "linuxkit/openntpd:45deeb05f736162d941c9bf494983f655ab80aa5"
  - name: docker
    image: "linuxkit/docker-ce:dda71ff9fe5ebbfa794b98c57c32df286b212848"
    capabilities:
     - all
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/disk/var/lib/docker:/var/lib/docker
     - /var/disk/etc/docker/daemon.json:/etc/docker/daemon.json
     - /var/disk/root/.docker:/root/.docker
     - /lib/modules:/lib/modules
files:
  - path: etc/docker/daemon.json
    source: deploy/daemon.json
  - path: root/.docker/ca.pem
    source: var/keys/ca.pem
  - path: root/.docker/ca-key.pem
    source: var/keys/ca-key.pem
# trust:
#   org:
#     - linuxkit
```

**Comment by justincormack** [comment]
Odd. There have not been any changes in ISO generation recently. I have found providers have all sorts of not very good checks that are hard to debug. Possibly size related?

**Comment by furious-luke** [comment]
Vultr got back to me, they said there was a temporary issue in their system regarding copying ISOs from their storage to the servers. After trying again the example Vultr file works and the metadata looks good.

**Comment by riyazdf** [comment]
@furious-luke ok great! Just rebased and updated.

**Comment by justincormack** [comment]
@riyazdf I think some hashes have been updated since this, can you check?

**Comment by riyazdf** [comment]
@justincormack: thanks, updated hashes for essentially everything except `linuxkit/sysctl` and `linuxkit/metadata`

**Pull request merged**
