### PR TITLE
flag in init and background only if not in init

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**- What I did**

1. Add `INITGETTY=true` env var when running from `/etc/init.d/001-getty`
2. Only `wait` in `rungetty` if `INITGETTY` is true

`wait` was causing onboot to block. See [this](https://github.com/linuxkit/linuxkit/pull/2233#discussion_r127970030)

**- How I did it**
Typed

**- How to verify it**
Run in `services` and in `init`. Ensure everything starts when in `init`.

**- Description for the changelog**

Remove block of `init` when getty is in `init` mode.

**- A picture of a cute animal (not mandatory but encouraged)**
squid

No, a squid is _not_ cute, but it is the first animal that came to mind.

### CODE REVIEW

**Comment by deitch** [comment]
Pushing out hashed image for CI...

**Comment by deitch** [comment]
Shoot. I need to update all of the examples first, right?

**Comment by deitch** [comment]
I am trying to follow the new process.

1. Got LGTM
2. pushing out tagged
3. adding commit for examples changed

**Comment by deitch** [comment]
Tagged and pushed.

Used script to change the examples, projects, etc. and pushed as separate commit.

Is that right?

**Comment by deitch** [comment]
Just waiting for CI to clear.

**Comment by deitch** [comment]
Should CI be taking this long?

**Comment by justincormack** [comment]
It claims to have only started 11 minutes ago...

**Comment by rn** [comment]
there are quite a few PRs on the fly and the limit is max of 4 PRs in
parallel

**Comment by justincormack** [comment]
We could increase that number...

**Comment by dave-tucker** [comment]
Done in https://github.com/linuxkit/linuxkit-ci/pull/24
It won't come in to effect until CI is redeployed

**Comment by deitch** [comment]
Nice if this ever ends up on green... :-) CI

**Comment by deitch** [comment]
Finally passed CI. Everyone approved, so merging in.

**Pull request merged**
