### PR TITLE
Kernel update to 4.13.12/4.9.61/4.4.97 + disable CMA on arm64

### LINKED ISSUE #2434: Networking on Cavium Thunder is not quite working (4.9.x kernel)
On the Cavium Thunder machines on packet.net, the `netpf` driver get's loaded and 12 VFs are created:
```
[   29.097586] thunder-xcv, ver 1.0
[   29.101749] thunder-BGX, ver 1.0
[   29.105096] thunder-BGX 0000:01:10.0: BGX0 QLM mode: XFI
[   29.111556] thunder-nic, ver 1.0
[   29.220007] pci 0002:01:00.1: [177d:a034] type 00 class 0x020000
[   29.220318] pci 0002:01:00.2: [177d:a034] type 00 class 0x020000
[   29.220619] pci 0002:01:00.3: [177d:a034] type 00 class 0x020000
[   29.220953] pci 0002:01:00.4: [177d:a034] type 00 class 0x020000
[   29.221308] pci 0002:01:00.5: [177d:a034] type 00 class 0x020000
[   29.221699] pci 0002:01:00.6: [177d:a034] type 00 class 0x020000
[   29.222078] pci 0002:01:00.7: [177d:a034] type 00 class 0x020000
[   29.222424] pci 0002:01:01.0: [177d:a034] type 00 class 0x020000
[   29.222816] pci 0002:01:01.1: [177d:a034] type 00 class 0x020000
[   29.223267] pci 0002:01:01.2: [177d:a034] type 00 class 0x020000
[   29.223626] pci 0002:01:01.3: [177d:a034] type 00 class 0x020000
[   29.223994] pci 0002:01:01.4: [177d:a034] type 00 class 0x020000
[   29.224360] thunder-nic 0002:01:00.0: SRIOV enabled, number of VF available 12
[   29.231875] thunder-nic 0006:01:00.0: Request for #10 msix vectors failed, returned -12
[   29.239908] thunder-nic: probe of 0006:01:00.0 failed with error -12
```
Note, `0002:01:00.0` is the PF and `0002:01:00.X` are the VFs. `mdev` loads the PF driver fine, but for some reason the VF driver is not loaded. If I manually insert the VF driver:
```
% insmod /proc/1/root/lib/modules/4.9.43-linuxkit/kernel/drivers/net/ethernet/cavium/thunder/nicvf.ko
[  711.013689] thunder-nicvf, ver 1.0
[  711.017432] thunder-nicvf 0002:01:00.1: enabling device (0004 -> 0006)
[  711.065282] thunder-nicvf 0002:01:00.2: enabling device (0004 -> 0006)
[  711.113234] thunder-nicvf 0002:01:00.3: enabling device (0004 -> 0006)
[  711.160027] thunder-nicvf 0002:01:00.4: enabling device (0004 -> 0006)
[  711.204027] thunder-nicvf 0002:01:00.5: enabling device (0004 -> 0006)
[  711.248027] thunder-nicvf 0002:01:00.6: enabling device (0004 -> 0006)
[  711.292027] thunder-nicvf 0002:01:00.7: enabling device (0004 -> 0006)
[  711.336029] thunder-nicvf 0002:01:01.0: enabling device (0004 -> 0006)
[  711.380029] thunder-nicvf 0002:01:01.1: enabling device (0004 -> 0006)
[  711.424026] thunder-nicvf 0002:01:01.2: enabling device (0004 -> 0006)
[  711.468024] thunder-nicvf 0002:01:01.3: enabling device (0004 -> 0006)
[  711.512025] thunder-nicvf 0002:01:01.4: enabling device (0004 -> 0006)
```
and `eth0` and `eth1` appear.

However, when I try to "up" the device, I get:
```
[  906.451032] thunder-nicvf 0002:01:00.1 eth0: Failed to alloc/config VF's QSet resources
```

I'm not entirely sure if the error from PCI device `0006:01:00.0` of not being able to allocate MSI-X vectors is related...
```
0002:01:00.0 Ethernet controller: Cavium, Inc. THUNDERX Network Interface Controller (rev 09)
0006:01:00.0 Ethernet controller: Cavium, Inc. THUNDERX Network Interface Controller (rev 09)
```
`0006:01:00.0` seems to be the second ethernet controller...

### PR DESCRIPTION
**Pull request by rn**
This is the weekly kernel update plus a change in kernel config for arm64.

We disable the Contiguous Memory Allocator (CMA) (it's not enabled on x86_64). It appears that the default memory size for it is too small and causes issues with the Cavium Thunder X network device driver (see @scott400 comment [here](https://github.com/linuxkit/linuxkit/issues/2434#issuecomment-342370982)). We could have increased the default size or, as done here, disable CMA altogether. I've tested the kernel with CMA disabled on both Cavium Thunder X and a Raspberry Pi 3 without issues.

With CMA disabled, we still need to manually `modprobe` the NIC driver on  Cavium Thunder X to get networking going, so the documentation was updated accordingly.
resolves #2434

hare-grass

### CODE REVIEW

**Comment by rn** [comment]
The x86_64 kernels are already pushed, the arm64 kernels are still building.

**Comment by justincormack** [comment]
Weird that circleci has suddenly decided some crypto code is broken

**Comment by rn** [comment]
LinuxKit CI fails on the same thing...hmmm

**Comment by rn** [comment]
Ah, I think my mechanical update of the YAML files updated a vendored file. Fixing

**Comment by rn** [comment]
@ijc or @justincormack Could I get a review on this? I started working on 4.14 support and while it shouldn't conflict it touches some shared files.

**Pull request merged**
