### PR TITLE
openntpd: the "-s" flag is obsolete, this generates some error messages in the ntpd logs

### PR DESCRIPTION
**Pull request by sprat**
**- What I did**

Removed the "-s" flag in the ntpd command-line because the flag is obsolete and generate some error messages in the ntpd logs

**- How I did it**

Typed the backspace key

**- How to verify it**

Check the CI

**- Description for the changelog**

Removed the "-s" flag in openntpd package, because this flag is obsolete

**- A picture of a cute animal (not mandatory but encouraged)**

https://cdn.radiofrance.fr/s3/cruiser-production/2014/03/ea065e11-ac5b-11e3-907f-782bcb6744eb/640_marmotte-cc-benjamine92.jpg

### CODE REVIEW

**Comment by sprat** [comment]
The CI pipelines are red but I think it's some false positive

**Comment by djs55** [comment]
The CI needs some work, see https://github.com/linuxkit/linuxkit/issues/3749 . The current system requires the new packages to be built and pushed (by a maintainer) and then the pinned shas in the tests updated. I'll take a look!

**Comment by djs55** [comment]
I've pushed the package and hit the re-run button in the CI.

**Comment by deitch** [comment]
And all of CI is green now.

**Review by deitch — APPROVED** [review]

**Pull request merged**
