### PR TITLE
fix that docker.yml wasn't working correctly

### PR DESCRIPTION
**Pull request by proelbtn**
**- What I did**

fix that docker.yml wasn't working correctly

**- How I did it**

add the configs to make directory before docker container running.

**- How to verify it**

1. build original docker.yml, and run it. ensure that 

**- Description for the changelog**

I wanted to try moby and linuxkit, so I downloaded example/docker.yml, built it, and ran it with linuxkit.
but I can't execure /bin/sh on docker in my environment. I looked for the cause, so I found following logs.

```
FATA[0000] failed to create task                         error="rpc error: code = Unknown desc = runtime create failed: OCI runtime create failed: container_linux.go:265: starting container process caused \"process_linux.go:348: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/var/lib/docker\\\\\\\" to rootfs \\\\\\\"/containers/services/docker/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker\\\\\\\" caused \\\\\\\"stat /var/lib/docker: no such file or directory\\\\\\\"\\\"\"" service=docker
 - 004-mount
```

It seems to occur that /var/lib/docker is missing, so I added the configs.

Here are some infomations for my environment.

```
(ns: getty) linuxkit-525400123456:~# ctr version
Client:
  Version: 3455ffc0
  Revision: 3455ffc08c553db0ca9fe60b4ba2b3e8a2dc960b

Server:
  Version: 3455ffc0
  Revision: 3455ffc08c553db0ca9fe60b4ba2b3e8a2dc960b
(ns: getty) linuxkit-525400123456:~# ctr tasks list
TASK      PID    STATUS    
dhcpcd    415    RUNNING
getty     547    RUNNING
ntpd      605    RUNNING
rngd      658    STOPPED
(ns: getty) linuxkit-525400123456:~# ctr containers list
CONTAINER    IMAGE    RUNTIME                           LABELS    
dhcpcd       -        io.containerd.runtime.v1.linux    -         
docker       -        io.containerd.runtime.v1.linux    -         
getty        -        io.containerd.runtime.v1.linux    -         
ntpd         -        io.containerd.runtime.v1.linux    -         
rngd         -        io.containerd.runtime.v1.linux    -
```

**- A picture of a cute animal (not mandatory but encouraged)**

I look for my google photos, but I don't have it. :<

### CODE REVIEW

**Comment by justincormack** [comment]
Can you rebase? Should fix the CI failure.

**Comment by proelbtn** [comment]
sorry, but I only modified example/docker.yml. I try to build my new docker.yml and it succeed.
so I have no idea that I should fix... :<

**Comment by justincormack** [comment]
The failure was unrelated, just doing
git fetch upstream
git rebase upstream master
And force pushing should fix it

On 16 Jul 2017 1:28 am, "Ryoga" <notifications@github.com> wrote:

sorry, but I only modified example/docker.yml. I try to build my new
docker.yml and it succeed.
so I have no idea that I should fix... :<

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/pull/2218#issuecomment-315572672>,
or mute
the thread

**Comment by proelbtn** [comment]
sorry, because of my mistakes, I closed this pull request, so I reopened.

**Pull request merged**
