### PR TITLE
Test dev existence getty

### LINKED ISSUE #2362: getty runs on non existing devices
We added `ttyAMA0` to some of the examples, and the getty container is helplfully running  `/sbin/agetty -a root -L 115200 ttyAMA0 vt100` - we should test if the device exists first...

### PR DESCRIPTION
**Pull request by deitch**
**- What I did**
test that a given tty is a character device before trying to open getty on it.

Closes #2362 

**- How I did it**
```sh
	if [ ! -c /dev/$tty ]; then
		echo "getty: cmdline has console=$tty but /dev/$tty is not a character device; not starting getty for $tty" | tee /dev/console
		return
	fi
```

**- How to verify it**
Run it with a mixture of `console=` options that are and are not character devices and see that:

1. It starts for all char devices
2. It does _not_ start for missing or non-char devices
3. It puts an error message on console and in the log file that it is not starting it for that tty

**- Description for the changelog**

Only start getty for valid char-device ttys

**- A picture of a cute animal (not mandatory but encouraged)**
hammerhead

### CODE REVIEW

**Comment by deitch** [comment]
BTW, I thought about `-e` instead of `-c` to check if it exists, but realized that some builds seem to create files that are not char devices (e.g. my `moby build linuxkit.yml` has a `/dev/ttyAMA0` but it obviously is not a character device.

**Comment by rn** [comment]
looks like the updated getty has not been pushed.

**Comment by deitch** [comment]
@rn nope it hasn't. I was still thinking the "LGTM" then push, but yeah, should push it out. I will push out x86_64 and arm64 a little later today. And then the manifest-tool.

**Comment by rn** [comment]
I think the best to get LGTM before pushing is to do a PR without updating hashes (and not this in the PR) and then push another commit later with the hash updates. At least that's what Justin tends to do.

Instructions for how to push packages these days are in `./docs/packages.md`

**Comment by deitch** [comment]
OK.

**Comment by deitch** [comment]
I got it built and pushed on amd64, no problem.

Then went to do it on the arm64 machine, and the fun begins.

OK, new machine, need to set up ssh keys and add to github, `docker login` (with same credentials.. at least GitHub supports multiple keys; registry security and processes _desperately_ need cleanup).

Clone the repo, `make`. All is good until push. 

```
no valid signing keys for delegation roles
```

Ah, yes, need to set up notary and signing properly for a new location (other than my default laptop). The [docs](https://github.com/linuxkit/linuxkit/blob/master/docs/signing.md) have only three sections:

1. How to set up a new repo - not relevant, since this is an existing repo
2. Add maintainers to delegation roles - not relevant (if I understood it correctly), since I already _am_ delegated to (as I pushed from my `amd64`).
3. Import private keys into docker storage  - not relevant, since I don't have the right key here

Stumped. What are the steps I need to take to be able to sign on a new box (whether this new arm64 or just if I have another laptop) just like my existing one?

With ssh it was easy: 

1. `genkeypair`
2. import the public key to github
3. Nothing else

@riyazdf do you know what I need to do here?

**Comment by justincormack** [comment]
I think the key you need to copy is in `~/.docker/trust/`

**Comment by justincormack** [comment]
Or you can generate a new key for that machine and give it to @riyazdf to add

**Comment by justincormack** [comment]
LGTM

**Comment by deitch** [comment]
> generate a new key for that machine

That makes sense, but I do not recall how to do that. @riyazdf walked me through setting it up the first time (and I drove him a little crazy over 30+ mins of Slack to explain all of the parts). Is it documented anywhere?

**Comment by justincormack** [comment]
@deitch see https://docs.docker.com/engine/security/trust/trust_delegation/#generating-delegation-keys

**Comment by deitch** [comment]
Thanks @justincormack . So just RSA key and self-signed cert, and send off to Riyaz? OK, sending now...

**Comment by riyazdf** [comment]
@deitch - thanks for sending me your key, I've added it to this repo and the others! (the administration parts of the documentation are for what I just did to add your key)

>  (and I drove him a little crazy over 30+ mins of Slack to explain all of the parts)

On the contrary, it was a great feedback session!  Happy to discuss Notary/TUF anytime :)

**Comment by deitch** [comment]
OK, finally got this done amd64 and arm64, and manifest-tool for both. `manifest-tool inspect` shows both.

I am going to kick off CI again.

**Comment by deitch** [comment]
OK, I will give. 9 test failed CI? 

```
[+ 17m 35s] [FAIL    ] linuxkit.build.examples.minimal 9.25s
[+ 18m 11s] [FAIL    ] linuxkit.build.examples.docker 35.49s
[+ 18m 26s] [FAIL    ] linuxkit.build.examples.sshd 14.90s
[+ 18m 34s] [FAIL    ] linuxkit.build.examples.redis 8.03s
[+ 18m 53s] [FAIL    ] linuxkit.build.examples.swap 19.16s
[+ 19m 00s] [FAIL    ] linuxkit.build.examples.node_exporter 6.93s
[+ 19m 20s] [FAIL    ] linuxkit.build.examples.tpm 20.55s
[+ 20m 04s] [FAIL    ] linuxkit.build.blueprints.docker_for_mac 43.48s
[+ 30m 11s] [FAIL    ] linuxkit.packages.getty-containerd 15.64s
```

What am I missing here?

**Comment by justincormack** [comment]
`Failed to create OCI spec for linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec: Trusted pull for linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec failed: No trust data for 797cb79e0a229fcd16ebf44a0da74bcec03968ec`

You can get the full logs from the link at the top of the log output, in this case https://github.com/linuxkit/linuxkit-logs/commit/a1a04a8bf99b2fcd035cf15b112c20b12c6fa9f1

**Comment by deitch** [comment]
> You can get the full logs from the link at the top of the log output

Good to know, thanks.

> Trusted pull for linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec failed: No trust data for 797cb79e0a229fcd16ebf44a0da74bcec03968ec

Huh. But the trusted push succeeded (at least on amd64; we had issues on arm64 but @riyazdf showed that it had succeeded).

So trying to pull them with trust, I get:

```
$ DOCKER_CONTENT_TRUST=1 docker pull linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec-amd64
Pull (1 of 1): linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec-amd64@sha256:560cc5f11ed28ac2432906355414a210ae31c8a23c0b752c913cd407e85a0e1c

$ DOCKER_CONTENT_TRUST=1 docker pull linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec-arm64
Pull (1 of 1): linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec-arm64@sha256:9bed0c3163070d8a73b86c5bbf157307a0e20d0561882876ab6e23c85232eb17
```

arm64 and amd64 pull ok. But:

```
$ DOCKER_CONTENT_TRUST=1 docker pull linuxkit/getty:797cb79e0a229fcd16ebf44a0da74bcec03968ec
No trust data for 797cb79e0a229fcd16ebf44a0da74bcec03968ec
```

So `manifest-tool` failed? How do I fix that?

**Comment by deitch** [comment]
@riyazdf fixed it. Restarting CI

**Comment by justincormack** [comment]
Thats weird. Not sure whats the best way to debug - @rn any idea?

**Comment by rn** [comment]
I suspect it may be a similar issue to what @ijc saw earlier today (discussed on slack). but without full command output I can't tell

**Comment by deitch** [comment]
@riyazdf and I spoke about it. I had a weird output in arm64. I will send it to you on Slack.

**Comment by rn** [comment]
looks like the signing key passphrase was not supplied via an env variable. I had to resort to `expect` to script `notary` so interactive entry of the passphrase does not work

**Comment by deitch** [comment]
> looks like the signing key passphrase was not supplied via an env variable. I had to resort to expect to script notary so interactive entry of the passphrase does not work

Ah that might do it. Bit of a pain though. Either way, can we document that restriction?

**Comment by deitch** [comment]
In any case, CI is green (finally). Can we get a review and approval to merge (or requested changes)?

**Pull request merged**
