### PR TITLE
Move metadata package to go modules

### PR DESCRIPTION
**Pull request by mraerino**
**- What I did**

Migrate the `pkg/metadata` program to go modules

**- How I did it**

Ran:

```
cd pkg/metadata
go mod init github.com/linuxkit/linuxkit/pkg/metadata
go mod tidy
go mod vendor
rm vendor.conf
```

**- How to verify it**

It should still build i guess

**- Description for the changelog**

Migrate `pkg/metadata` to use Go modules

**- A picture of a cute animal (not mandatory but encouraged)**

[](https://unsplash.com/photos/TG43wDuNPj0)

### CODE REVIEW

**Comment by mraerino** [comment]
[Network failure in CI?](https://github.com/linuxkit/linuxkit/pull/3618/checks?check_run_id=2266043292#step:5:161)

```
#10 1.400 go: github.com/diskfs/go-diskfs@v1.1.1: Get https://proxy.golang.org/github.com/diskfs/go-diskfs/@v/v1.1.1.mod: dial tcp: lookup proxy.golang.org on 168.63.129.16:53: dial udp 168.63.129.16:53: connect: network is unreachable
```

**Comment by deitch** [comment]
network access is disabled by default during package build, and has not been enabled [here](https://github.com/linuxkit/linuxkit/blob/3cb7dc3e369957f3f8dbbf6fb62f129c0802ba15/pkg/metadata/build.yml), nor should it be. Did you run `go mod vendor`?

**Comment by mraerino** [comment]
ah, looks like it needs an explicit `go build -mod vendor`

**Comment by mraerino** [comment]
ok, it looks like it might need changes to this file?
https://github.com/linuxkit/linuxkit/blob/master/tools/alpine/go-compile.sh#L36
the build setup seems pretty complex

afaik if you call `go build -mod vendor` it will not try to download anything

**Comment by deitch** [comment]
I can build it locally, but it fails if I do `lkt pkg build pkg/metadata`. @justincormack do you know what this is doing?

**Comment by rn** [comment]
Probably the `go-compile.sh` script from the alpine base need a similar treatment to the `go-compile` package https://github.com/linuxkit/linuxkit/pull/3616

**Comment by kulinacs** [comment]
I got this working locally by adding $MOD_ARG  to the `go vet`, `go test`, and `go install` lines plus some additional changes included below.

I'm not sure if the issue is with the vendor update or this is a bug in the original `go-compile.sh`, but after fixing the vendor issue the build fails with:

```
#8 1.190 [skipping] govet...
#8 6.889 ./provider_packet.go:123:11: github.com/vishvananda/netlink.GenericLink composite literal uses unkeyed fields
#8 6.924 sh: github.com/vishvananda/netlink.GenericLink: unknown operand
```

Fixing the vet complaint fixes the build completely.

**Comment by deitch** [comment]
I ran some tests and can confirm that @rn's proposed fix for `go-compile.sh` fixes the networking issue. I am opening a PR shortly to affect that.

Once that is in place, the `netlink.GenericLink` will need to be resolved, but that is a separate question.

**Comment by dave-tucker** [comment]
@mraerino could you rebase please now #3637 has merged. CI should then be green :crossed_fingers:

**Comment by mraerino** [comment]
looks like GitHub changed their CI policy for outside contributors, mind approving CI?

**Comment by dave-tucker** [comment]
All approved :+1:  :crossed_fingers:

**Comment by mraerino** [comment]
Hmm, looks like it segfaults or throws SIGILL on one platform. Will look in a bit.

**Comment by dave-tucker** [comment]
@mraerino yeah this looks like an issue emulating s390x issues in CI and not something introduced by your patch. I'm currently hitting the same issue in #3627 and i'm looking for potential fixes

**Comment by dave-tucker** [comment]
@mraerino thanks for the contribution! I've cherry picked your commit in to #3627 (you're still shown as the contributor in the git history) as it contains the necessary CI and UX changes to `linuxkit` to enable this to pass CI. It will be quicker to get it merged this way, and you won't have to keep rebasing! Therefore, I'll go ahead and close this PR. Thanks again!

**Pull request closed without merging**
