### PR TITLE
Change GCP metadata SSH keys URL

### PR DESCRIPTION
**Pull request by steeve**
**- What I did**

Tried to SSH on a linuxkit VM on GCP.
Got the following message on the serial console:
```
2018/07/14 23:19:48 GCP: Probe succeeded
2018/07/14 23:19:48 GCP: Failed to get ssh data: Failed to get sshKeys: GCP: Status not ok: 404
2018/07/14 23:19:48 GCP: Failed to get user-data: GCP: Status not ok: 404
```

**- How I did it**

```
$ gcloud compute ssh myinstance
```

**- Description for the changelog**

According to the [GCP doc](https://cloud.google.com/compute/docs/storing-retrieving-metadata) the URL is not `sshKeys` but `ssh-keys` now.

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by rn** [comment]
Thanks this looks good to me. I've rebuild the `linuxkit/metadata` package. Could you update the YAML files in a separate commit to pick up the changes. You can update the YAMLs with:
```
./scripts/update-component-sha.sh --image linuxkit/metadata:721562e6f3ba9b6c003f9e746ff7ee94796f525
```

**Comment by steeve** [comment]
Done!

**Comment by rn** [comment]
Oh, crap, I seem to have truncated the hash in my comment above. Could you update again with:

```
./scripts/update-component-sha.sh --image linuxkit/metadata:721562e6f3ba9b6c003f9e746ff7ee94796f5251
```

**Comment by steeve** [comment]
Done! I've also split in 2 commits as you wished before.

**Pull request merged**
