### PR TITLE
Added more log statements to linuxkit push aws command

### PR DESCRIPTION
**Pull request by kencochrane**
**- What I did**
Added more log statements to` linuxkit push aws`

**- How I did it**
added more debug statements where they were needed

**- How to verify it**
If you run a linuxkit push aws command with verbose you will see more logs.

**- Description for the changelog**
Added more log statements to` linuxkit push aws` command, for greater visibility. 

Signed-off-by: Ken Cochrane <kencochrane@gmail.com>

### CODE REVIEW

**Comment by justincormack** [comment]
didnt I just merge this in https://github.com/linuxkit/linuxkit/pull/1969 ?

**Comment by kencochrane** [comment]
@justincormack doh! I was busy trying to figure out my issue, didn't see the PR. I added a few more debug statements, which I find useful. I can back out the other change if you want.

**Comment by DieterReuter** [comment]
@kencochrane I do like the other other changes, I think we could improve the AWS support even more.

**Comment by justincormack** [comment]
If you could back out the duplicated change it would be better, I dont like git's weird non merge conflicts for identical changes...

**Comment by kencochrane** [comment]
sure, give me a few minutes, and I'll update the PR.

**Pull request merged**
