### PR TITLE
Add a restart and stop command to service.

### PR DESCRIPTION
**Pull request by justinbarrick**
Signed-off-by: justinbarrick <jbarrick@cloudflare.com>

**- What I did**

Added restart and stop commands to the `service` command to restart and stop services.

**- How to verify it**

Run `service restart someservice` and `service stop someservice`.

**- Description for the changelog**

Added restart and stop commands to the `service` command to restart and stop services.

### CODE REVIEW

**Comment by deitch** [comment]
CI is failing, probably should look at the above and figure out why.

**Comment by deitch** [comment]
I think that adding `stop` and `restart` is a good thing. I have some suggestions on the structure though. 

1. Why the `switch args[0]` statement [here in main.go](https://github.com/linuxkit/linuxkit/pull/3063/files#diff-d97c24f85a236f43d00bbda743ed98e0R102) and then another [here in start.go](https://github.com/linuxkit/linuxkit/pull/3063/files#diff-ff45df16bbcd1fbb7b9b7370398c6b50R50), when they basically do the same thing? Might as well just have the single one in `main.go` call the relevant `func` directly.
2. We should rename `start.go` to `cmd.go` if it will have `start`, `stop`, and `restart`; or alternatively have separate files `start.go`, `stop.go` and `restart.go`, each with its own `func`. Either way, match the filename to what it does.

That is about it.

**Comment by rn** [comment]
I'm looking into the CI failure. Seem the builders run out of diskspace. Might take a day or two to fix.

**Comment by talex5** [comment]
I've rebuilt it now with a larger disk. The build required 11G in the end. However, it still failed:

```
[+ 79m 02s] gofmt...
[+ 79m 02s] start.go
[+ 79m 02s] The command '/bin/sh -c go-compile.sh /go/src/cmd/service' returned a non-zero code: 1
```

**Comment by justinbarrick** [comment]
Thanks for the review everyone. Are you happy to merge this?

**Comment by justinbarrick** [comment]
Thanks!

**Comment by rn** [comment]
@justinbarrick I've build and pushed an updated `linuxkit/init` package with this change for x86, arm64, and s390x. Could you add a commit to this PR to update the hashes in the YAML files?

There is script, so something like this from the top level directory should do the right thing:
```
./scripts/update-component-sha.sh --image linuxkit/init:9c91a7f714d84ef5f7aac8ec31536db9001d9930
```

Once you pushed the new commit, CI should pick it up and hopefully it will pass

**Comment by justinbarrick** [comment]
I've got a merge conflict, but the button doesn't work for me since I don't have write access to Linuxkit. Do one of you want to press that or should I resolve it in my repo?

**Comment by rn** [comment]
Ah, its a conflict with the power change in https://github.com/linuxkit/linuxkit/pull/3030

Could you:
- drop the hash update commit
- rebase to master
- force push

I will then rebuild the init package and give you a new hash

can you then add a commit with the update of the YAMLs.

Sorry, but the way the hashes work we need to go though this again, but shouldn't take long

Thanks

**Comment by justinbarrick** [comment]
Done!

**Comment by rn** [comment]
Thanks for the patience. I've rebuild and pushed the `init` package for all arches. Could you now push a new commit again updating the `init` package to:
```
linuxkit/init:eca81db9b072eb431c057bab77797e169295fa1e
```

This now should not have merge conflicts and also the right meta-data

**Comment by deitch** [comment]
CI is green. I will merge it in. Thanks for all of it @justinbarrick

**Comment by justinbarrick** [comment]
Awesome, thanks so much!

**Pull request merged**
