### PR TITLE
[POS-17] Add more docker event types to trigger fstrim

### PR DESCRIPTION
**Pull request by aiordache**
Trigger fstrim for image/container/builder/volume prune events.

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

we should consider using a switch for this and if we need to log all these events, but it's fine for now

**Comment by thaJeztah** [comment]
@djs55 ptal

**Review by djs55 — APPROVED** [review]
Also LGTM!

**Comment by djs55** [comment]
OK, CI is green and PR approved. I think the next step is for me to merge this and then `linuxkit pkg push` (according to https://github.com/linuxkit/linuxkit/blob/master/docs/packages.md )

**Comment by djs55** [comment]
... slight delay on the `linuxkit pkg push` while I figure out how to build for s390 :)

**Pull request merged**
