### PR TITLE
Switch to vsock as a module

### PR DESCRIPTION
**Pull request by djs55**
**- What I did**

Modified the LinuxKit 4.14 kernel configuration so that `AF_VSOCK` is loaded as a module. This works around an upstream bug described in #3376 where `connect` returns `ENODEV` when `AF_VSOCK` is compiled statically.

This modified configuration is currently shipping in Docker Desktop. Ideally if this change is merged then Desktop could switch back to unmodified LinuxKit kernels.

**- How I did it**

I tweaked the 4.14 kernel config in the usual manner.

**- How to verify it**

Using `AF_VSOCK` on Hyper-V will work correctly afterwards. There's a test program on #3376.

**- Description for the changelog**
- Load `AF_VSOCK` as a Linux 4.14 kernel module to work around an upstream bug (see linuxkit/linuxkit#3376)

**- A picture of a cute animal (not mandatory but encouraged)**

a small but colourful bug

### CODE REVIEW

**Comment by rn** [comment]
Is this limited to 4.14 or also for 4.19 and 5.x?

**Comment by djs55** [comment]
I don't know -- I've not had a chance to try later kernels. I guess I can fire some PRs against the Desktop CI and see what happens :)

**Comment by rn** [comment]
I prefer having them as similar as possible. I'll update the other kernel configs

**Comment by djs55** [comment]
Thanks!

**Pull request merged**
