### PR TITLE
Update kernels to 5.10.47/5.4.129, remove 5.11.x and add 5.12.x

### PR DESCRIPTION
**Pull request by rn**
Also:
- Remove s390x kernel WIP #3676
- fix kconfig build
- add CONFIG_SQUASHFS_ZSTD

seaslug

### CODE REVIEW

**Comment by rn** [comment]
The CI failures in `LinuxKit Build Tests` seem transient.

The CI failure for kernel tests does not seem to have enough info on the failure, but when I ran it locally it complained:
```
starting kernel config sanity test with /proc/config.gz
FAILURE: mqueue filesystem missing
kernel config test failed!
Kernel config test suite FAILED
```
which is a bit odd since the `mqueue` FS is actually present when I checked with a getty container

**Comment by rn** [comment]
It's actually not `mqueue` but `oprofilefs`. Test test had a bug

**Comment by rn** [comment]
Pushed new version of the kernel config test

**Review by djs55 — APPROVED** [review]
LGTM!

**Pull request merged**
