### PR TITLE
Enable CONFIG_VIRTIO_FS

### PR DESCRIPTION
**Pull request by fredericdalleau**
Hello, for testing virtiofs I enabled CONFIG_VIRTIO_FS as suggested in https://virtio-fs.gitlab.io/howto-qemu.html

**- What I did**
Enable CONFIG_VIRTIO_FS=y in the configuration

**- How I did it**
Using sed, though I only tested kernel 5.10.47

**- How to verify it**
refer to https://virtio-fs.gitlab.io/.
It requires starting a virtiofs-enabled hypervisor and adding appropriate configuration to create the share. The virtiofs can then be mounted:
`$ mount -t virtiofs <tag> <mountpoint>`

**- Description for the changelog**
Enable CONFIG_VIRTIO_FS

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by djs55 — APPROVED** [review]
I managed to mount a virtio filesystem with @fredericdalleau 's test kernel, which is pretty exciting.

**Comment by djs55** [comment]
@rn let me know if you're too busy to look at the kernel-related PRs -- I've got time to help this week.

**Comment by rn** [comment]
sorry, ran out of time this weekend and won't have much time this week. @djs55 if you have cycles feel free to update

**Comment by djs55** [comment]
I've done some things... although I'm not sure they're the right things 😅 

On an amd64 machine and then an arm64 I ran `cd kernel; make push`. I think these succeeded (after I manually pulled the linuxkit/alpine image it needed). In my PR here I updated the hashes to trigger the CI: https://github.com/linuxkit/linuxkit/pull/3726

**Pull request merged**
