### PR TITLE
Update kernels to 4.19.3/4.18.20/4.14.82/4.9.138/4.4.164

### PR DESCRIPTION
**Pull request by rn**
blue-penguin

### CODE REVIEW

**Comment by rn** [comment]
there were more kernel updates. rolling them and will update this PR

**Comment by justincormack** [comment]
Bye 4.18. LGTM when green.

**Comment by rn** [comment]
kernels are not pushed yet...either network flakiness or hub flakiness...

**Comment by rn** [comment]
Looks like I finally managed to build and compile all kernels. I got a very weird assortment of errors on pushes both from the s390x and x86 system. Updated the YAMLs and see if the CI is barfing on not finding any packages...

**Comment by rn** [comment]
CI fails on `docker pull linuxkit/mkimage-gcp:e6cdcf859ab06134c0c37a64ed5f886ec8dae1a1`, which pulls fine on my system. Looks like more hub flakiness...sigh

**Pull request merged**
