### PR TITLE
Update to Alpine Linux 3.9 (plus cadvisor and linux-firmware update)

### PR DESCRIPTION
**Pull request by rn**
Update LinuxKit to use Alpine 3.9 almost everywhere.

A few exceptions:
- `mkimage/*efi*` has compilation errors (see https://github.com/linuxkit/linuxkit/issues/3295). Keep them on 3.8 for now.
- `pkg/bpftrace` does not compile (see https://github.com/linuxkit/linuxkit/issues/3296). Disable it for now.

This PR also contains two update to `linuxkit/alpine` since I discovered when building the `pkg` that the WireGuard alpine packages got slight restructured.I did not want to rebuild everything else I had build, so only `pkg/*` are build with the very latest `linuxkit/alpine`

Once this update passes CI I'll probably do a release. 

WIP https://github.com/linuxkit/linuxkit/issues/3282

lone-some-george

### CODE REVIEW

**Comment by rn** [comment]
Hmm, the datakit ci has not kicked in (yet). I've seen this before, maybe it'll kick in a little while

**Comment by justincormack** [comment]
datakit is building now.

**Comment by rn** [comment]
CI failed with kmod tests for 4.14.x onwards. Running locally, i get:
```
make -C /usr/src/linux-headers-4.14.104-linuxkit M=/kmod modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.104-linuxkit'
  CC [M]  /kmod/hello_world.o
cc1: error: cannot load plugin ./scripts/gcc-plugins/structleak_plugin.so
   Error relocating ./scripts/gcc-plugins/structleak_plugin.so: _ZN11symtab_node10dump_tableEP8_IO_FILE: symbol not found
cc1: error: cannot load plugin ./scripts/gcc-plugins/randomize_layout_plugin.so
   Error relocating ./scripts/gcc-plugins/randomize_layout_plugin.so: _Z13size_int_kindl14size_type_kind: symbol not found
make[2]: *** [scripts/Makefile.build:333: /kmod/hello_world.o] Error 1
make[1]: *** [Makefile:1535: _module_/kmod] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.104-linuxkit'
make: *** [Makefile:4: all] Error 2
```

The problem seems to be that the plugins were compiled with an older version of gcc.

Also looks like the LinuxKit kernel build is broken with this update. Will try to unbreak this first, and if that fixes the kmod tests push an update.

**Comment by rn** [comment]
With the latest commits, the kernel build is fixed but I had to disable the `perf` build (see https://github.com/linuxkit/linuxkit/issues/3299). To make this easier, I refactored the build of the `linuxkit/kernel-perf` package and moved the compilation into the `Dockerfile.perf`.

I've verified with a locally build kernel that the `kmod` tests pass with this new arrangement but have not yet recompiled all the current kernels. So the CI will fail again with this update.

@justincormack if you are ok with disabling `perf` builds for now (and the two new commits), I'll rebuild the current  set of kernel with the updated kernel build and kick CI again

**Comment by justincormack** [comment]
SGTM

**Comment by rn** [comment]
kernel config needed a little tweak (newer kernels configs record the gcc version) but new kernel pushed and CI kciked

**Pull request merged**
