### PR TITLE
Move coreos-grub build to its own image

### PR DESCRIPTION
**Pull request by deitch**
**- What I did**

Extracted the building of grub from the various places that use it - `tools/mkimage-raw-efi`, `tools/mkimage-iso-efi`, `tools/mkimage-qcow2-efi` - into its own package `linuxkit/grub` from source `tools/grub`, and just copy over the compiled `*.EFI` image as needed.

This will speed up builds of those images, and more importantly make it easier to move them to upstream grub and off of orphaned CoreOS grub, when ready.

**- How I did it**

Moved the common Dockerfile info over and updated the Dockerfiles in each of those packages.

**- How to verify it**

1. Build the grub image
2. Build the `mkimage-*-efi` image(s)
3. `lkt build -format tar | docker run -i <your mkimage>`
4. Boot

**- Description for the changelog**

Centralize common grub builds.

**- A picture of a cute animal (not mandatory but encouraged)**

**Note:** The images have not been fully pushed to docker hub quite yet. `arm64` pushes have been stuck. Will comment here when ready.

This will simplify much of #3309

### CODE REVIEW

**Comment by deitch** [comment]
This does *not* switch to `alpine:3.9` base for grub. There was a build problem with coreos grub and `alpine:3.9`. If I can get it to work, great, but let's not hold the incremental improvements up.

**Comment by rn** [comment]
Thanks. This looks good. I can help with pushing the arm64 image but this PR also needs to update the hash of the modified `mkimage-*` tools packages so that CI is actually picking them up

**Comment by deitch** [comment]
Thanks Rolf, but don’t help with the arm64. Let’s figure out why my push isn’t working for `linuxkit/grub` but is for the others. Otherwise will be stuck again next time.

**Comment by deitch** [comment]
> update the hash of the modified mkimage-* tools packages so that CI is actually picking them up

Update it where?

**Comment by rn** [comment]
I DMed you pushing/signing

> Update it where

```
% git grep linuxkit/mkimage
src/cmd/linuxkit/moby/linuxkit.go:    image: linuxkit/mkimage:a8680e89070591c8b9e80d54e185787c19921668
src/cmd/linuxkit/moby/output.go:                "iso":         "linuxkit/mkimage-iso:17c68596851349c9d8917459116f7d3409f12fdd",
src/cmd/linuxkit/moby/output.go:                "iso-bios":    "linuxkit/mkimage-iso-bios:50aedc359bc13ee2d472a73d6e6740740b809c95",
src/cmd/linuxkit/moby/output.go:                "iso-efi":     "linuxkit/mkimage-iso-efi:248673cd3784eb3664d0f80b5bd31829465ca784",
src/cmd/linuxkit/moby/output.go:                "raw-bios":    "linuxkit/mkimage-raw-bios:71a966249ffbb23a499cfca280bbabb8afbbd530",
src/cmd/linuxkit/moby/output.go:                "raw-efi":     "linuxkit/mkimage-raw-efi:a01ff1621b9945a63675e2a73d3fda064fad3c3f",
src/cmd/linuxkit/moby/output.go:                "squashfs":    "linuxkit/mkimage-squashfs:c409c0f2045a0b9bffec38b981994a3e02852443",
src/cmd/linuxkit/moby/output.go:                "gcp":         "linuxkit/mkimage-gcp:e6cdcf859ab06134c0c37a64ed5f886ec8dae1a1",
src/cmd/linuxkit/moby/output.go:                "qcow2-efi":   "linuxkit/mkimage-qcow2-efi:74cc5c7c4064c7d25d3caf08ab51cddd9b840ebe",
src/cmd/linuxkit/moby/output.go:                "vhd":         "linuxkit/mkimage-vhd:3820219e5c350fe8ab2ec6a217272ae82f4b9242",
src/cmd/linuxkit/moby/output.go:                "dynamic-vhd": "linuxkit/mkimage-dynamic-vhd:743ac9959fe6d3912ebd78b4fd490b117c53f1a6",
src/cmd/linuxkit/moby/output.go:                "vmdk":        "linuxkit/mkimage-vmdk:cee81a3ed9c44ae446ef7ebff8c42c1e77b3e1b5",
src/cmd/linuxkit/moby/output.go:                "rpi3":        "linuxkit/mkimage-rpi3:b787b1210a0e13456a8f128722f1134e3933907b",
test/cases/040_packages/013_mkimage/mkimage.yml:    image: linuxkit/mkimage:a8680e89070591c8b9e80d54e185787c19921668
```
the `mkimage-*` packages is primarily used by the `linuxkit` tool

**Comment by deitch** [comment]
Oh that. Yes. Good point.

**Comment by deitch** [comment]
It is somewhat frustrating that we cannot keep this to two changes: one to change this and test it, one to consume it. But the CI isn’t structured to pick it up that way.

**Comment by rn** [comment]
you can make it to commits, one to restructure and the second to pick up the changes

**Comment by deitch** [comment]
> you can make it two commits, one to restructure and the second to pick up the changes

Yeah, usually do (and I drive people crazy on other projects when they mix in things like changes with "generate code" type stuff in a single commit... :-) ), will do here.

The images pushed out; thanks to @rn for helping. Updating the test case and linuxkit cmd now.

**Comment by deitch** [comment]
Updated. Will let CI run

**Comment by deitch** [comment]
CI is clean. Going to merge this, and try separately to get `coreos/grub` to build off of `alpine:3.9`; not hold this up.

**Pull request merged**
