### PR TITLE
Update to tip of manifest-tool and opengcs/LCOW

### PR DESCRIPTION
**Pull request by rn**
- PR to manifest-tool to get the length for notary has been merged. Use official version now and update docs that `go get` now also works
- Update `opengcs` to latest and then update the LCOW blueprint
dog-rabbit

### CODE REVIEW

**Comment by justincormack** [comment]
You could also mention that manifest-tool is now available from our homebrew repo

**Comment by rn** [comment]
I would have if I'd known

**Comment by rn** [comment]
added a note on brew install as well

**Comment by justincormack** [comment]
LGTM

**Pull request merged**
